### ISSUE TITLE
Scripts menu not opening

### ISSUE THREAD

**Issue by Benur21** [bruderstein/PythonScript#100]
I just installed PythonScript_1.0.9.0_x64.msi from https://github.com/bruderstein/PythonScript/releases/tag/v1.0.9 to my 64bit Notepad++ installation.

I then restarted Notepad++, and when I was going to check its scripts, I noticed that the **Plugins -> Python Script -> Scripts** menu was not opening. I hover it, click it, nothing.

![image](https://user-images.githubusercontent.com/29681989/44681835-a8ffe300-aa39-11e8-8f5c-1fcb69b4c45a.png)

Is there some more stable PythonScript version for x64 notepad++? Thanks.

**Comment by bruderstein** [comment]
If you've only just installed it, have you created any scripts?

**Comment by Benur21** [comment]
I was expecting to see the samples and the startup.py. I need a working startup script.

**Comment by Benur21** [comment]
Okay, I tried to create a new script. Clicked "New Script", created a "test.py" on my desktop, then I wrote "asd" on it and saved. The Scripts menu still doesn't open.

On the instalation, I'm sure I left the default options, where the install samples option was enabled (all I know is I didn't change anything).
I just had the idea to check the installation to check for the scripts. The 5 samples are there, as well as the startup.py, at Notepad++\plugins\PythonScript\scripts.

**Comment by Benur21** [comment]
Just saying, I am now installing the 32 bits version of notepad++ (uninstalled 64 bits) so that it can have better compatibility with the plugins I need.

**Comment by ClaudiaFrank** [comment]
I don't have a problem using the 1.0.9 zip

![grafik](https://user-images.githubusercontent.com/16170444/44879690-b8d22e00-acaa-11e8-8595-9d16eb19080e.png)

May I ask what exactly you did? How did you install it and where to?
Can you post your notepad++ debug-info (availbale under ? menu

**Comment by Benur21** [comment]
I reinstalled Notepad++ x64 just to check this again.

This is what I did (after uninstalling other notepad++ versions):

### Install np++ x64:
I selected my installation location (personalized);
Added Portuguese in Localization;
Don't use %APPDATA%;

### Install PythonScript_1.0.9.0_x64
I selected my notepad++ installation location (personalized);

### This is the debug info:
```
Notepad++ v7.5.8   (64-bit)
Build time : Jul 23 2018 - 02:06:36
Path : C:\Users\rubjo\Desktop\Pastas\Programas\Instalações\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : PythonScript.dll DSpellCheck.dll mimeTools.dll NppConverter.dll 
```

Is there any PythonScript 1.2 version? I can't find it on the link of my first post, neither on google ("PythonScript 1.2").

**Comment by sasumner** [comment]
@Benur21 
> Is there any...1.2 version?
https://github.com/bruderstein/PythonScript/releases/tag/v1.2.0

**Comment by Benur21** [comment]
@sasumner Thank you.
I wonder why http://npppythonscript.sourceforge.net/ says that the latest version is 1.0.8.0 and not 1.2.0.0.

I tried this newer version (1.2) and it's working! 👍 Thank you.

I was also using version 1.0.8 for x86 notepad and [having problems](https://sourceforge.net/p/npppythonscript/discussion/1188886/thread/9552c0b9/) with it :/ 
Meh.

**Comment by chcg** [comment]
@Benur21 How to update the website or moving it to github pages, etc. is currently in clarification with the project owner.

**Comment by Benur21** [comment]
Yes I forgot to close
