### ISSUE TITLE
Add tooltip with script name when hover over script toolbar button

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#104]
I'm not sure this is something that Pythonscript can do, but it sure would be nice.  Reference the relevant part of this N++ Community thread discussion:  https://notepad-plus-plus.org/community/topic/16317/creating-copy-buttons

**Comment by pryrt** [comment]
this may be related to #32

**Comment by sasumner** [comment]
I think #32 covers it...sorry for the duplication...closing.
