### ISSUE TITLE
Add function for getting clipboard text into string variable

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#106]
If I want my Pythonscript to get the Windows clipboard text (for a purpose other than putting said text into the current document), I either have to write some ctypes code that directly handles the clipboard, or I have to editor.paste() the text into a document, figure out how the paste changed the document (so that I can get the pasted text's length, and then its value), and then editor.undo() the change.

The downside of the ctypes approach: The code is longish, and there's some complications when the source for the clipboard text is from a CMD.exe window, and in general:  Ugh!

The downside of the editor.paste() approach: To avoid having the paste text in the current document's redo history (after the undo), one has to create a temporary "new" file--this is slow and presents a visually negative screen flash to the user

The suggestion is to create a new function, suggested name of notepad.getClipboardText().  This function would obtain the clipboard text, with line-endings in the data that follow the active document's, and then return a string with the data.  If the clipboard doesn't contain text data then an empty string should be returned.

**Comment by sasumner** [comment]
A "hidden editor" technique described in these links:

* https://notepad-plus-plus.org/community/topic/18133/regex-rounding-numbers-python-script-does-not-run-properly

* https://notepad-plus-plus.org/community/topic/17631/assign-language-by-line

makes this current issue unnecessary, so I'm closing it.

In summary, one could create a "hidden editor" instance (using notepad.createScintilla()), do a .paste() into that hidden editor, and finally determine the clipboard contents by using .getText() on the hidden editor instance.

**Comment by alankilborn** [comment]
>makes this current issue unnecessary, so I'm closing it.

I would like to see this reopened.
Surely PythonScript itself should be able to give me the clipboard text content in a variable?

Currently I'm doing it this way (workaround, demo):

```py
from __future__ import print_function

from Npp import *

try:
    editor3h
except NameError:
    editor3h = notepad.createScintilla()

def clipboard_get_text():
    editor3h.clearAll()
    editor3h.paste()
    return editor3h.getText()

print('text in clipboard:|{}|'.format(clipboard_get_text()))
```

**Comment by chcg** [comment]
@alankilborn From a first look to me this seems to be something not directly related to with N++ and Pythonscript but a more general task in dealing with clipboard data. There are some more generic options, see https://stackoverflow.com/questions/101128/how-do-i-read-text-from-the-clipboard.

**Comment by alankilborn** [comment]
>From a first look to me this seems to be something not directly related to with N++ and Pythonscript but a more general task in dealing with clipboard data.

I don't know that that argument makes a lot of sense.

There are other clipboard functions:

* editor.copy()
* editor.copyText(text)
* editor.paste()

But I've no way to decide if I conditionally want the data in the clipboard in my document, without pasting it first, figuring out the length of what was pasted, examining the content and then deciding I don't want it, and then editor.undo()ing it, "corrupting" my document's undo buffer?

I can keep my workaround technique; I was just thinking that a new function was needed to complete the set of clipboard functions to make it nice for those new to the plugin (who would be looking for such a function, and really wouldn't understand the advanced workaround technique).

**Comment by chcg** [comment]
@alankilborn 
The difference is that the functions you are mentioning are part of scintillas interface, see e.g.:
https://github.com/bruderstein/PythonScript/blob/d181250d70f887eea9602f90f97a854161f86e5d/PythonScript/src/Scintilla.iface#L2350

and there is just a wrapper generated by the plugin for that

https://github.com/bruderstein/PythonScript/blob/d181250d70f887eea9602f90f97a854161f86e5d/PythonScript/src/ScintillaWrapperGenerated.cpp#L4658

From my understanding the feature request is something which is not available from scintilla but a wrapper around win32 functionality.

**Comment by alankilborn** [comment]
Understood, but there are other "helper" functions in PythonScript that aren't simple Scintilla wrappers.
Really, what should be concentrated on are features that make sense as complements to the Scintilla wrappers that don't make users seek external solutions (and make them wonder, "why can't I do what I need with what's provided by this plugin?").

**Comment by alankilborn** [comment]
Another workaround, with some special conditions on input:

```
def clipboard_get_text2():
    # get text from clipboard and very minimally affect undo/redo history
    assert editor.getSelections() == 1  # condition required because we will be pasting and then have to revert it
    assert editor.getSelectionEmpty()   # condition required because we will be pasting and then have to revert it
    assert editor.canPaste()
    current_pos = editor.getCurrentPos()
    doc_len_in_bytes_before_paste = editor.getLength()
    doc_was_modified_before_paste = editor.getModify()
    editor.beginUndoAction()
    editor.paste()
    num_bytes_in_clipboard = editor.getLength() - doc_len_in_bytes_before_paste
    retval = editor.getTextRange(current_pos, current_pos + num_bytes_in_clipboard)
    editor.deleteRange(current_pos, num_bytes_in_clipboard)
    editor.endUndoAction()
    if not doc_was_modified_before_paste: editor.setSavePoint()
    return retval
```
