### ISSUE TITLE
Context-Help does not include LANGTYPE enum

### ISSUE THREAD

**Issue by pryrt** [bruderstein/PythonScript#107]
It would be nice for the help file to include the LANGTYPE enum in the **Enums** section, and add the links there from the `getCurrentLang()` and `getLangType()` mentions of LANGTYPE.

**Comment by chcg** [comment]
See #94 and https://github.com/bruderstein/PythonScript/blob/master/docs/source/enums.rst#langtype -> will be part of next release.

**Comment by pryrt** [comment]
Cool, sounds great!  Thanks.
