### ISSUE TITLE
Problem with Python Script: npp + windows 8

### ISSUE THREAD

**Issue by mrkrotov** [bruderstein/PythonScript#11]
Hi!
At first, sorry for my english.
Sergey Chikuyonok has sent me to you as developer of python script.
I've got a problem with it - it doesn't respond on any actions from Sergey's plugin Emmet and doesn't show scripts Python Script > Scripts . Console is empty
It was installed through Plugin Manager.
I've got notepad 6.3.1 version
So if you can, please help me to solve the problem!
Thanks

**Comment by bruderstein** [comment]
Closing as no response.
