### ISSUE TITLE
docs/source/pythonprimer.rst links to python 3 tutorial, PythonScript uses python 2.7

### ISSUE THREAD

**Issue by pryrt** [bruderstein/PythonScript#115]
If you end up staying on python2.7, then docs/source/pythonprimer.rst should be updated to link to https://docs.python.org/2/tutorial/, rather than the existing link to https://docs.python.org/tutorial/ (which is the 3.7 tutorial).  

Of course, if issue #36 occurs, then this issue becomes moot. :-)

**Comment by chcg** [comment]
@pryrt Thanks for the hint. Some work started to switch to py3, see https://github.com/chcg/PythonScript/tree/python36_test. But probably that needs still quite some time to overcome the problems in startup of python3 console and maybe some diffs in string handling, etc.
