### ISSUE TITLE
PythonScript_1.3.0.0_x64.msi chooses "Program Files (x86)" for install

### ISSUE THREAD

**Issue by zenis0102** [bruderstein/PythonScript#118]
really **awesome** plugin and thanks for the new release but _x64 msi installer_ picks **Program Files (x86)** instead of **Program Files** for installation

**Comment by chcg** [comment]
Caused by https://github.com/bruderstein/PythonScript/blob/master/installer/PythonScript.wxs#L27 as ProgramFilesFolder defaults to 32bit, see https://docs.microsoft.com/de-de/windows/desktop/Msi/property-reference#system_folder_properties

64bit is ProgramFiles64Folder

**Comment by vsrawat** [comment]
> 64bit is ProgramFiles64Folder

There is no such folder.
32 bit should go to c:\Program Files (x86)\notepad+  folder
64 bit should go to c:\Program Files\notepad+ folder

Another bug is, it is not extracting PythonScript.dll and Python27.dll 
from msi for some strange reason.

I had noticed and changed the folder to 64 bit location when msi run, 
even then it has not extracted PythonScript.dll and Python27.dll

I had to manually extract from msi and put to respective location.

Thanks.
-- 
Rawat

**Comment by chcg** [comment]
@vsrawat Probably a sideeffect of the wrong parameters on msi creation and therefore the access rights to store executable code from a 32bit installer to the 64bit program files folder is prohibited by windows. 
I think I tested the installer with a portable version of N++ at some unrestricted folder location and that installation isn't facing this restriction.

**Comment by vsrawat** [comment]
oh, and last time, I installed through notepad++ plugin Admin (or 
Manager, I don't remeber), and that had installed in correct folder.

Actually, most of the users install it through plugin manager, and it 
got installed correctly, that is why the problem of Oct release didn't 
even surface till now, 4 months later.

Thanks.
-- 
Rawat

**Comment by zenis0102** [comment]
I wasn't sure that I should add this as another _New Issue_ or just add a comment here!

But seem like **PythonScript_1.3.0.0_x64** is not compatible with the latest Notepad++ (as of today Feb-6th-2019 the latest x64 version is **npp.7.6.3.Installer.x64.exe**) anymore due to the change of the way NPP++ installs and loads plugins.

I've done all following and still not been able to make it work with NPP:
1. Installed PythonScript_1.3.0.0_x64 through original installer but as I mentioned at my first post it goes to **Program Files (x86)** ant not to **Program Files**
2. Through installer I tried to manually change the installation path but the new path was NOT updated in installer and still it points to **Program Files (x86)** and even installs to **Program Files (x86)** either
3. I installed it as usual then tried to move installed files to NPP folder (**python27.dll** in root directory of NPP and the rest into _plugins_ directory) but it didn't worked because lately NPP has decided to put **plugins dll** and its associated files in their own specific folders (i.e. _AnyPlugin.dll_ and associated files into _AnyPlugin_ folder), refer to the 3th paragraph here [Notepad++ 7.6.3 released](https://notepad-plus-plus.org/news/notepad-7.6.3-released.html)

   > _Due to the security reason, from this version Notepad++ will load plugins only from &lt;NPP_INST_DIR&gt;\plugins\. In the case of installer, Notepad++ is installed in %ProgramFiles%\Notepad++\ - plugins are loaded from %ProgramFiles%\Notepad++\plugins\ instead of %ProgramData%\Notepad++\plugins\ in the previous version. This change has no impact on current loading behaviour of portable version. Sorry for the inconvenience regarding this change - I believe there's no more modification concerning the plugins location in the future._
4. I created _PythonScript_ folder inside _NPP plugins_ folder and moved PythonScript.dll and the other associated files and folders there but still ,to no avail, even moved **python27.dll** inside that folder and it didn't worked again
5. I created another _PythonScript_ folder inside previously-created _PythonScript_ folder like _C:\Program Files\Notepad++\plugins\PythonScript\PythonScript_ and moved **python27.dll** into _plugins\PythonScript_ and the dll and the rest to _plugins\PythonScript\PythonScript_ but again didn't worked
6. I did all in steps 4 and 5 in _%USERPROFILE%\Roaming\Notepad++_ and _%USERPROFILE%\Local\Notepad++_ but again no success

And finally I tried to find and install _PythonScript_ from **Notepad++ Plugin Admin** as _@vsrawat_ offered but _PythonScript plugin_ does not exist in **Notepad++ Plugin Admin** list anymore or maybe at least for me!

sorry for the long comment :(

**Comment by chcg** [comment]
There is already an issue for it #109. Currently this plugin is not adapted to N++ 7.6.x plugin changes and therefore it is not part of Notepad++ Plugin Admin list.

**Comment by chcg** [comment]
See https://github.com/wixtoolset/issues/issues/2165 and https://github.com/wixtoolset/issues/issues/5908. Tried to use 
`
		<?define PlatformProgramFilesFolder = "ProgramFiles64Folder" ?>`

for x64, but that doesn't help.

**Comment by chcg** [comment]
See https://github.com/bruderstein/PythonScript/releases/tag/v1.5.1
