### ISSUE TITLE
Consider using hwndFrom within scintilla notification

### ISSUE THREAD

**Issue by Ekopalypse** [bruderstein/PythonScript#121]
In order to distinguish which scintilla notification was sent by which scintilla instance it
would be nice to add this 
params["idFrom"] = notifyCode->nmhdr.idFrom; 
after 
params["code"] = notifyCode->nmhdr.code; 
in ScintillaWrapper.cpp
then one can use [SCI_SETIDENTIFIER](https://www.scintilla.org/ScintillaDoc.html#SCI_SETIDENTIFIER).
Preferable npp itself would set it and I will open a feature request there but for the time being it could be done from
pythonscript with something like editor1.setIdentifier(1) and editor2.setIdentifier(2)

**Comment by Ekopalypse** [comment]
As pointed out [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5327),
hwndFrom can be used to identify which editor sent which notification.
So, I guess, code should be like 
~~~~
params["hwndFrom "] = notifyCode->nmhdr.hwndFrom ;
~~~~

**Comment by chcg** [comment]
@Ekopalypse So my understanding is that all notifications should contain "hwndFrom" not just the unknown ones handled by the default case of the switch statement.

**Comment by Ekopalypse** [comment]
@chcg, correct and thank you for updating PS to the new scintilla version.

**Comment by chcg** [comment]
Added both hwndFrom and idFrom to all callbacks.
