### ISSUE TITLE
sqlite3.dll does not exist 

### ISSUE THREAD

**Issue by wuwao1** [bruderstein/PythonScript#123]
I don't find sqlite3.dll,  so I can't use sqlite3  unless I install  python 2.7.15 and take the sqlite3.dll from it.sorry for my poor English,I mean sqlite3.dll is not integrated.

**Comment by chcg** [comment]
@wuwao1 Your are right, sqlite is part of https://github.com/bruderstein/PythonScript/tree/master/PythonLib/full/sqlite3, but not the corresponding sqlite3.dll, which should be under 
https://github.com/bruderstein/PythonScript/tree/master/PythonLib/full_dll
and
https://github.com/bruderstein/PythonScript/tree/master/PythonLib/full_dll_x64

**Comment by chcg** [comment]
Fixed with commit https://github.com/bruderstein/PythonScript/commit/fa291adc6af283b05d67ef993d73a95dec4b4aa8
