### ISSUE TITLE
SCINTILLANOTIFICATION.CHARADDED: arg key ch is always 0

### ISSUE THREAD

**Issue by webketje** [bruderstein/PythonScript#127]
**Bug**
When a callback is registered on SCINTILLANOTIFICATION.CHARADDED, the keycode value for `args['ch']` is always 0

**Environment:**
- notepad.getAppdataPluginsAllowed() == True
- Notepad 7.7.1 (x64)
- PythonScript 1.4.0 (Full, x64)
- Win10

**Reproduce**
See python script in #126

**Comment by sasumner** [comment]
I can't comment on your script, but simple, straightforward usage works fine for me; example:

    def AC2IC__CharacterAdded(args):
        char_added_code = args['ch']
        # ...

    editor.callback(AC2IC__CharacterAdded, [SCINTILLANOTIFICATION.CHARADDED])

**Comment by Ekopalypse** [comment]
x64 issue, current PythonScript has not been updated to reflect new 7.7.1 notification struct,
x86 users are not affected by this change

**Comment by chcg** [comment]
Will fixed with https://github.com/bruderstein/PythonScript/releases/tag/v1.5.2
