### ISSUE TITLE
No longer works in the current Npp

### ISSUE THREAD

**Issue by mwpowellhtx** [bruderstein/PythonScript#128]
Couple of issues you need to address I think.

* As I understand it, the plugin model has changed.

* Bundle 32-bit and 64-bit together. Historically, there has been a confusion in the installers between these two, and/or a lack of proper 64-bit Npp support.

In the latest Npp version, when I install PythonScript, does not work. My scripts do not appear, cannot map short cuts, etc. This did work before, but not in the current version.

**Comment by chcg** [comment]
@mwpowellhtx See #109 for problems with N++ versions 7.6.x and 7.7.x. With upcoming version 7.8.x (https://community.notepad-plus-plus.org/topic/18323/notepad-7-8-release-candidate-4 - 5. Enhance plugin system: allow any plugin to load private DLL files from the plugin folder.) the base is available again to provide a proper installation of the pythonscript plugin by the builtin pluginAdmin. Additionally this needs some further updates for N++ interface changes and the underlying scintilla has changed from 3.5.6 -> 4.2.0. Currently working on that at https://github.com/chcg/PythonScript/tree/npp_7_7_interface.

**Comment by chcg** [comment]
See release https://github.com/bruderstein/PythonScript/releases/tag/v1.5.1. Usable again with N++ 7.8. Open issue is the availability via the builtin PluginAdmin.

**Comment by chcg** [comment]
See release https://github.com/bruderstein/PythonScript/releases/tag/v1.5.1. Usable again with N++ 7.8. Open issue is the availability via the builtin PluginAdmin.
