### ISSUE TITLE
Installation instruction is wrong for new versions of Npp

### ISSUE THREAD

**Issue by Joppest** [bruderstein/PythonScript#136]
See this post for correct installation instructions:
https://sourceforge.net/p/npppythonscript/discussion/1188886/thread/a0c09e284b/#8bc6

**Comment by sasumner** [comment]
@joppest Why didn't you post a link to the installation instructions that are wrong?  How can it be fixed if we don't know what you are referencing?

Also, perhaps a more current instruction is referenced in this thread on the N++ Community:  https://community.notepad-plus-plus.org/topic/18503/trying-to-get-python-script-and-testfx/

**Comment by chcg** [comment]
@Joppest As written in the community thread. If you are using N++ 7.8.1 the plugin is available from the builtin pluginAdmin and the installation should be working out-of-the-box.
