### ISSUE TITLE
is this can do....?

### ISSUE THREAD

**Issue by loveJasmine** [bruderstein/PythonScript#137]
my requirement:
Selected some texts, then I trigger one self shortcut, the text I selected will change as the rules I predefined by the plugin build by pythonscript

**Comment by sasumner** [comment]
That doesn't make a lot of sense.  You're going to have to expand on that before anyone can respond.

**Comment by chcg** [comment]
As sasummer said with this description no answer is possible. Could be reopened if new data is added.
