### ISSUE TITLE
someone working on an evolution towards python3 ?

### ISSUE THREAD

**Issue by stanpetit** [bruderstein/PythonScript#138]
Hi all!
Python27 is dying ... So what is the "future" of `from future import ...` ? None
Is someone working on an evolution towards Python3 ?
Best, Stan

**Comment by chcg** [comment]
There is some work on this, see https://github.com/chcg/PythonScript/commits/python36_test.
This is a duplicate to https://github.com/bruderstein/PythonScript/issues/36.
