### ISSUE TITLE
getLanguageDesc bug

### ISSUE THREAD

**Issue by pryrt** [bruderstein/PythonScript#146]
@Ekopalypse and I have noticed that there's a potential bug in PythonScript's implementation of getLanguageDesc: https://community.notepad-plus-plus.org/post/51274

We can get it to reliably crash using the brief script:
```
from Npp import notepad, LANGTYPE

LANGUAGES = LANGTYPE.values.values()
for language in LANGUAGES:
    print(notepad.getLanguageDesc(language))
```

When I run the equivalent script using my Perl Win32::Mechanize::NotepadPlusPlus to call the underlying NPPM_GETLANGUAGEDESC (or if Eko uses python's `ctypes.windll.user32.SendMessageW` to do the same), it works reliably.

**Comment by Ekopalypse** [comment]
Not sure, but I assume that [here](https://github.com/bruderstein/PythonScript/blob/master/PythonScript/src/NotepadPlusWrapper.cpp#L1018) one needs to add 1 to the buffer allocation.
but I might be wrong as I don't have sufficient c++ knowledge.

**Comment by pryrt** [comment]
well, [getPluginHomePath](https://github.com/bruderstein/PythonScript/blob/master/PythonScript/src/NotepadPlusWrapper.cpp#L506) _does_ use `[size+1]`, so that's likely it.

**Comment by chcg** [comment]
See N++ description of how to use NPPM_GETLANGUAGEDESC and NPPM_GETLANGUAGENAME and the size+1 was missing as you already found out.
Thanks.

**Comment by Ekopalypse** [comment]
The test itself seems to be fine. 
As far as I understand, boost:.python truncates the string by \0,
so there is no way for the test to see if it has been allocated correctly or not - I suppose.

**Comment by chcg** [comment]
Fixed with https://github.com/bruderstein/PythonScript/releases/tag/v1.5.4
