### ISSUE TITLE
docs intro.rst: invalid FILESAVING notification vs valid FILEBEFORESAVE

### ISSUE THREAD

**Issue by pryrt** [bruderstein/PythonScript#148]
The **Handling Notifications** section of the `intro.rst` goes back and forth from calling the notification `FILESAVING` (wrong) and `FILEBEFORESAVE` (correct).  Most of the instances of `FILESAVING` are in the text, rather than in the example code, so that's less problematic, but in the **Cancelling Callbacks** subsection, it's in the example code, too.  But to avoid confusion, they should all be `FILEBEFORESAVE`.

**Comment by chcg** [comment]
@pryrt Thanks for the hint. This will be available then with the next release. Probably after the final python 2.7.18 is available for integration.

**Comment by chcg** [comment]
Fixed with https://github.com/bruderstein/PythonScript/releases/tag/v1.5.4
