### ISSUE TITLE
Python3 - creation of standard files

### ISSUE THREAD

**Issue by Ekopalypse** [bruderstein/PythonScript#151]
How are the files in the standard lib directory created?
According to Pythonscript 3.0.1 x64.zip there is a Queue.py file in lib but it should be [queue.py](https://github.com/python/cpython/blob/3.8/Lib/queue.py).
The content of both files is the same, so I assume it is a windows quirk where
the filename did not get modified as it is, from windows point of view, the same name.

**Comment by chcg** [comment]
@Ekopalypse I do the checkins on windows and the case was changed between python 2.7 and python 3. And it took me some time to realize that git on windows is case insensitive. Fixed with https://github.com/bruderstein/PythonScript/commit/71181802bcdd13bc08c3a06139d4389b69966034
