### ISSUE TITLE
Failed to compile source code with VS2017

### ISSUE THREAD

**Issue by wuwao1** [bruderstein/PythonScript#152]
I tried to compile the source code with VS2017, but failed and got some error messages, as shown below.
![image](https://user-images.githubusercontent.com/29857592/88226878-5a980500-cc9f-11ea-9f9a-9e226bb45484.png)
![image](https://user-images.githubusercontent.com/29857592/88226952-713e5c00-cc9f-11ea-8243-c4067286cb12.png)

**Comment by chcg** [comment]
See https://github.com/bruderstein/PythonScript/blob/master/appveyor.yml.

1. googletest is a git submodule which requires an additional:
> git submodule -q update --init
2. Checkout https://github.com/bruderstein/PythonScript/blob/master/PythonScript/project/PythonSettings_appveyor.props and https://github.com/bruderstein/PythonScript/blob/master/PythonScript/project/packages_appveyor.config to use nuget packages for the necessary python libs
3. Current master is on the way to switch to python 3.8, so the documentation for release 1.3 is quite outdated for that, check pre-release 3.0.2
