### ISSUE TITLE
ps v3+ in not backword compatible with ps v1.5.4 so it shoud throw syntax errors for things not working now

### ISSUE THREAD

**Issue by vsrawat** [bruderstein/PythonScript#156]
One of my old pythonscript that was working till v1.5.4 had stopped working with ps v3 and I didn't even come to know about it not working, and it has messed all my data since I dutifully installed ps v3 on the day of its first release, and its later updates

I think it is due to unicode representation getting changed in python v3+ that wa adopted for ps v3+

my issue is: How do I know what has stopped with each update of npp/ pythonscript/ python?

How many of us dutifully every word of release note each of hundreds of software/ plugins/ addons/ drivers that we are using on our pc.

When we have installed something and seen it working once, we wish and believe that it will be forward compatible and will continue working in future updates of any component of it.

AND, if it doesn't work, we should be notified somehow that it will not work any more, so that we check what has stopped working and how to correct it.

There is the irresponsible work of a developer.

If something has stopped working in a ps update, we don't come to know that it has stopped working, and there is no message and we believe that it has worked behind the screen as earlier.

That is what is wrong. If some previous syntax has stopped working, python and/ or pythonscript developers should throw a syntax error for that right there in the first run, so that the user at least gets to know that it is not working any more, then the user either learn the new syntax and edit his script to work with the new update, or the user can revert to previous update to keep his old script working.

I think it is a mistake of pythonscript developers that they have allowed the old syntax as valid even when it is not working.

I think that is what alpha beta testings are for.

So I guess ps developers should give a thought to this.

Thanks.
-- 
Rawat

**Comment by Ekopalypse** [comment]
> One of my old pythonscript that was working till v1.5.4 had stopped working with ps v3 

Do you mind showing us the script to see what might have caused it?

> I think it is due to unicode representation getting changed in python v3+ that wa adopted for ps v3+

Unicode should work, every other encoding has issues.

> my issue is: How do I know what has stopped with each update of npp/ pythonscript/ python?

Note, PS 3.X is still ALPHA release and as such it shouldn't be used in production environments. The reason for providing
an ALPHA/BETA release is to get others involved in testing and reporting back their issues. The goal at the end is that
a script, written with >PS 1.0.8 works with PS 3.X as well AS LONG AS THERE IS NO python syntax difference.

>How many of us dutifully every word of release note each of hundreds of software/ plugins/ addons/

Don't understand what you trying to say.

> When we have installed something and seen it working once, we wish and believe that it will be forward compatible and will
> continue working in future updates of any component of it.

For RELEASE software I agree but for ALPHA/BETA versions this cannot be guaranteed.

> AND, if it doesn't work, we should be notified somehow that it will not work any more, so that we check what has stopped
> working and how to correct it.

Again, ALPHA releases are provided so that other can help the project to identify potential pitfalls ...

> There is the irresponsible work of a developer.

That's harsh - why do you think it is the case.

> If something has stopped working in a ps update, we don't come to know that it has stopped working, and there is no
> message and we believe that it has worked behind the screen as earlier.

Wait, do you say you got PS 3 automatically installed from Plugin Admin?? This shouldn't be the case.

> That is what is wrong. If some previous syntax has stopped working, python and/ or pythonscript developers should throw a 
> syntax error for that right there in the first run, so that the user at least gets to know that it is not working any more, then the 
> user either learn the new syntax and edit his script to work with the new update, or the user can revert to previous update to 
> keep his old script working.

If there is a python syntax error then you do get it displayed in the console.

> I think it is a mistake of pythonscript developers that they have allowed the old syntax as valid even when it is not working.

Ah, no - the syntax is defined by python.org not by the PythonScript plugin developer. And as said, you cannot run an
invalid python3 syntax with PS 3.X

> I think that is what alpha beta testings are for.

Correct.

> So I guess ps developers should give a thought to this.

No, PythonScript project needs YOUR help in this case. 
That's the whole reason for providing ALPHA/BETA releases.
There are tests which run but one cannot test everything. How should one know beforehand which libraries are used,
which npp/PS combination on which OS with which hotfix level ... 
Why do you think MS has issues after rolling out a fix.

Sorry, but your general complaint is not fair - I must even say, that it was your fault to install an ALPHA version and thinking everything works. (Always assuming that you have also installed PS manually and have not updated via PluginAdmin)

**Comment by vsrawat** [comment]
It could be my mistake that I had installed an alpha version, I somehow missed that aspect, if known I would not have installed.

But, even when I installed alpha version, I was supposed to give feedback on it. 

But when there is no error message is appearing how do I come to know that something is not working - by design or by mistake.

Ever since I installed v3+, entire things gave pretence of working as earlier, till yesterday when I noticed that one of my previous pythonscript has not done the work it was supposed to do. Then I posted first on npp forum, and members there told me about unicode compatibility.

So the issue is - unicode representation that was working previously is not working in ps v3+, but there is no error message, no breakdown of script. Users are not even coming to know that it is not working as it is for text manipulation that is not visible to naked eyes.

my question is - when previous syntax is not working anymore, why is that syntax retained in new update. ps v3+ should throw a syntax error or abort the script midtrack on finding previous syntax. The the use would come to know that this line is not working and he/ she will learn new unicode representation and will update his script.

Without any error message, and by keeping obsolete old syntax as valid, users are getting misinformed and our data is getting corrupted when ps finishes running peacefully but had not done the work it was supposed to do.

Developers should remove all obsolete syntax in new update.

Thanks.

**Comment by Ekopalypse** [comment]
> But, even when I installed alpha version, I was supposed to give feedback on it.

Yes, and that is very much appreciated.

> But when there is no error message is appearing how do I come to know that something is not working - by design or by
> mistake.
> Ever since I installed v3+, entire things gave pretence of working as earlier, till yesterday when I noticed that one of my
> previous pythonscript has not done the work it was supposed to do. Then I posted first on npp forum, and members there told 
> me about unicode compatibility.
> So the issue is - unicode representation that was working previously is not working in ps v3+, but there is no error message, 
> no breakdown of script. Users are not even coming to know that it is not working as it is for text manipulation that is not 
> visible to naked eyes.

I have found this code in the npp forum

~~~py
#coding=utf8
editor.beginUndoAction()
#removes ZERO WIDTH SPACE
editor.replace(unichr(8203),"")
#removes ZERO WIDTH NON JOINER
editor.replace(unichr(8204),"")
#removes ZERO WIDTH JOINER
editor.replace(unichr(8205),"")
editor.endUndoAction()
~~~

and if this is the one we are talking about I doubt that this code did not raise a NameError exception.
unichr is no longer included in Python3. The error was certainly displayed in the console. 
But again for clarification, PS3 and files that are Unicode decoded (utf8) should not have any problems.
Files which are for example CP1252 etc... encoded are still causing problems at the moment.
But this is clearly noted on the release page.

> my question is - when previous syntax is not working anymore,  ...
> Developers should remove all obsolete syntax in new update.

Perhaps we have a different understanding of the term syntax. 
If this refers to the classes, methods, functions and attributes that PS provides via the editor, notepad and console objects, 
then these are valid and work, according to the current status, to the announced extent. However, if this means Python syntax, then PS has no influence on this, but this problem would be indicated by an exception in the console, unless you have just found a situation where this is not the case. 
By the way, I tested your code and it shows an exception.

~~~py
Traceback (most recent call last):
  File "D:\...\issue156.py", line 6, in <module>
    editor.replace(unichr(8203),"")
NameError: name 'unichr' is not defined
~~~

**Comment by vsrawat** [comment]
> I have found this code in the npp forum
> 
> #coding=utf8
> editor.beginUndoAction()
> #removes ZERO WIDTH SPACE
> editor.replace(unichr(8203),"")
> #removes ZERO WIDTH NON JOINER
> editor.replace(unichr(8204),"")
> #removes ZERO WIDTH JOINER
> editor.replace(unichr(8205),"")
> editor.endUndoAction()
> 

Yes, this was my tiny script.

To elaborate: It just removes zero-width space, zero-width joiner/ 
non-joiner, etc. unicode characters that google translate somehow 
inserts in translated text. These are not visible so we can't see them 
to figure out their presence, but their invisible presence messes up 
with any "SEARCH" in any software, and subesequent find/ replace 
collapses for that instance.

> and if this is the one we are talking about I doubt that this code did 
> not raise a NameError exception.
> unichr is no longer included in Python3. The error was certainly 
> displayed in the console.
> But again for clarification, PS3 and files that are Unicode decoded 
> (utf8) should not have any problems.
> Files which are for example CP1252 etc... encoded are still causing 
> problems at the moment.
> But this is clearly noted on the release page.
> 
>     my question is - when previous syntax is not working anymore, ...
>     Developers should remove all obsolete syntax in new update.
> 
> Perhaps we have a different understanding of the term syntax.
> If this refers to the classes, methods, functions and attributes that PS 
> provides via the editor, notepad and console objects,
> then these are valid and work, according to the current status, to the 
> announced extent. However, if this means Python syntax, then PS has no 
> influence on this, but this problem would be indicated by an exception 
> in the console, unless you have just found a situation where this is not 
> the case.
> By the way, I tested your code and it shows an exception.
> 
> Traceback  (most  recent  call  last):
>    File  "D:\...\issue156.py",line  6,in  <module>
>      editor.replace(unichr(8203),"")
> NameError:name  'unichr'  is  not  defined
> 

I had debugged my script once and found it working. of course that was 
done in ps console.

I never opened ps console ever since.

How do I know that I need to open console and see errors there.

Do all users who are using ps in npp have to debug all of their scripts 
again and again with each update of python and pythonscript? and maybe, 
of npp too?

Give to thought to it from the angle of us newbie users of ps.

This entire process is very tedious, complicated, cumbersome. We newbies 
are overwhelmed with such a drill.

When old unicode representation doesn't work, the pythonscript should 
have aborted right there giving such a message on the main npp window.

Why exactly is a deprecated unicode representation retained in ps with 
such a level that peacefully allows successful processing of a ps 
script, while the script has failed to do the intended work.

Something is drastically amiss there.

I am 60 years old, have worked with dos, cp/m, unix, GWbasic, Wordstar 
lotus, vi, command line interpreters, assemblers, compilers,
And still my entire life time of experience fails to justify how can 
pythonscript let a faulty script run so peacefully and successfully?

My 90,000 rows of excel data had got corrupted as those characters that 
my tiny pythonscript was supposed to remove, didn't get removed and are 
present there, I don't know where as they are not visible.

I will have to figure out unicode char find replace in word excel. Seems 
I should give up pythonscript and stick of msword-excel macros, they are 
irritatingly and thankfully very verbose in throwing erorrs. :-)

ps developers should kindly give a thought to all this.

Thanks.
-- 
Rawat

**Comment by vsrawat** [comment]
To add: my that problem got solved by removing ps v3+ from npp and 
reinstalling ps v.1.5.4

My that script runs satisfactorily now.

so that issue is gone.

but handling and display of ps errors within npp should be thought about.

I wonder whether that is a useful feedback from alpha testing of ps v3+.

Thanks.
-- 
Rawat

**Comment by chcg** [comment]
For python3 see https://stackoverflow.com/questions/2352018/cant-use-unichr-in-python-3-1, so unichr was changed to just chr.
It is possible to adapt the script to be usable with both python versions.
With the switch to python 3 as basis it is not possible to reuse all existing scripts without the necessary modifications for the python version incompatibilities. This can't be handled by the plugin as there is no version information within script files to detect such version related differences.

**Comment by Ekopalypse** [comment]
> I had debugged my script once and found it working. of course that was
> done in ps console.
> I never opened ps console ever since.
> How do I know that I need to open console and see errors there.

Hmm, not sure but I guess this works like any other scripting environment.
A script is executed and some kind of console must display the output in case of an error.

> Do all users who are using ps in npp have to debug all of their scripts
> again and again with each update of python and pythonscript? and maybe,
> of npp too?

I can't say, because I don't know how the users use PS and with what level of knowledge.
But don't you think that there is also a responsibility of the users?
Shouldn't every user of the software learn at least the basics of this software?
I am well aware of the fact that not every user has the time and desire to deal with every detail of the software,
but knowing the basics is essential in my opinion.

> Give to thought to it from the angle of us newbie users of ps.
> This entire process is very tedious, complicated, cumbersome. We newbies
> are overwhelmed with such a drill.

Which process do you mean?

> When old unicode representation doesn't work, the pythonscript should
> have aborted right there giving such a message on the main npp window.
> Why exactly is a deprecated unicode representation retained in ps with
> such a level that peacefully allows successful processing of a ps
> script, while the script has failed to do the intended work.
> Something is drastically amiss there.

In my opinion this already exists, check the box for
"automatically open console on error" in the PS configuration

> I am 60 years old, have worked with dos, cp/m, unix, GWbasic, Wordstar
> lotus, vi, command line interpreters, assemblers, compilers,
> And still my entire life time of experience fails to justify how can
> pythonscript let a faulty script run so peacefully and successfully?

> My 90,000 rows of excel data had got corrupted as those characters that
> my tiny pythonscript was supposed to remove, didn't get removed and are
> present there, I don't know where as they are not visible.

> I will have to figure out unicode char find replace in word excel. Seems
> I should give up pythonscript and stick of msword-excel macros, they are
> irritatingly and thankfully very verbose in throwing erorrs. :-)

This is of course also an approach. Good luck with it.

> ps developers should kindly give a thought to all this.

I'm sure they do, but I am afraid no matter what they do, there will always be users
who want what PS does to be different because it suits their way of using it.
Unfortunately I don't know the formula how to make everyone happy, otherwise I would share it here.

**Comment by vsrawat** [comment]
On 9/6/2020 5:17 PM, Ekopalypse wrote:
> 
> In my opinion this already exists, check the box for
> "automatically open console on error" in the PS configuration
> 

Yes, I found it now. it was unticked and I ticked it now.

now errors will open console automatically. That should be default 
behavior, I don't remember whether I had unticked it myself earlier.

Thanks.
-- 
Rawat
