### ISSUE TITLE
release mail should mention whether it is alpha or beta version or final release.

### ISSUE THREAD

**Issue by vsrawat** [bruderstein/PythonScript#157]
The release mail received just now, quoted below, doesn't even mention that it is alpha version.

I guess that is why I just mechanically clicked on links and downloaded and installed previous releases without knowing that were alpha, that caused big problems for me.

Please consider mentioning in all such release mail whether these are alpha or beta versions of final releases.

Thanks.
-- 

v3.0.4

Repository: bruderstein/PythonScript · Tag: v3.0.4 · Commit: 5003891 · Released by: bruderstein
—

This release has 7 assets:

    PythonScript_3.0.4.0_x64.msi
    PythonScript_Full_3.0.4.0_x64.zip
    PythonScript_Full_3.0.4.0_x64_PluginAdmin.zip
    PythonScript_Min_3.0.4.0_x64.zip
    PythonScript_TclTk_3.0.4.0_x64.zip
    Source code (zip)
    Source code (tar.gz)

Visit the release page to download them.

—
You are receiving this because you are watching this repository.
View it on GitHub or unsubscribe from all notifications for this repository.

**Comment by sasumner** [comment]
>I guess that is why I just mechanically clicked on links and downloaded...

I think you did that because you are an "unusual" fellow.

I don't know that Pythonscript developers have great control over content of emails that you may be subscribed to from github; probably not.  Suggest you berate github itself for such an indiscretion, if you are so inclined, and I wish you good luck with that.

Of course, any of the linkage from that email takes you to a page where 3.0.4 is clearly an "alpha" version.
If, that is, you take some responsibility for your actions, and read the information (recommended).

**Comment by vsrawat** [comment]
Righto buddy.

Everything is end users' responsibility and everything is end users' risk.

Developers should not be expected to listen to any single thing posted 
on this forum, not even a simple obvious useful thing like mentions 
words like alpha/ beta/ RC.

In that case, why is this mailing list for? Is it just an announcement list?

People like you are actually trolls that come to criticize any smallest 
suggestion given on this forum, thinking that a suggestion is actually a 
criticism of the software or the developers and you would come in good 
books of developers and might reap some benefit.

Anything said on a list and people like you arrive to undermine and 
attack the person who had posted that.

Thoughts like yours are biggest hindrance of free discussion and 
exchange of ideas on a forum.

Thanks.
-- 
Rawat

**Comment by chcg** [comment]
I will add alpha to the next tags to make that more clear.
