### ISSUE TITLE
Python Script 3.0.4 - runMenuCommand issue

### ISSUE THREAD

**Issue by Ekopalypse** [bruderstein/PythonScript#158]
running
~~~py
notepad.runMenuCommand('Macro', 'Trim Trailing Space and Save')
~~~

doesn't open the save dialog and leaves PS in a blocked stated.

![image](https://user-images.githubusercontent.com/47723516/94430709-a3cf6e00-0194-11eb-939a-4e9c47fd8bfe.png)

**Comment by chcg** [comment]
@Ekopalypse Seems for my configuration that macro call is working:
```

Notepad++ v7.9   (64-bit)
Build time : Sep 22 2020 - 03:19:04
Path : C:\Users\christian\Source\Repos\npp.7.9.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : HexEditor.dll PythonScript.dll 
```

**Comment by Ekopalypse** [comment]
@chcg ok, thank you for trying, running manually works.
So it must be something I defined/configured, hmm.
I'm closing it for now and try to see what the problem is.
If I find it out and it is relate tp PS I will reopen it.
