### ISSUE TITLE
Add double click support in configuration dialog

### ISSUE THREAD

**Issue by cmeriaux** [bruderstein/PythonScript#163]
To ease the configuration, add support of double click in the configuration dialog.

In the file tree-view, a double click action append to the **Menu itmes** the selected script

In the menu Items list and toolbar icons list, a double click action remove the selected script from this list .

**Comment by sasumner** [comment]
Isn't this a pure duplicate of #162 ??

**Comment by cmeriaux** [comment]
oupss !! sorry !!!
