### ISSUE TITLE
Feature requests for limitations I faced with Python Scripts

### ISSUE THREAD

**Issue by StoopidoMan** [bruderstein/PythonScript#165]
Something like this:

1- menu [pluggins> Python Script> Running Scripts] and have a list of running scripts, and each script would have Reload/Stop sub-menu entries .

2- Currently it is possible to add a button to Menu, and Toolbar to run a script, I think it would be amazing to be able to have a button to stop the script and another for starting it, and a toggle button that have two states on/off with two(two icons for it).

3- be able to run [User Scripts]  at NPP startup, instead of on running the [STARTUP.py] 
![image](https://user-images.githubusercontent.com/71223069/98647478-59720d00-234e-11eb-863c-3a8ad114880c.png)

4- Toolbar icon/button customizable tooltip

let me know If I should create a separate issue for each feature request.

**Comment by Ekopalypse** [comment]
1. - you can only have one running script, so I don't see the benefit
2. - there is a stop script function in the python script menu
3. - create a new script called startup.py and it will create a "user" startup py. Use the python import mechanism to start your scripts
4. already an open issue - afaik.

**Comment by chcg** [comment]
ad 4. See #32 which requested to add the script name as tooltip. The tooltip would be not customizable by the user in this case.
