### ISSUE TITLE
Bug: [Set Icon...] not working with any .ico file

### ISSUE THREAD

**Issue by StoopidoMan** [bruderstein/PythonScript#166]
there is several issues with the [Set icon...] feature:

1- I tried different .ico files at different resolution 16x16 and 24x24 but all of them didn't work without warning. There is no documentation suggesting anything about it, so is this a bug? Additionally adding an error message if possible would help new users like me. 
 
2- I switch to .bmp, it worked but the button/icon size is too small to use for most kind of icons, and it is smaller than other icons in the toolbar:
![image](https://user-images.githubusercontent.com/71223069/98649732-59274100-2351-11eb-99b3-df28e611e16c.png)

I used a blue border to see if the image is scaled to fit, and indeed it is, so the issue is not the dimension of the .bmp file.  I suggest giving the user more granule settings over the icon such as their size.
 
Additionally, the icon is offset to the top right area:
![image](https://user-images.githubusercontent.com/71223069/98649911-9db2dc80-2351-11eb-9f7b-4baf0f970a29.png)

**Comment by dfs-** [comment]
Seems the offset issue is caused by the high dpi settings @StoopidoMan uses.

**Comment by Ekopalypse** [comment]
Can be closed - implemented with #366

**Comment by chcg** [comment]
@StoopidoMan You may want to test the new option to use 16x16 icons now with https://github.com/bruderstein/PythonScript/releases/tag/v3.0.20
