### ISSUE TITLE
Helper Methods  editor.forEachLine(testContents(contents, lineNumber, totalLines)) 

### ISSUE THREAD

**Issue by liyanggang** [bruderstein/PythonScript#174]
Traceback (most recent call last):
  File "D:\MyProgram\npp.7.8.9.bin.x64\plugins\Config\PythonScript\scripts\format_sql.py", line 126, in <module>
    f_AlignLeftByString('WITH(NOLOCK)')
  File "D:\MyProgram\npp.7.8.9.bin.x64\plugins\Config\PythonScript\scripts\format_sql.py", line 26, in f_AlignLeftByString
    editor.forEachLine(f_getPositionMax(contents, lineNumber, totalLines))
NameError: global name 'contents' is not defined

How to call this method？

**Comment by sasumner** [comment]
This isn't an "issue".  This is a "question".  A good place to ask questions of this nature, and receive responses is https://community.notepad-plus-plus.org/

**Comment by vsrawat** [comment]
Thanks for guiding to right place.

I am also using npp, but as this part was not at all related to npp, I was using fr in firefox, so I couln't connect on what pretext to ask it in npp forum, so I asked here.

Actually it is obvious that re or fr doesn't carry effect of a table entry from top to bottom. fr doesn't "remember" what it has converted in previous table entries, so it can't include/ exclude anything in later entries based on previous conversion.
So, it was an entirely fr question, whether some method or trick is available to achieve it.
re is a one time affair, there is no sequential execution of re, as in fr.
So, anyone not using fr wouldn't be able to understand the requirement or to answer it. 

I see my requirement but I am myself unable to think how it can be achived in fr, meaning how to keep track of what was converted by earlier entries, 
So I cannot suggest a potential solution. 
If more people feel such a requirement, hope somebody would think of and suggest a method.

Thanks.

**Comment by vsrawat** [comment]
re lookahead would become very complex, there are logs of domain name, domaiin extensions, email ids. it will be gigantic to include all in one lookahead, and the list will keep on growing as new domain names/ emaid id, website URLs are getting added in my text,

I and going to try a simpler method for my need.

After execution of all my tables (7 of them in succession in one go), all my english text gets converted to Hindi/ Devanagari, and Hindi/ Devanagari doesn't have capital/ small letters. so the input English text being in small or capital doesn't make a difference for my end output.

I am thinking that I keep all input text in lower letters, it can be done in npp by a single keystroke. 
then in fr tables first convert known domain names/ emaid id, website URLs from small to all CAPITAL letters.
Then run my tables, converting all, irrespective of case.
When it comes to converting individual letters, convert then case sensitive, convert only individual English small letters from English to Hindi.
that leaves all my domain names/ emaid id, website URLs that were in CAPITAL letters, uncoverted.
convert those english things again to proper case if URLs are written in some special combo of small-capital.

Theoretically it is likely to work. If some other fr user faces similar requirement in future, let this post be an archive of this solution.

Thanks.

**Comment by chcg** [comment]
@liyanggang See https://github.com/bruderstein/PythonScript/blob/2e7140288039c854d171db49fbd16b0b9c69a14a/docs/source/scintilla.rst for forEachLine. Also you didn't add a code snippet it seems you are calling f_getPositionMax with parameters:

`editor.forEachLine(f_getPositionMax(contents, lineNumber, totalLines))`

, but it should be just the function name like in the sample:

`editor.forEachLine(f_getPositionMax)`

Could that be your problem? Otherwise a code snippet would be helpful and the plugin version of pythonscript.

**Comment by liyanggang** [comment]
def f_getPositionMax(contents, lineNumber, totalLines):
    global v_string
    global v_position_max
    v_position_cur = contents.find(v_string)
    if v_position_cur > v_position_max : v_position_max = v_position_cur

def f_forEachLine(contents, lineNumber, totalLines):
    global v_string
    global v_position_max
    v_position_cur = contents.find(v_string)
    if v_position_cur != -1 :
        v_position_diff = v_position_max - v_position_cur + len(v_string)
        editor.replaceWholeLine(lineNumber, contents.replace(v_string,v_string.rjust(v_position_diff,' ')))

def f_AlignLeftByString(v_align_string):
    global v_string
    global v_position_max
    v_string = v_align_string
    v_position_max = 0
    editor.forEachLine(f_getPositionMax)
    editor.forEachLine(f_forEachLine)

f_AlignLeftByString('=')
