### ISSUE TITLE
How to use the editor.forEachLine() on PythonScript_Full_3.0.4.0_x64

### ISSUE THREAD

**Issue by liyanggang** [bruderstein/PythonScript#175]
/*################################################################################################*/

-- PythonScript_Full_3.0.4.0_x64

```python
def f_getPositionMax(contents, lineNumber, totalLines):
    global v_string
    global v_position_max
    v_position_cur = contents.find(v_string)
    if v_position_cur > v_position_max : v_position_max = v_position_cur

def f_forEachLine(contents, lineNumber, totalLines):
    global v_string
    global v_position_max
    v_position_cur = contents.find(v_string)
    if v_position_cur != -1 :
        v_position_diff = v_position_max - v_position_cur + len(v_string)
        editor.replaceWholeLine(lineNumber, contents.replace(v_string,v_string.rjust(v_position_diff,' ')))

def f_AlignLeftByString(v_align_string):
    global v_string
    global v_position_max
    v_string = v_align_string
    v_position_max = 0
    # editor.forEachLine(f_getPositionMax)
    # editor.forEachLine(f_forEachLine)
    editor.forEachLine(f_getPositionMax())
    editor.forEachLine(f_forEachLine())

f_AlignLeftByString('WITH(NOLOCK)')
f_AlignLeftByString('=')
```

/*################################################################################################*/

-- Error info

Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
Initialisation took 235ms
Ready.
Traceback (most recent call last):
  File "D:\MyProgram\npp.7.8.9.bin.x64\plugins\Config\PythonScript\scripts\format_sql.py", line 126, in <module>
    f_AlignLeftByString('WITH(NOLOCK)')
  File "D:\MyProgram\npp.7.8.9.bin.x64\plugins\Config\PythonScript\scripts\format_sql.py", line 26, in f_AlignLeftByString
    editor.forEachLine(f_getPositionMax())
TypeError: f_getPositionMax() missing 3 required positional arguments: 'contents', 'lineNumber', and 'totalLines'

/*################################################################################################*/

editor.forEachLine() is normal in PythonScript_Full_1.5.4.0_x64 How to use this method in PythonScript_Full_3.0.4.0_x64 ?

How to use the editor.forEachLine() on PythonScript_Full_3.0.4.0_x64 ？``

![20201214113200](https://user-images.githubusercontent.com/25525551/102037952-0d106600-3e01-11eb-90a4-a436c101f5f0.png)
![20201214112847](https://user-images.githubusercontent.com/25525551/102037960-126db080-3e01-11eb-9996-220472e988ff.png)

**Comment by chcg** [comment]
Checked sample script https://github.com/bruderstein/PythonScript/blob/1402c12944cdad041595043812f324b0e3131dcc/scripts/Samples/Remove%20and%20Modify%20selected%20lines.py which still works as expected.

**Comment by liyanggang** [comment]
> Checked sample script https://github.com/bruderstein/PythonScript/blob/1402c12944cdad041595043812f324b0e3131dcc/scripts/Samples/Remove%20and%20Modify%20selected%20lines.py which still works as expected.
> 
> @liyanggang
> 
> Why did you replace
> 
> ```
> # editor.forEachLine(f_getPositionMax)
> # editor.forEachLine(f_forEachLine)
> ```
> 
> by
> 
> ```
>     editor.forEachLine(f_getPositionMax())
>     editor.forEachLine(f_forEachLine())
> ```
> 
> ? The commented versions are still functional according to my tests. Testfiles are stored as UTF-8.
> 
> ![grafik](https://user-images.githubusercontent.com/12630740/102139994-e84adb80-3e5e-11eb-96fd-6f1840e0dc91.png)
> 
> According to your images above you are using ASCII encoded files GB2312. This is not supported yet for https://github.com/bruderstein/PythonScript/releases/tag/v3.0.4
> 
> > 
> 
> **Attention: This is a developer/early adaptor version which is no longer compatible to existing python 2.7 scripts. See e.g. https://www.guru99.com/python-2-vs-python-3.html on the differences. Apart from that see the missing features/open issues below.**
> 
> > Missing features:
> > support for files with encodings that are not unicode

thank you very much! It is indeed because I am using the ASCII encoded file GB2312 which caused an error, and the file was stored as UTF-8 and executed successfully.
(Note: The reason for replacing the commented version is for Python 3.x syntax considerations. I would like to ask when will the 3.x version be officially released?)

**Comment by chcg** [comment]
@liyanggang The main blocker for the python 3 release is the broken ASCII support. Unclear how to fix it and how long that will take.

**Comment by liyanggang** [comment]
received. Thank you for your email reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chcg"<notifications@github.com&gt;; 
发送时间: 2020年12月16日(星期三) 下午4:41
收件人: "bruderstein/PythonScript"<PythonScript@noreply.github.com&gt;; 
抄送: "liyanggang@maiyuesoft.com"<2608633186@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [bruderstein/PythonScript] How to use the editor.forEachLine() on PythonScript_Full_3.0.4.0_x64 (#175)





 
@liyanggangpython 3 版本的主要拦截器是损坏的 ASCII 支持。不清楚如何修复它， 以及这需要多久。
 
•
您收到此消息是因为您被提及。
直接回复此电子邮件，在 GitHub上查看，或取消订阅。
