### ISSUE TITLE
Problem with using ampersand in notepad.prompt() prompt text

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#176]
When using an ampersand ( `&` ) in the "prompt" argument to `notepad.prompt()` it gets "distorted" in a way that Windows programmers will easily understand. :-)

Examples:

`notepad.prompt('Tom & Jerry', '', '')`
produces:
![image](https://user-images.githubusercontent.com/30118311/102533054-e22d4880-4072-11eb-804f-2809ef13bb97.png)

`notepad.prompt('Tom&Jerry', '', '')`
produces:
![image](https://user-images.githubusercontent.com/30118311/102533137-fe30ea00-4072-11eb-9a1f-e260b7fdb051.png)

The example directly above **_SHOULD_** produce the following:
![image](https://user-images.githubusercontent.com/30118311/102533216-1e60a900-4073-11eb-86eb-41c556cf7c27.png)

Pythonscript 1.5.2.0

**Comment by chcg** [comment]
Reproducible up to release 3.0.4 .
Further chars are also broken, e.g.:
 
`notepad.prompt('ß!"§$%&/()=?´`öä#ü+ÖÄÜ*', 'ß!"§$%&/()=?´`öä#ü+ÖÄÜ*', '')`

![grafik](https://user-images.githubusercontent.com/12630740/102535803-0441bd80-40a9-11eb-8948-ac26f4196480.png)

**Comment by chcg** [comment]
The described issue is caused by:
https://docs.microsoft.com/en-us/windows/win32/dlgbox/dlgbox-programming-considerations#mnemonics
and could be avoided by usage of SS_NOPREFIX:
https://docs.microsoft.com/en-us/windows/win32/controls/static-control-styles
or escaping of & by &&.

**Comment by sasumner** [comment]
Since there is no real need for "underlined accelerators" in the `notepad.prompt()` box that I can see, if I were implementing it I would avoid them entirely, possibly using the `SS_NOPREFIX` thing, although I didn't read about it.

>escaping of & by &&.

Well, yes, Windows programmers understand this, but maybe not Python programmers.
And it is how I produced my "SHOULD" screenshot above. :-)

**Comment by chcg** [comment]
Start of fix, see https://github.com/chcg/PythonScript/commit/9c83beaaeaba5fd6f92e16d8a31882167f9fadac
