### ISSUE TITLE
Support for SendKeys module

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#183]
I've notice that in 1.5.4 there seems to be _partial_ support for the `SendKeys` module import:

```
>>> import SendKeys
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\...\plugins\PythonScript\lib\SendKeys.py", line 16, in <module>
    from _sendkeys import char2keycode, key_up, key_down, toggle_numlock
ImportError: No module named _sendkeys
```

So, `SendKeys` is found, but when that code tries to access `_sendkeys` there is a failure because that isn't found.

I'd like to use `SendKeys` without having to do "special things" to make it work.

Note about 3.0.5alpha:  `SendKeys` is not present at all -- can this be added (in full, of course)?

**Comment by chcg** [comment]
See https://pypi.org/project/SendKeys/#files and https://www.reddit.com/r/learnpython/comments/7lzocc/sendkeys_not_working_python_3/, it seems it is just available for python 2.7

The download contains in setup.py

```
    ext_modules=[
        Extension("_sendkeys", ["_sendkeys.c"],
            libraries=['user32','kernel32']),
    ],
```
, so indeed there seems to be some part missing in the current installation for python 2.7

**Comment by sasumner** [comment]
>@sasumner Did you use the x64 bit version of 1.5.4?

No; was using 32-bit.

**Comment by chcg** [comment]
@sasumner Just tried it with 32bit and it worked fine for me. Is _sendkeys.pyd available in your N++ plugins\PythonScript\lib dir?

```
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:19:08) [MSC v.1500 32 bit (Intel)]
Initialisation took 63ms
Ready.
>>> import SendKeys
```

Have you changed the configuration which python installation is preferred?

**Comment by sasumner** [comment]
> No; was using 32-bit.

I'm actually using _both_ 32 and 64-bit, so sometimes it gets confusing. :-)
Sorry for that.

Clarification:

* with 32-bit:  no errors with `import SendKeys`
* with 64-bit:  `import SendKeys` yields the `ImportError: No module named _sendkeys` error this issue was opened with.

> Is _sendkeys.pyd available in your N++ plugins\PythonScript\lib dir?

* with 32-bit:  YES
* with 64-bit:  NO

>Have you changed the configuration which python installation is preferred?

No; I have no independent Python 2.7 on my machine.

**Comment by chcg** [comment]
@sasumner That makes much more sense and is matching with my findings from the code :-)

**Comment by sasumner** [comment]
@chcg In the future, having SendKeys available with PS 3.x will be important to me, as part of a "full" install of PythonScript.  I see that the import fails under the current 3.0.5alpha (64 bit).  Will SendKeys be something that will be available in PS 3 (real release, non-alpha)?

**Comment by chcg** [comment]
@sasumner Added a python3 adapted version of SendKeys also to master for 3.0.x version.

**Comment by chcg** [comment]
Fixed with https://github.com/bruderstein/PythonScript/releases/tag/v2.0.0 and also in the python3 alpha versions.

@sasumner Feel free to add a new request for the messagebox.
