### ISSUE TITLE
Input focus jump after typing into console's >>> prompt and pressing Enter

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#184]
So if I type something (e.g. `a=4`) into the box to the right of `>>>` in the Pythonscript console, and press Enter, I get this:

![image](https://user-images.githubusercontent.com/30118311/104337652-b65f8000-54c3-11eb-8050-669639990b0c.png)

Where the thick black vertical bar is a caret where the input focus now is -- I had to draw the caret in after the screenshot because I couldn't capture it.

But the question is, why does the input focus leave the box to the right of the `>>>` ?
Is it useful to do this? (I can't see any use)
It makes it really inconvenient to enter several commands at the `>>>` prompt, because I have to keep moving the input focus back to there to enter the next command

Does it happen for everyone, or just me?
Am I missing something?

I noticed this right after a clean fresh install of 1.5.4 under N++ 7.9.2 64-bit.

**Comment by chcg** [comment]
I could reproduce the issue with 1.5.4 on

```
Notepad++ v7.9.2   (64-bit)
Build time : Dec 31 2020 - 04:01:34
Path : C:\Users\christian\Source\Repos\npp.7.9.2.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.746
Current ANSI codepage : 1252
Plugins : NppTaskList.dll NppXmlTreeviewPlugin.dll PythonScript.dll 

```

It is not happening with an older N++ 7.8.6.

**Comment by MaDill** [comment]
I can confirm this also with Notepad++ v8.3.1

```
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\_PortablePrograms\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1466
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll XMLTools.dll 

```

**Comment by alankilborn** [comment]
It's really annoying and it seems like it may not be too hard to fix?
It makes me wonder if this project is really under active development.

**Comment by vinsworldcom** [comment]
It seems that it should get the focus back:

https://github.com/bruderstein/PythonScript/blob/5c42c49182bcf4d96102f77c822c589c19dcab54/PythonScript/src/PythonConsole.cpp#L322

Which it seems is in the routine for gathering output and printing to the console and then should set focus to the input combo box.  Though I still see the behavior documented in this issue - cursor ends up with focus in the output window, not the input combo box.

Cheers.
