### ISSUE TITLE
'MENUCOMMAND.FORMAT_CONV2_AS_UTF_8_BOM' missing

### ISSUE THREAD

**Issue by brainexcerpts** [bruderstein/PythonScript#186]
Currently the enum:
`MENUCOMMAND.FORMAT_CONV2_AS_UTF_8`
converts to UTF8 **with** BOM, I need the same to convert **without** BOM but it does not exists.

It would be nice to have:
`MENUCOMMAND.FORMAT_CONV2_AS_UTF_8` -> converts to UTF8 **without** BOM
`MENUCOMMAND.FORMAT_CONV2_AS_UTF_8_BOM` -> converts to UTF8 **with** BOM

Side note:
----------
`notepad.runMenuCommand("Encoding", "Convert to UTF-8")` 
will convert to UTF8 **without** BOM

`notepad.runMenuCommand("Encoding", "Convert to UTF-8-BOM")`
will convert **with** BOM

Unfortunately it only works when Notepad++ language is set to English (this is not my case)

**Comment by chcg** [comment]
Naming is from:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/menuCmdID.h#L368-L372

, so FORMAT_CONV2_UTF_8 is probably the one you are missing. Also naming is a little bit inconsistent. That would require a change in N++ itself or maybe an alias here.

**Comment by brainexcerpts** [comment]
@chcg 
You pointed me to the right direction thank you! this one was hard to see, I just tested and actually it's:

- MENUCOMMAND.FORMAT_**AS**_UTF_8 -> to UTF8 **without** BOM
- MENUCOMMAND.FORMAT_**CONV2**_UTF_8 -> to UTF8 **with** BOM

Those names are so confusing ^^
