### ISSUE TITLE
mail announcing release of v3.0.6 - v3.0.6: my thoughts

### ISSUE THREAD

**Issue by vsrawat** [bruderstein/PythonScript#188]
You guys are still not telling that it is a "Pre-release" "alpha" version.

Gullible people like me might think it to be a Final release and download and install facing problem of compatibility between python 2 and python 3

That is what I had faced when I had installed similar release previously.

The forum and developers are taking no cognizance of problems reported by users, following their own pre-determined ways.

And what is this happening that version after version are all only "Pre-release" "alpha"? 
Nothing progresses further? 
No beta, no RC, no final release?
one "Pre-release" "alpha" after another "Pre-release" "alpha"?

This is not the development life-cycle of a product that I understand a software should have.

There wasn't even a proper "reply to" link in this mail that would send the reply to proper thread. 

Reply To email mentioned in it was noreply@github.com, that is obviously unmonitored or altogether non-existant.
mail sent to PythonScript@github.com and subscribed@github.com duly bounced.

Thanks.
-- 
Rawat

**Comment by chcg** [comment]
![grafik](https://user-images.githubusercontent.com/12630740/109395042-92001b80-792a-11eb-8684-7ffe23cb5543.png)

The mailing is some automatic feature of the github platform and nothing triggered manually.
The release is created by the appveyor CI build and need some manual correction to change it to prerelease.
I tried just tried to modified that and hope that will work for the next release and directly add the -alpha to the tag.

**Comment by sasumner** [comment]
>Gullible people like me might think it to be a Final release and download and install facing problem of compatibility between python 2 and python 3

Do your research before installing a new version.
Do careful testing on backup copies of your files before giving your own personal blessing to a new version.

If you choose to do anything else, then the next time you post something like this, make sure you change it to:

`Stupid people like me might think it to be a Final release and download and install facing problem of compatibility between python 2 and python 3`

**Comment by vsrawat** [comment]
Yes dear, you are the only intelligent person and all the rest of 
humanity is stupid.

inflate your ego at the cost of pride of others, and show that you have 
zero IQ when it comes to sense of humor or matters of figure of speech 
like oxymoron.

Suit yourself, and remain adamant that you will never listen to what 
others are expressing on this platform.

Thanks.

**Comment by sasumner** [comment]
@chcg 

>The mailing is some automatic feature of the github platform and nothing triggered manually.
The release is created by the appveyor CI build and need some manual correction to change it to prerelease.
I tried just tried to modified that and hope that will work for the next release and directly add the -alpha to the tag.

I don't think you need to jump through any special hoops.
It is obvious that this is still in "alpha state".
All one has to do is pay attention.
Spend your excellent efforts on more worthy things! :-)
