### ISSUE TITLE
Problem with Windows 64bit, Python 64bit preinstall

### ISSUE THREAD

**Issue by james4388** [bruderstein/PythonScript#19]
Dear Dave,
I have python 64bit preinstall in my C:\Python27 directory and ofcourse a 64bit version of python27.dll in system dir. When I select PythonScript/Console it first say Unknown error, then an empty console window and can not get anyresult. How can we fix this. I really dont want to remove my python because some dependencies. Please help

**Comment by chcg** [comment]
@james4388 Did this solve your issue? Can this be closed? There are already #33 and #27 to create a 64bit version of this plugin.

**Comment by chcg** [comment]
Seems to be no longer an issue. Please reopen if this is still not solved by the hint from dave above.
