### ISSUE TITLE
Abort save file from FILEBEFORESAVE callback

### ISSUE THREAD

**Issue by asrafindanang** [bruderstein/PythonScript#192]
in my case, I have created a FILEBEFORESAVE callback to run php.exe to parse currently opened php file
if there is no error then the file will be saved
but if there are any error, an alert will appear showing the parse error message and I want the save action is aborted but I dont know how to abort save the save action
is there any way to abort the save action?

**Comment by Ekopalypse** [comment]
No, PythonScript has no way to interrupt Notepad++'s save action.
One idea could be to reassign ctrl+s (I assume you use this and not the mouse to save files) and check if the current document is a php file, if so run your linter and then call save or in case of error  you skip it.

**Comment by asrafindanang** [comment]
thank you for your answer
maybe i can try ur idea later
