### ISSUE TITLE
Support dockable feature

### ISSUE THREAD

**Issue by Jzhenli** [bruderstein/PythonScript#193]
Hi, does PythonScript support to create new dockable?  Seems there's no API, would u add it for the next version? thanks.

![image](https://user-images.githubusercontent.com/42105688/113151593-d5221700-9267-11eb-886a-07db609ff22b.png)

**Comment by chcg** [comment]
@Jzhenli What is your expectation should be shown in the dockable windows?

**Comment by Jzhenli** [comment]
@chcg want to add file structure index in the dockable, or something like function list.

**Comment by chcg** [comment]
@Jzhenli I think this is not possible in an usable way. It would require pythonscript plugin to implement a own instance of the DockingDlgInterface (https://github.com/bruderstein/PythonScript/blob/master/NppPlugin/include/DockingDlgInterface.h) which could be used from python code and that somehow in a generic way, if I got you right. If you want to deal with windows, you might use tcl/tk from Tkinter see e.g. https://github.com/bruderstein/PythonScript/blob/master/scripts/Samples/Sorter.py

See e.g. https://github.com/bruderstein/PythonScript/blob/master/PythonScript/src/ConsoleDialog.cpp which is a specific impl of that interface.
The function list itself is implemented in N++, see https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/FunctionList/functionListPanel.h.

**Comment by Jzhenli** [comment]
@chcg  I find JN-NPP-Scripts plugin can do it, if some one want this feature, can have a try.
