### ISSUE TITLE
Add some .ico or .bmp files in the installation package.

### ISSUE THREAD

**Issue by vsrawat** [bruderstein/PythonScript#195]
I tried to add my script's icon on toolbar, but it goes to Documents folder where there are no .ico .bmp files, and I am not aware where to find those files. So I couldn't add that.

Please consider adding some .ico or .bmp files in the installation package, and clicking on "set icon" in configuration window should go to that specific folder where those ico bmp files are stored in ps installation.

Thanks.

**Comment by chcg** [comment]
That sounds strange. If you have no own icons, why should you then want to set one?
You could find some examples here:
https://github.com/bruderstein/PythonScript/tree/master/PythonScript/res
They are compiled as resources into the dll. So it doesn't make sense to distributed them additionally.

**Comment by vsrawat** [comment]
Why should I have my own icons? I never created any. I am not a 
developer or designer or photoshop-er.

I use npp, I installed pythonscript, I wrote my script, I was running 
that accessing from menu, that required some clicks, so I wanted to add 
that an icon in the toolbar that can be run with a single click.

So, when the software is providing option to add an icon for each script 
on the toolbar, there should be some easy method to have ready made 
icons provided bundled with the software.

The link you give has no relevant icon that can be added to a script, 
though folder open/ close can be used as placemarker and only I will 
know that clicking this icon will not open/ close any folder and would 
rather run my script.

Anyway, if someone can tell me where w8.1 stores its set of icons, I 
will select one from that, or shall google about that.

This is a suggestion as a layman user, and I feel many must be feeling 
such a requirement, so you can add or decide not to add some icon files 
in the 11 MB package to save some bytes.

Thanks.
-- 
Rawat

**Comment by chcg** [comment]
So you didn't get what the usage section of the docu mean:

> To edit the script, just hold Ctrl down and click the script in the Scripts menu.
> 
> If you click Configuration, you can assign the script either to a toolbar icon, or to the Python Script menu itself. If you assign a script to the menu, then it will appear immediately, but you will not be able to assign a shortcut to it until next time Notepad++ starts.
> 
> If you assign it to a toolbar icon, then it will only appear on the next start of Notepad++.

There will be a default icon in the toolbar, if you don't add your custom one for your script. The icons just appear for the toolbar with standard icons set.

![grafik](https://user-images.githubusercontent.com/12630740/113446542-40025800-93f8-11eb-99da-a7d310e68442.png)

**Comment by Ekopalypse** [comment]
Since this is marked as invalid, can it be closed?
Providing additional icons doesn't make sense to me, since one usually chooses a particular icon to remind what a particular script does, and given that it's so easy to create your own icons these days, I think it's appropriate to leave that task to the user.

**Comment by chcg** [comment]
@Ekopalypse I think there was one issue remaining here. Currently it seems just .bmp icons are working fine but not .ico. I wanted to take a closer look at that also it is not directly the issue.

**Comment by Ekopalypse** [comment]
@chcg 

I'm working on getting .ico files to work as well,

![{40B394FA-F657-4C06-8046-A776E705A5AD}](https://github.com/user-attachments/assets/c2afde8a-1ab8-423c-9f32-89af687c9814)

but PythonScript doesn't really have a “utility” code module and the required code needs to be added to ShortcutDlg and ConfigFile which don't share other code modules. Is it ok if it is duplicated in this case? Or should I create a utility.h/cpp and include it into both?

**Comment by chcg** [comment]
@Ekopalypse Both options are fine for me. In case of code duplication a comment on it would be good.

**Comment by alankilborn** [comment]
My 2c:  Avoid duplication.  :-)
