### ISSUE TITLE
The FILEOPENED callback acts on the last active file instead of the one that is opened

### ISSUE THREAD

**Issue by kiyn** [bruderstein/PythonScript#196]
Consider the following script in execution:

```
from Npp import *

def opening_document(args):
   editor.addText("now")
notepad.callback(opening_document, [NOTIFICATION.FILEOPENED])
```

While there is a file "1" active in Notepad++, if i open a file "2", "now" will be printed in file "1".

How can i add text to the opened file instead of the last active one?
Thanks. 

Same behavior with FILEBEFORELOAD and FILEBEFOREOPEN.
Happens with PythonScript v1.5.4 as well as with v3.0.8.

**Comment by sasumner** [comment]
>How can i add text to the opened file instead of the last active one?

The information about the file opened is passed in via the `args` argument.
So, you could obtain your desired result in the code you show by changing it to:

```z
def opening_document(args):
   notepad.activateBufferID(args['bufferID'])  # <------important addition
   editor.addText("now")
notepad.callback(opening_document, [NOTIFICATION.FILEOPENED])
```

**Comment by chcg** [comment]
See also https://github.com/bruderstein/PythonScript/blob/master/scripts/Samples/Event%20Handler%20Demo.py

**Comment by kiyn** [comment]
> 
> 
> > How can i add text to the opened file instead of the last active one?
> 
> The information about the file opened is passed in via the `args` argument.
> So, you could obtain your desired result in the code you show by changing it to:
> 
> ```
> def opening_document(args):
>    notepad.activateBufferID(args['bufferID'])  # <------important addition
>    editor.addText("now")
> notepad.callback(opening_document, [NOTIFICATION.FILEOPENED])
> ```

Thanks for the quick reply.
After your indication I also found references in the documentation (links to online 1.0.8.0 old version):

[http://npppythonscript.sourceforge.net/docs/latest/intro.html?highlight=activatebufferid](url)
[http://npppythonscript.sourceforge.net/docs/latest/notepad.html?highlight=activatebufferid](url)



I went ahead with my scripts, but now I have another problem. 
I need to invoke the functions with callbacks to use them elsewhere.
I have reread and tried many times, but it's still not clear to me what kind of object I have to insert as a parameter and how to indicate it. 

In the documentation I found: 

_"The args parameter to the function is a map (similar a dictionary in C# or a hashmap in Java), that contains the arguments for the event - many events are signalled for a BufferID, which is the Notepad++ internal number for a particular file or tab. We can do things with the bufferID like get the filename, switch to it to make it active and so on."_

I can invoke the function and it works if I put `None` as a parameter, but if it's present, as you suggested and as needed 

`notepad.activateBufferID(args['bufferID'])`


when I invoke the function with `None` as parameter it gives me this error: 

``` 
   notepad.activateBufferID(args['bufferID'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

if as parameter I use

`notepad.getCurrentBufferID()`

return error:

`TypeError: 'long' object has no attribute '__getitem__'`

I made many attempts with no results, even creating an object with the `__getitem__` attribute.

I apologize if these are trivial questions, but this is my first script.
Is it possible to use a function with callback elsewhere?
With what attribute? 
thanks

**Comment by sasumner** [comment]
@kiyn 

I'd like to help, but I have no idea what you're asking.  :-(

**Comment by kiyn** [comment]
Perhaps an example can help me to be clearer.

I have a 1.py file with this function: 

```
from Npp import *

def opening_document(args):
   notepad.activateBufferID(args['bufferID'])
   editor.addText("now")
notepad.callback(opening_document, [NOTIFICATION.FILEOPENED])
```

I would like to use that function from the 2.py file:

```
from Npp import *
import 2

opening_document(args)
```

What should I enter as args ?

**Comment by sasumner** [comment]
```
args = { 'bufferID' : some_buffer_id }
opening_document(args)
```

`some_buffer_id` would need to be a valid buffer ID.

**Comment by kiyn** [comment]
Great!
Thanks again

**Comment by sasumner** [comment]
@chcg I would suggest closing.

@kiyn In the future, a good place to ask questions like this is https://community.notepad-plus-plus.org/

There are some good experts in PythonScript there.

**Comment by kiyn** [comment]
@sasumner
Thank you, and I apologize if my request was in the wrong context.

Il giorno sab 24 apr 2021 alle ore 13:34 sasumner ***@***.***>
ha scritto:

**Comment by sasumner** [comment]
>Thank you, and I apologize if my request was in the wrong context.

It's fine.  
I was just giving you a suggestion for wider exposure to questions of similar nature you might ask in the future.
