### ISSUE TITLE
how to install 3rd lib

### ISSUE THREAD

**Issue by Jzhenli** [bruderstein/PythonScript#197]
Hi, just want to know how to install 3rd python lib for this plugin?

**Comment by chcg** [comment]
@Jzhenli What do you mean with 3rd python lib? Python version 3, e.g. https://www.python.org/downloads/release/python-394/?

**Comment by Jzhenli** [comment]
if I want to install pandas or numpy lib, how to do it?

**Comment by Ekopalypse** [comment]
@Jzhenli
You don't. If you want to use such libraries, you must have a local Python installation and copy the pythonX.dll into the pythonscript plugin directory to replace the one that comes with the plugin itself.

**Comment by chcg** [comment]
In config dialog you have to check that your local installation is preferred, see
![grafik](https://user-images.githubusercontent.com/12630740/117372719-43db3b80-aeca-11eb-964b-77e32f7da326.png)

**Comment by hcommin** [comment]
How does PythonScript determine where my locally installed Python packages are located?

I have two versions of Python installed (3.9 and 3.10). PythonScript is running Python 3.10, but then trying to load packages from my 3.9 installation (and failing). I've set my PATH to point to 3.10, but PythonScript still insists on loading the 3.9 packages.

**Comment by Ekopalypse** [comment]
This is done [internally by python](https://github.com/bruderstein/PythonScript/blob/6ba0f5f203ec0d557e5f7d10408c8ce5ea0049ea/PythonScript/src/PythonHandler.cpp#L99) itself.
Yes, if you are using multiple versions, this may be the only way to ensure that the correct path is used. Remember that PythonScript behaves like a Python REPL, it stores this information as long as Npp is running.

**Comment by Ekopalypse** [comment]
@Jzhenli - Is there anything still open, or can this topic be closed?
