### ISSUE TITLE
Some troubles with installing plugins to userdata folder (AppData/Roaming/Notepad++/)

### ISSUE THREAD

**Issue by 1ike** [bruderstein/PythonScript#21]
## Hi!

I had a problem when tried to install plugin([PythonScript 1.0.8.0 Full](http://sourceforge.net/projects/npppythonscript/files/Python%20Script%201.0.8.0/PythonScript_Full_1.0.8.0.zip/download)) to userdata folder. The plugin manager show notification error "unknown exeption" at attempt to call "Show Console". 
If remove plugin to "Program Files (x86)/ Notepad++/" it working fine. 
But another problem appears with Emmet plugin(it in the userdata folder). [To fix it help the next line](https://github.com/emmetio/emmet/issues/185#issuecomment-15992932) at the end of startup.py (Program Files (x86)/ Notepad++/plugins/PythonScript/scripts/):  `sys.path.insert(0, r'C:\Users\Andy\AppData\Roaming\Notepad++\plugins\EmmetNPP')`.
### Resume

If people keep their plugins in "AppData/Roaming/Notepad++/" and use Emmet they must:
- remove PythonScript plugin to "Program Files (x86)/ Notepad++/" ;
- insert line `sys.path.insert(0, r'C:\Users\Andy\AppData\Roaming\Notepad++\plugins\EmmetNPP')` at the end of startup.py (Program Files (x86)/ Notepad++/plugins/PythonScript/scripts/) .

**Comment by bruderstein** [comment]
This will be solved when 1.0.8 is in plugin manager (due for the next XML release)

**Comment by Ekopalypse** [comment]
Can be closed as well I guess.
