### ISSUE TITLE
Why is there NO installation documentation for Python 3.x version of this product ?  Is this FOSS product actively maintained? 

### ISSUE THREAD

**Issue by richlysakowski** [bruderstein/PythonScript#214]
I tried installing this from Notepad++ Plugin Manager and it still installs Python 2.7 !!   

Then I googled around to find a solution for using Python 3 from Notepad++ using my c:\programdata\Anaconda3\Python.exe interpreter, but not for this product.   

I still wanted to see whether this product is actively maintained, and EVENTUALLY found this github.com repo mentioned on StackOverflow.  Then I came to github.com.  However there are NO installation instructions for this product on its github home page, even though it appears to be actively maintained and developed. 

Can someone please provide updated instructions for installing the Python 3.x version?  A user's guide would be great too (like how to use the code samples?) because it appears to have a lot more Python-specific functionality than just NPP Run... menu interpreter command. 

Thank you.

**Comment by chcg** [comment]
There is a release for python3, see https://github.com/bruderstein/PythonScript/releases/tag/v3.0.9.
But there is at least one obstacle to overcome for a official release
-    support for files with encodings that are not unicode

For the installation without the help of PluginAdmin you could use the msi package.
See https://github.com/bruderstein/PythonScript/blob/master/docs/source/usage.rst

**Comment by Ekopalypse** [comment]
@richlysakowski - Is there anything still open, or can this topic be closed?
