### ISSUE TITLE
Notepad++ 8.3 builds change Sci_position leading to crash

### ISSUE THREAD

**Issue by vinsworldcom** [bruderstein/PythonScript#218]
See here for more detail:

+ https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header
+ https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11104#issuecomment-1025206468

Basically, just take from the Notepad++ repo and replace in your repo:

+ notepad-plus-plus/scintilla/include/Scintilla.h
+ notepad-plus-plus/scintilla/include/Sci_Position.h

then recompile.

I'm currently using Python 3.0.7-alpha - Need the Python 3.8 support.  I suppose the PythonScript 1.5.4 release will have this issue as well.

Cheers.

**Comment by Yaron10** [comment]
@vinsworldcom,

Reading your [comment in Compare](https://github.com/pnedev/compare-plugin/issues/275#issuecomment-1030058265), I'd like to try using NPP 64-bit.
Have you built PythonScript with the new Scintilla.h and Sci_Position.h? Are those the only changes required?

Thank you.

@chcg,

Are you planing on updating to v1.5.5?

Thank you for your work.

**Comment by vinsworldcom** [comment]
I did build PythonScript 3.0.7-alpha with the new headers and it seemed to fix the `getRangeText()` issue. Not sure if there any other >2G problems but I'm not using files that big so I really don't care.

https://community.notepad-plus-plus.org/topic/22473/pythonscript-and-system-python/10

I should note I don't really know what I'm doing other Rebuild Solution in visual studio and googling any errors that come up.

Cheers.

**Comment by Yaron10** [comment]
@vinsworldcom,

Thank you for the detailed reply.

I'd rather use Python 2.7 for the time being.
On switching to NPP 64-bit - should I replace anything else other than python27.dll?

BR

**Comment by alankilborn** [comment]
>On switching to NPP 64-bit - should I replace anything else other than python27.dll?

Gasp.  Yes.  You should do a proper install of PS 64-bit, or at least a fresh extract of all of its files from the zips.

**Comment by Yaron10** [comment]
@alankilborn,

I meant "On switching to NPP 64-bit - should I replace anything else other than python27.dll and PythonScript.dll?".

Anyway, thank you.

**Comment by alankilborn** [comment]
@Yaron10 

Yes, I knew fully what you meant.
There are other files that are different besides the ones you mention, between 32 and 64 bit.
That's why I said you should do a proper install or extract.

**Comment by Yaron10** [comment]
@alankilborn,

Thanks again. I appreciate the info.

**Comment by chcg** [comment]
First I'm changing the current master version to support 8.3 and check what needs to be changed and then investigate how it could be backported to the python 27 legacy branch.

**Comment by Yaron10** [comment]
@chcg,

Thank you for your ongoing work. Much appreciated.

**Comment by chcg** [comment]
Fixed with https://github.com/bruderstein/PythonScript/releases/tag/v2.0.0 and 
https://github.com/bruderstein/PythonScript/releases/tag/v3.0.11

**Comment by Yaron10** [comment]
@chcg,

👍 
Thank you for your great work. I do appreciate it.
