### ISSUE TITLE
[HELP] Migrating scripts from 32-bit to 64-bit

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#222]
The following two scripts work properly in NPP 32-bit + PythonScript 1.5.4 32-bit.
In NPP 64-bit (_8.2 as well_) + PythonScript 1.5.4 64-bit they do not work as expected.

I'd appreciate your help.

***
The code in _startup.py_ (+ the _Customize Toolbar_ plugin and another small Python script) enables me to assign 3 different commands to a single toolbar button.
For example: _New_ button.
Left-click: Open a new default document.
Middle-click: Open a new XML document.
Right-click: Open a new C++ document.

_Without the _Customize Toolbar_ plugin and the other small Python script, Middle-click and Right-click should execute the default command._

**startup.py**
```
# The lines up to and including sys.stderr should always come first
# Then any errors that occur later get reported to the console
# If you'd prefer to report errors to a file, you can do that instead here.
import sys
from Npp import *

# Set the stderr to the normal console as early as possible, in case of early errors
sys.stderr = console

# Define a class for writing to the console in red
class ConsoleError:
	def __init__(self):
		global console
		self._console = console;

	def write(self, text):
		self._console.writeError(text);

# Set the stderr to write errors in red
sys.stderr = ConsoleError()

# This imports the "normal" functions, including "help"
import site

# This sets the stdout to be the currently active document, so print "hello world",
# will insert "hello world" at the current cursor position of the current document
# sys.stdout = editor

sys.stdout = console		# Change "sys.stdout = editor" to "sys.stdout = console".

##################### Set console.editor styles. #####################

console.editor.setZoom(2)		# Set font size to 10 (default 8 + 2).
console.editor.styleSetFore(2, (0 , 0 ,255))		# Set foreground color of links to files to blue.
console.editor.setSelBack(True, (108 , 255 ,108))

##################### Right/Middle-Click Mode. #####################

from ctypes import windll, wintypes, WINFUNCTYPE

WNDENUMPROC = WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)
WNDPROCTYPE = WINFUNCTYPE(wintypes.LONG, wintypes.HWND, wintypes.UINT, wintypes.WPARAM, wintypes.LPARAM)

GWL_WNDPROC = -4

WM_LBUTTONDOWN = 0x0201
WM_LBUTTONUP = 0x0202
WM_RBUTTONDOWN = 0x0204
WM_RBUTTONUP = 0x0205
WM_MBUTTONDOWN = 0x0207
WM_MBUTTONUP = 0x0208
MK_RBUTTON = 0x0002
MOUSEEVENTF_LEFTDOWN = 0x0002
MOUSEEVENTF_LEFTUP = 0x0004

clickButton = 0

class NPPchildWindows():

	def enumNPPCallback(self, hWnd, lParam):
		currentClass = (wintypes.WCHAR * 256)()
		windll.user32.GetClassNameW(hWnd, currentClass, 256)

		if currentClass.value == "ToolbarWindow32":
			self._hToolbar = hWnd
			return False

		return True

	def __init__(self):
		self._hToolbar = None

		hParent = windll.user32.FindWindowA("Notepad++", None)
		windll.user32.EnumChildWindows(hParent, WNDENUMPROC(self.enumNPPCallback), 0)

	def registerRightMiddleClick(self):
		if self._hToolbar:
			self._customToolbarProc = WNDPROCTYPE(self.customToolbarProc)
			self._originalToolbarProc = windll.user32.SetWindowLongA(self._hToolbar, GWL_WNDPROC, self._customToolbarProc)
			console.write("Toolbar right/middle-click mode registered.\n\n")

	# On right-clicking a **button**, MOUSEEVENTF_LEFTDOWN triggers a WM_RBUTTONUP although the right button is still down.
	# On right-clicking an empty area in the toolbar, MOUSEEVENTF_LEFTDOWN does NOT trigger a WM_RBUTTONUP.
	# (MOUSEEVENTF_LEFTUP *must* always be sent after MOUSEEVENTF_LEFTDOWN).
	# On middle-clicking anywhere, MOUSEEVENTF_LEFTDOWN does NOT trigger a WM_RBUTTONUP.
	# Quite tricky!
	def customToolbarProc(self, hWnd, msg, wParam, lParam):
		global clickButton
		if msg == WM_RBUTTONDOWN or msg == WM_MBUTTONDOWN:
			windll.user32.mouse_event(MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0)	# Tricky MOUSEEVENTF_LEFTDOWN.
		elif msg == WM_RBUTTONUP or msg == WM_MBUTTONUP:
			clickButton = 2 if msg == WM_RBUTTONUP else 1
			windll.user32.mouse_event(MOUSEEVENTF_LEFTUP, 0, 0, 0, 0)	# Executed twice on right-clicking a **button**.
		elif clickButton != 0 and msg == WM_LBUTTONDOWN:
			clickButton = 0
		elif msg == WM_LBUTTONUP and wParam == MK_RBUTTON:
			return 0	# On right-clicking a **button**, do not process the first WM_LBUTTONUP but the second one sent when the right button is released.

		return windll.user32.CallWindowProcA (self._originalToolbarProc, hWnd, msg, wParam, lParam)

childWindowsNPP = NPPchildWindows()
childWindowsNPP.registerRightMiddleClick()
```
**In 64-bit, _customToolbarProc()_ is not called.**
***

**Replace Current Line.py**
```
import ctypes

def getClipboardText():
	if ctypes.windll.user32.OpenClipboard(None):
		hClipboard = ctypes.windll.user32.GetClipboardData(1)		# 1 == Get text.
		if hClipboard:
			pointerToContent = ctypes.windll.kernel32.GlobalLock(hClipboard)
			clipboardData = ctypes.c_char_p(pointerToContent).value
			ctypes.windll.kernel32.GlobalUnlock(hClipboard)
		else:
			clipboardData = -1		# clipboardData is not text.

		ctypes.windll.user32.CloseClipboard()
	else:
		clipboardData = -1		# Error.

	return  clipboardData

def replaceCurrentLine(clipboardText):
	editor.home()
	editor.lineEndExtend()

	clipboardTextHasEOL = clipboardText.endswith(('\n', '\r'))		# Ends with '\n' or '\r'.
	if clipboardTextHasEOL:
		editor.charRightExtend()		# Select EOL.

	editor.paste()	# editor.paste() converts the EOL to the current format if needed.

	if clipboardTextHasEOL:
		editor.lineUp()
		editor.lineEnd()		# Always position the carret at the end of the pasted string.

# NOTE: if a string with an EOL is pasted in the file's last line, a new line is created.
# It can be considered the expected behavior; it's certainly not worth the extra work (removing the EOL and using editor.replaceSel()).

def mainReplaceCurrentLine():
	clipboardText = getClipboardText()
	if clipboardText != -1:
		replaceCurrentLine(clipboardText)
	else:
		import winsound
		winsound.MessageBeep()

#-------------------------------------------------------------------------------#

mainReplaceCurrentLine()
```
**In 64-bit, `clipboardTextHasEOL = clipboardText.endswith(('\n', '\r'))` generates an error.**

**Comment by alankilborn** [comment]
@Yaron10 

I would try this code for your clipboard problem:

    from Npp import *

    try:
        editor3h  # third editor, hidden
    except NameError:
        editor3h = notepad.createScintilla()

    def getClipboardText():
        editor3h.clearAll()
        editor3h.paste()
        return editor3h.getText()

**Comment by alankilborn** [comment]
@Yaron10 

BTW, I recently switched from 32-bit to 64-bit N++ (and thus PS).
I was afraid to make the change because I didn't know what was going to break.
So...
I set up TWO folder structures with one holding the DLLs (and any other bitness-dependent files) for 32-bit and one holding the 64-bit.
Then I created two batch files to copy over the real plugins folder structure the files I wanted at any given time.
This gave me the ability to solve problems slowly, and still be able to use N++ while my porting was incomplete.

**Comment by Yaron10** [comment]
@alankilborn,

> Arguably a better place for discussion is the N++ Community?

You're probably right. But the N++ Community interface and the 3-minutes-edit is not so convenient.

Thank you very much for the detailed and very helpful reply. I do appreciate it. 👍 

I've figured out _startup.py_.
Here is the relevant code for 64-bit:
```
from ctypes import windll, wintypes, WINFUNCTYPE

WndEnumProc = WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)
WndProcType = WINFUNCTYPE(wintypes.LPARAM, wintypes.HWND, wintypes.UINT, wintypes.WPARAM, wintypes.LPARAM)

CallWindowProc = windll.user32.CallWindowProcW
CallWindowProc.restype = wintypes.LPARAM
CallWindowProc.argtypes = [WndProcType, wintypes.HWND, wintypes.UINT, wintypes.WPARAM, wintypes.LPARAM]

SetWindowLong = windll.user32.SetWindowLongPtrW
SetWindowLong.restype = WndProcType
SetWindowLong.argtypes = [wintypes.HWND, wintypes.INT, WndProcType]

GWL_WNDPROC = -4

WM_LBUTTONDOWN = 0x0201
WM_LBUTTONUP = 0x0202
WM_RBUTTONDOWN = 0x0204
WM_RBUTTONUP = 0x0205
WM_MBUTTONDOWN = 0x0207
WM_MBUTTONUP = 0x0208
MK_RBUTTON = 0x0002
MOUSEEVENTF_LEFTDOWN = 0x0002
MOUSEEVENTF_LEFTUP = 0x0004

clickButton = 0

class NPPchildWindows():

	def enumNPPCallback(self, hWnd, lParam):
		currentClass = (wintypes.WCHAR * 256)()
		windll.user32.GetClassNameW(hWnd, currentClass, 256)

		if currentClass.value == "ToolbarWindow32":
			self._hToolbar = hWnd
			return False

		return True

	def __init__(self):
		self._hToolbar = None

		hParent = windll.user32.FindWindowA("Notepad++", None)
		windll.user32.EnumChildWindows(hParent, WndEnumProc(self.enumNPPCallback), 0)

	def registerRightMiddleClick(self):
		if self._hToolbar:
			self._customToolbarProc = WndProcType(self.customToolbarProc)
			self._originalToolbarProc = SetWindowLong(self._hToolbar, GWL_WNDPROC, self._customToolbarProc)
			console.write("Toolbar right/middle-click mode registered.\n\n")

	# On right-clicking a **button**, MOUSEEVENTF_LEFTDOWN triggers a WM_RBUTTONUP although the right button is still down.
	# On right-clicking an empty area in the toolbar, MOUSEEVENTF_LEFTDOWN does NOT trigger a WM_RBUTTONUP.
	# (MOUSEEVENTF_LEFTUP *must* always be sent after MOUSEEVENTF_LEFTDOWN).
	# On middle-clicking anywhere, MOUSEEVENTF_LEFTDOWN does NOT trigger a WM_RBUTTONUP.
	# Quite tricky!
	def customToolbarProc(self, hWnd, msg, wParam, lParam):
		global clickButton
		if msg == WM_RBUTTONDOWN or msg == WM_MBUTTONDOWN:
			windll.user32.mouse_event(MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0)	# Tricky MOUSEEVENTF_LEFTDOWN.
		elif msg == WM_RBUTTONUP or msg == WM_MBUTTONUP:
			clickButton = 2 if msg == WM_RBUTTONUP else 1
			windll.user32.mouse_event(MOUSEEVENTF_LEFTUP, 0, 0, 0, 0)	# Executed twice on right-clicking a **button**.
		elif clickButton != 0 and msg == WM_LBUTTONDOWN:
			clickButton = 0
		elif msg == WM_LBUTTONUP and wParam == MK_RBUTTON:
			return 0	# On right-clicking a **button**, do not process the first WM_LBUTTONUP but the second one sent when the right button is released.

		return CallWindowProc(self._originalToolbarProc, hWnd, msg, wParam, lParam)

childWindowsNPP = NPPchildWindows()
childWindowsNPP.registerRightMiddleClick()
```
BTW - if there's a docked panel open on NPP startup, it doesn't work.
But that's the case in 32-bit too, and I got used to it. :)

***

> I would try this code for your clipboard problem...

It seems nice and interesting. I haven't tried it yet.
Shouldn't I free/delete `editor3h` after `notepad.createScintilla()`?

Any idea why `clipboardTextHasEOL = clipboardText.endswith(('\n', '\r'))` generates an error?

***
> Then I created two batch files...

I'm also using batch files for restoring clean config.xml and other files.
(Actually using NirCmd scripts).

***
@Ekopalypse,

Thank you for the "Eko code". Great. 👍

**Comment by alankilborn** [comment]
@Yaron10 

>N++ Community interface and the 3-minutes-edit are not so convenient

Point taken.  I guess my thinking was that potentially others that could benefit would see the discussion more likely there than here.

>Shouldn't I free/delete editor3h after notepad.createScintilla()?

I keep it around because I use the same technique in other scripts that I may run during a session.  They just reuse that existing editor3h that I leave hanging around.

>Any idea why clipboardTextHasEOL = clipboardText.endswith(('\n', '\r')) generates an error?

No, and I wouldn't think too much about it.  Just try IMO my simpler technique. :-)

**Comment by Yaron10** [comment]
@alankilborn,

> No, and I wouldn't think too much about it. Just try IMO my simpler technique. :-)

But I'd still want to know if it `endswith(('\n', '\r'))`.
I also want to know if it's text or not.

I'll think about it. 
Thanks again.

**Comment by alankilborn** [comment]
@Yaron10 

>I'd still want to know if it endswith(('\n', '\r'))

    t = getClipboardText()
    if t.endswith('\r\n'): print 'ends with CR+LF')
    elif t.endswith('\n'): print 'ends with LF')
    elif t.endswith('\r'): print 'ends with CR')


>I also want to know if it's text or not.

If it isn't text, you will get a zero-length string back from the `getClipboardText()` call

**Comment by Yaron10** [comment]
@alankilborn,

Great! 👍 

> I keep it around because I use the same technique in other scripts that I may run during a session. They just reuse that existing editor3h that I leave hanging around.

And if I don't want to leave hanging around?

**Comment by alankilborn** [comment]
@Yaron10 

>And if I don't want to leave it hanging around?

    notepad.destroyScintilla(editor3h)

**Comment by Yaron10** [comment]
@alankilborn,

👍 

Thanks again. I do appreciate it.

**Comment by alankilborn** [comment]
@Yaron10 

Glad I could help.

**Comment by alankilborn** [comment]
BTW, another technique you could use to determine if you have text data is the `.canPaste()` function.  As in `editor3h.canPaste()`.  It will return `False` if the clipboard contains non-text data, otherwise `True`.

**Comment by Yaron10** [comment]
@alankilborn,

I had a phone call and hence the late response.

> BTW, another technique you could use...

That's nice. But your original suggestion is better in this case. It works like a charm. 👍 

Thank you.

**Comment by alankilborn** [comment]
BTW the origins of your clipboard routines...might have roots here?:  https://community.notepad-plus-plus.org/post/18486

**Comment by Yaron10** [comment]
@alankilborn,

Indeed. Some scripts I haven't changed for years.

Scott and Claudia. :)

**Comment by alankilborn** [comment]
>Scott and Claudia

Yes, we all learned a lot from them.
