### ISSUE TITLE
findText do not find text

### ISSUE THREAD

**Issue by MaDill** [bruderstein/PythonScript#223]
I can not get editor.findText working.

Configuration:
```
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\_PortablePrograms\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1466
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll XMLTools.dll 

PythonScript Version 1.5.4.0 64bit

```

Testfile:
```
test1
test2as
test 3
test4
teSt5
tast6
tes17
test8
tes9
test10

```

Console commands:
```
>>> matches = []
>>> editor.research(r'test\d$', lambda m: matches.append(m.span(0)), 0, 0, editor.getLength())
>>> print(matches)
[(0, 5), (24, 29), (52, 57)]
>>> findResult = editor.findText(FINDOPTION.REGEXP, 0, editor.getLength(), r'test\d$')
>>> print(findResult)
None

```

How to use editor.findText?

**Comment by alankilborn** [comment]
I put it in a script file and ran it that way, and it seems to work for me (N++ 8.2.1, PS 1.5.4.0, 64bit):

    '''
    test1
    test2as
    test 3
    test4
    teSt5
    tast6
    tes17
    test8
    tes9
    test10
    '''
    matches = []
    editor.research(r'test\d$', lambda m: matches.append(m.span(0)), 0, 0, editor.getLength())
    print(matches)
    findResult = editor.findText(FINDOPTION.REGEXP, 0, editor.getLength(), r'test\d$')
    print(findResult)

![image](https://user-images.githubusercontent.com/77065706/154487313-3a725940-7c12-4eef-b9de-7c671ba6cb99.png)

**Comment by chcg** [comment]
Fixed with https://github.com/bruderstein/PythonScript/releases/tag/v2.0.0 and 
https://github.com/bruderstein/PythonScript/releases/tag/v3.0.11
