### ISSUE TITLE
editor.getTextRange crash notepad++

### ISSUE THREAD

**Issue by MaDill** [bruderstein/PythonScript#224]
When I use getTextRange, notepad++ just crash and is closed without a message or error.

Configuration:

```
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\_PortablePrograms\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1466
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll XMLTools.dll 

PythonScript Version 1.5.4.0 64bit

```
Testfile:

```
test1
test2as
test 3
test4
teSt5
tast6
tes17
test8
tes9
test10

```

Now I mark the word "test2as".

Console commands:

```
>>> editor.getSelText()
'test2as'
>>> editor.getSelectionStart()
7
>>> editor.getSelectionEnd()
14

```

When I now execute getTextRange in the console the console turns solid grey and after a few seconds notepad++ close itself.

`>>> editor.getTextRange(7, 14)`

**Comment by alankilborn** [comment]
Notepad++ 8.3 and above added huge file support and because of that plugins that use SCI_GETTEXTRANGE need to be rebuilt and a new version of the plugin released.

**Comment by chcg** [comment]
Fixed with https://github.com/bruderstein/PythonScript/releases/tag/v2.0.0 and 
https://github.com/bruderstein/PythonScript/releases/tag/v3.0.11
