### ISSUE TITLE
User script save location

### ISSUE THREAD

**Issue by Tamarindo94** [bruderstein/PythonScript#227]
I cannot find where user scripts are saved on disk. By "user script" I mean scripts created through Plugins > Python Script > New script

**Comment by alankilborn** [comment]
It is going to be the `...\plugins\Config\PythonScript\scripts\` folder.

But really, can't you just create a script and then see the location when Notepad++ opens it?  (The path to the script will be shown in the Notepad++ title bar).

This really isn't an "issue".  This is a "question".  Questions are better asked [HERE](https://community.notepad-plus-plus.org/) in the future.

**Comment by Tamarindo94** [comment]
Thank you for the reply, I found the user scripts in the location you suggested under AppData\Roaming.
I had already closed the script so I couldn't see the location from inside npp. Now I know where to find them
