### ISSUE TITLE
Missing *.pyd in v3.0.x

### ISSUE THREAD

**Issue by fjumelle** [bruderstein/PythonScript#229]
When executing 'from urllib import request' in the console of the version 3.0.12, I get an error 'ModuleNotFoundError: No module named '_socket''.
After adding all *.pyd from an installed Python 3.10.2 (from DLLs folder) to C:\Program Files\Notepad++\plugins\PythonScript\, it is working fine.

**Comment by chcg** [comment]
@fjumelle How did you install pythonscript? Which version of N++ do you use?

**Comment by alankilborn** [comment]
Another user's trial:

`from urllib import request` works just fine for me at the console `>>>` prompt in v3.0.12 (N++ 8.3.2).

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]

**Comment by fjumelle** [comment]
Thank you for your replay.
I think I understand...:
- Notepad++ 64 bits v8.2.1 or 8.3.3 + PythonScript 64 bits v3.0.12 installed with the .msi ==> error (at home W11 and at work W10)
- Then now at home, some tests:
   - N++ 64 v8.3.3 + Pythonscript v3.0.12 installed with .msi ==> error
   - Then I manually install the Full v3.0.12.zip ==> no error
   - When I compare the plugins folder after .msi and after .zip, the only differences are... 24 additional files in the lib folder in the zipped version

**Comment by chcg** [comment]
Confirmed that there is an issue with the installer. That issue seems to be no new one. Maybe introduced with https://github.com/bruderstein/PythonScript/releases/tag/v1.0.9.

**Comment by chcg** [comment]
Fixed with https://github.com/bruderstein/PythonScript/releases/tag/v3.0.13
