### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by vanmorden** [bruderstein/PythonScript#230]
Hi.

I´m trying to use the library cryptography but when I do an import like this 'from cryptography.fernet import Fernet', I get this error:
> from cryptography.fernet import Fernet
*Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\ProgramasInstalados\Python\Python310\lib\site-packages\cryptography\fernet.py", line 15, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "D:\ProgramasInstalados\Python\Python310\lib\site-packages\cryptography\hazmat\primitives\padding.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: DLL load failed while importing _rust: No se puede encontrar el módulo especificado.*

I read maybe is the path and I added the path: 'sys.path.append("D:\ProgramasInstalados\Python\Python310\Lib\site-packages\cryptography\hazmat\bindings")'

When I print the path on the console I found a surprise:
D:\ProgramasInstalados\Python\Python310\Lib\site-packages\cryptography\hazmatindings

Instead of show 'hazmat\bindings' show a strange char.

I´m using Notepad++ v8.3 64bits with pulgin Python Script 3.0.12.0 and an installed version of Python 3.10.2

P.D.: I can use the library perfectly outside Notepad++

**Comment by chcg** [comment]
@vanmorden See https://www.w3schools.com/python/gloss_python_escape_characters.asp -> \b is backspace, so you have to use \\ instead of just \

**Comment by alankilborn** [comment]
or use a "raw" string:

`sys.path.append(r"D:\ProgramasInstalados\Python\Python310\Lib\site-packages\cryptography\hazmat\bindings")`

Note the `r` after `append(`.

Again, though, basic Python stuff here.

**Comment by vanmorden** [comment]
You are right, I made an apprectice error but my problem is not the append of the path.
Altthough, I set the path the way you teach me I can't load the library inside Notepadd++.
The error is the same. I can use the library if I use it on th CLI.

**Comment by chcg** [comment]
See https://github.com/bruderstein/PythonScript/blob/master/PythonScript/src/PythonHandler.cpp#L105-L109

seems site packages are intentionally not imported. There seem to be problems way back with python 2.7 with python init.

**Comment by Ekopalypse** [comment]
@vanmorden 
Make sure that you have copied python3 and python310 dll from your local installation to the PythonScript directory.
![image](https://user-images.githubusercontent.com/47723516/166230898-9e164c6a-bccb-4944-9670-dd9389efc787.png)

**Comment by vanmorden** [comment]
Hi!
I copied the two DLLs again and now it's working.
I don't know.
Thanks by the way.
