### ISSUE TITLE
Latest 3.0.13 PythonScript crashes with latest Notepad++ Scintilla 5 development build

### ISSUE THREAD

**Issue by vinsworldcom** [bruderstein/PythonScript#233]
![image](https://user-images.githubusercontent.com/9657169/162354107-0d21b9b7-033a-427d-8da4-9b7db596bd7a.png)

I've disabled my user 'startup.py' - the only thing running is the standard 'startup.py` included in the PythonScript package.

## Using:

https://github.com/bruderstein/PythonScript/releases/download/v3.0.13/PythonScript_Min_3.0.13.0_x64.zip

System Python 3.10.4

Notepad++ 8.3.3+ 64-bit artifact (includes Scintilla 5+): https://ci.appveyor.com/api/buildjobs/6rlbvr96ibvgynmw/artifacts/Notepad%2B%2B.x64.Release.exe

Notepad++ v8.3.3   (64-bit)
Build time : Apr  7 2022 - 17:29:28
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : PythonScript.dll

**Comment by vinsworldcom** [comment]
More info:  I've downgraded to the official Notepad++ 8.3.3 release 64-bit and still having issues.  I've disabled my PythonScriptStartup.cnf which may have been causing issues.  Now Notepad++ loads fine, but as soon as I click Plugins => Python Script => Show Console

![image](https://user-images.githubusercontent.com/9657169/162426590-5e81afbc-8338-4402-a4bf-1eeea429085a.png)

Cheers.

**Comment by vinsworldcom** [comment]
Further testing shows that the "FULL" version (vs. "Min" which I've been using) seems to work OK in both my scenarios - with 8.3.3 and the latest 8.3.3 dev release including Scintilla 5+.  So it seems to be some difference in the Full vs Min version and since a diff seems to indicate the DLLs are the same, is the Min version missing some Python libraries that are "required" for it to run?

**Comment by chcg** [comment]
@vinsworldcom Min is a stripped version with just the basic python files and without additional packages. On my system 

```
Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Users\xxx\Repos\npp.8.3.3.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1645
Current ANSI codepage : 1252
Plugins : PythonScript.dll 
```
I can't reproduce the issue, also the setup seems quite similar to yours. Do you use a debug version of pythonscript?

**Comment by vinsworldcom** [comment]
> Do you use a debug version of pythonscript?

No, I just downloaded a fresh copy of Notepad++ 8.3.3 and PythonScript 3.0.13-x64-Min and still get when I try to open the console via menu:

![image](https://user-images.githubusercontent.com/9657169/163573790-5298a0e4-cc33-42bf-8371-544c593f44e3.png)

Note, in my fully customized version of Notepad++ running the latest dev build, I have PythonScript 3.0.13-x64_PluginAdmin working fine.  I seems the Min version may just be missing some Python modules that my system Python doesn't have as the DLL's seem the same:

```
PS VinsWorldCom ~ > ls -al .\Downloads\npp\plugins\PythonScript\
total 5924
drwx------  1 VinsWorldCom               0 Mar 22 02:13 .\
drwx------  1 VinsWorldCom               0 Mar 22 02:13 ..\
drwx------  1 VinsWorldCom               0 Mar 22 02:13 doc\
drwx------  1 VinsWorldCom               0 Apr 15 09:01 lib\
-rw------a  1 VinsWorldCom         4445640 Mar 16 12:39 python310.dll
-rw------a  1 VinsWorldCom         1620480 Mar 22 02:11 PythonScript.dll
drwx------  1 VinsWorldCom               0 Mar 22 02:13 scripts\

PS VinsWorldCom ~ > ls -al C:\usr\bin\npp64\plugins\PythonScript\
total 5924
drwxr-x---  1 VinsWorldCom               0 Apr  8 15:35 .\
drwxr-x---  1 VinsWorldCom               0 Apr  8 15:35 ..\
drwxr-x---  1 VinsWorldCom               0 Mar 22 02:13 doc\
drwxr-x---  1 VinsWorldCom               0 Apr  8 15:36 lib\
-rw-r----a  1 VinsWorldCom         4445640 Mar 16 12:39 python310.dll
-rw-r----a  1 VinsWorldCom         1620480 Mar 22 02:11 PythonScript.dll
drwxr-x---  1 VinsWorldCom               0 Apr  8 15:35 scripts\
```

If I'm the only one having this issue, back-burner it as I have a working solution with the full version.  I've typically been using Min in the past just to have the minimal amount of module overlap in PythonScript and my system Python and prefer installing all my libraries in the system Python.  I do this since I mainly use PythonScript with a pretty hefty PythonScript "IDE" script running with lots of call backs that makes Notepad++ a pretty functional Python IDE for my Python3 development.

Cheers.
