### ISSUE TITLE
Doc Format - class clase

### ISSUE THREAD

**Issue by cmeriaux** [bruderstein/PythonScript#24]
In the documentation, can you modify the case of the class/function so that it's directly executable in the python console ?

Example **Editor**.addText(text) would be **editor**.addText(text)

Thank you

**Comment by bruderstein** [comment]
Unfortunately, I don't think I can. It uses the standard python generator, and `Editor` is the class, `editor` is the predefined variable that is an instance of that class. Hence `editor.addText` would not be correct, and would i think be inconsistent with all other python documentation.

**Comment by cmeriaux** [comment]
Thank you for answer. I get your point and I think you're right.
I found out a solution.
Editor = editor thant I can copy/paste from the doc ;-)
