### ISSUE TITLE
Toolbar button created with Customize Toolbar moves to end of toolbar after use

### ISSUE THREAD

**Issue by kiwichick888** [bruderstein/PythonScript#249]
Using Windows 10 Pro, Npp v8.4.6, Customize Toolbar v5.3 and Python Script v2.

I will start by saying that I have no idea if this is a problem with Npp, Customize Toolbar, or Python Script so I'm asking wherever I can think of. So far I've asked in the Npp Community forum and in the Npp subreddit on Reddit but haven't received any help.

I have a Customize Toolbar button I created for one of my Python scripts. After I use the button, the next time I start Npp, the button has moved to the end of the toolbar. It will not stay where I place it. Can anyone give me any idea why this happens?

I know I can create a toolbar button using Python Script but I don't want to because the button tooltips don't take on the name of the script and there's no way to set a name within the config - they're just named generically “Python Script x” (where x is a number).

**Comment by alankilborn** [comment]
It seems like a _CustomizeToolbar_ issue.  I use that as well and I've seen on rare occasions where it spontaneously moves a button around; not anything major and not often.

**Comment by chcg** [comment]
@kiwichick888 So likely you should report the problem at https://sourceforge.net/projects/npp-customize/

**Comment by kiwichick888** [comment]
> It seems like a _CustomizeToolbar_ issue. I use that as well and I've seen on rare occasions where it spontaneously moves a button around; not anything major and not often.

Thanks, it's only ever moves it to the end of the toolbar and it's only this one button  - although I've not tried another Python Script button to see if it's specifically that plugin that's affected .

**Comment by kiwichick888** [comment]
> @kiwichick888 So likely you should report the problem at https://sourceforge.net/projects/npp-customize/

I didn't want to start straight off with a bug report when I wasn't sure if it was a CT issue so I posted in the Discussion over there. It says "Post awaiting moderation" but I'm not holding my breath, because the the last post in Discussions was over a year ago. The last ticket was lodged nine years ago so I don't even know how active the project is anymore.

**Comment by alankilborn** [comment]
> I don't even know how active the project is anymore.

Well, there was a new release (of Customize Toolbar) just a bit over a year ago; see [HERE](https://community.notepad-plus-plus.org/topic/21704/customize-toolbar-new-version-5-3).  I don't know if this means anything, but that's fairly current.

**Comment by kiwichick888** [comment]
> > I don't even know how active the project is anymore.
> 
> Well, there was a new release (of Customize Toolbar) just a bit over a year ago; see [HERE](https://community.notepad-plus-plus.org/topic/21704/customize-toolbar-new-version-5-3). I don't know if this means anything, but that's fairly current.

Yes, I saw that too. Still, over a year ago is quite a while with no new activity. I'll just have to wait and see, I guess.

**Comment by chcg** [comment]
@kiwichick888 For now I consider this as a Customize Toolbar issue.

**Comment by kiwichick888** [comment]
> @kiwichick888 For now I consider this as a Customize Toolbar issue.

Thanks for letting me know.
