### ISSUE TITLE
notepad.getCurrentDocIndex(v) doesn't return -1 if view 'v' is not open

### ISSUE THREAD

**Issue by alankilborn** [bruderstein/PythonScript#255]
If I execute `notepad.getCurrentDocIndex(1)` and view 1 is not currently open, this occurs:

```
>>> notepad.getCurrentDocIndex(1)
18446744073709551615L
```

This is on 64-bit N++/PS and PS 2.0 (or 3.10.2).  Tested in combination with N++ v8.4.6.

I would think that on 32-bit the following would occur, but I have not recently tested this:

```
>>> notepad.getCurrentDocIndex(1)
4294967295L
```

The Notepad++ code should be sending the plugin `-1`, see here:  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6000f3bb21a42a4d28d068617e0dc642ef739b26/PowerEditor/src/NppBigSwitch.cpp#L1510

and I would expect to see this:
```
>>> notepad.getCurrentDocIndex(1)
-1
```

in either the 32-bit or 64-bit case.

------------------------------------------------------------

Note:  Workaround from Eko (after `import ctypes`):

```
>>> ctypes.c_ssize_t(notepad.getCurrentDocIndex(1)).value
-1L
```

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/blob/6000f3bb21a42a4d28d068617e0dc642ef739b26/PowerEditor/src/NppBigSwitch.cpp#L1510-L1524
and
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/42d863dd9f46768edee3013bfd232a27597f8ef9/PowerEditor/src/WinControls/TabBar/TabBar.h#L69-L71

return type is not unsigned 
https://github.com/bruderstein/PythonScript/blob/f27212c104a2a1202f397c2e026abd299152b4d0/PythonScript/src/NotepadPlusWrapper.cpp#L408-L411

idx_t alias size_t, but needs to be some signed value.

**Comment by alankilborn** [comment]
I suppose this function could "stand in" until this is fixed:

```
def getCurrentDocIndex(view):
    for (f, b, i, v) in notepad.getFiles():
        if v == view: return notepad.getCurrentDocIndex(view)
    return -1
```
