### ISSUE TITLE
Plugin Manager never installs Python library

### ISSUE THREAD

**Issue by BugZappr** [bruderstein/PythonScript#26]
When you start n++ without PythonScript installed (and have removed any pre-existing library files), and then install PythonScript via the Plugin Manager, the Python standard library is not installed.  More specifically, the following directories are either missing or empty: $(N++ directory)/plugins/PythonScript/lib and $(N++ directory)/plugins/PythonScript/scripts.  It is the "lib" directory that holds the library files.

Perhaps you have a philosophy that the Plugin Manager is only for PythonScript Lite, which lacks these directories.  They take up only 10.7 MB on my installation.  It seems unnecessary, IMHO, to exclude these just to save ~11MB, when teraByte drives are readily available and inexpensive these days.  This is just my opinion, however.  If you wish to have a PythonScript Lite, then it only seems fitting to have a PythonScript Full in the Plugin Manager.

Lacking the library is the only thing keeping Emmet from working through the Plugin Manager, see: [Emmitio plugin issue 12](https://github.com/emmetio/npp/issues/12#issuecomment-155416270).  Emmit is the replacement for ZenCoding; which allows one to perform some repetitive HTML tasks much faster, and is customizable.  Emmitio is its N++ plugin.  You might call it a prestige feature - only the best text editors support Emmit.  Without the standard library, when one attempts to expand an Emmit abbreviation into HTML, one gets only "python script plugin did not accept the script".  I have found that a recent version of PythonScript Full with the library, when its contents are copied into the "plugins" directory, works just fine with Emmet.  I can't say that I've tested it exhaustively, but I also can't say that they are using an old version of PythonScript for development, either.  Lacking the standard Python library keeps Emmet from working via the Plugin Manager.  This is to say, lacking the standard library is the only thing keeping N++ from supporting Emmit for anyone who hasn't gone so far as to install PythonScript Full by hand, from using Emmit.

When one chooses to install Emmitio from the Plugin Manager without PythonScript already installed and with the PythonScript directory removed, Plugin Manager prompts the user to install Python Script as a requirement.  If you simply add the library files to the archive downloaded by Plugin Manager, Emmitio installed this way should begin working when installed with its requirement(s).  If you opt for the Plugin Manager to have both a PythonScript Lite and PythonScript Full, then the dependency for Emmitio on PythonScript will have to be changed to PythonScript Full.  Renaming PythonScript to PythonScript Lite may also break any other plugins that rely on it without the standard library.  I wonder how many PythonScript users use Python without using at least some of its standard library anyway.  Maybe a few, but I'm guessing not many; so I favor simply including them.  Doing so will require no further action from the Emmitio team to get their plugin as well.

**Comment by chcg** [comment]
Seems to be fixed according to Emmitio plugin issue 12.
@BugZappr Could this be closed?

**Comment by chcg** [comment]
Copy operation for pythonScript:

```
<download>http://downloads.sourceforge.net/project/npppythonscript/Python%20Script%201.0.8.0/PythonScript_Full_1.0.8.0.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fnpppythonscript%2Ffiles%2FPython%2520Script%25201.0.8.0%2F</download>
<download>http://downloads.sourceforge.net/project/npppythonscript/Python%20Script%201.0.8.0/PythonScript_ExtraLibs_1.0.8.0.zip</download>
<copy from="python27.dll" to="$NPPDIR$\" validate="true"/>
<copy from="plugins\PythonScript.dll" to="$PLUGINDIR$\" validate="true"/>
<copy from="plugins\PythonScript\*.*" to="$PLUGINDIR$\PythonScript" recursive="true"/>
<copy from="plugins\doc\PythonScript\*.*" to="$PLUGINDIR$\doc\PythonScript"/>
```

so everything should be available.

**Comment by BugZappr** [comment]
Er, yes.  This has started working for me when it is downloaded in the plugin manager in Notepad++ when the plugin files are first deleted.  Indeed, rightly closed.
