### ISSUE TITLE
[Feature Request] console.show() without putting input focus in console 

### ISSUE THREAD

**Issue by alankilborn** [bruderstein/PythonScript#260]
I'd like to be able to execute `console.show()` in some of my scripts, to make sure the user of my script can see output to the console during script running.  However, I don't want input focus to move to the console in such a situation, I want input focus to remain in the editor window.

Using PS 2.0.

**Comment by Ekopalypse** [comment]
calling grabFocus after calling show works for me on PS3.
~~~py
console.show()
editor.grabFocus()
~~~

**Comment by alankilborn** [comment]
> calling grabFocus after calling show works for me on PS3.

Also works on PS 2.0.

Thanks, @Ekopalypse , it appears I should have asked you first before creating this issue.  :-)

**Comment by victorel-petrovich** [comment]
I often find same need.
I think it's worth have an option so that can have this behavior without having to add `editor.grabFocus()` in every such script? 

@alankilborn , maybe reopen the issue?

**Comment by victorel-petrovich** [comment]
maybe could have the option as a parameter: `console.show(focusInConsole=false)'
