### ISSUE TITLE
Run a script and pass parameters to it from an NPP-external script / program?

### ISSUE THREAD

**Issue by InfoBube** [bruderstein/PythonScript#273]
Say I have Notepad++ running and have set up a PythonScript to delete some text in the currently open tab. Is there a way for an external script (say, in Autohotkey) to pass the text string to be deleted to Notepad++ / the PythonScript so that that particular text is deleted automatically without prompting the user? I. e. the string to be deleted is not stored in the NPP PythonScript but is passed to the script when it is launched? Maybe I could write to a file and read that from the PythonScript - or might there be more direct methods? Would the clipboard be an option, too?

Would be much obliged for some short feedback whether this is possible. Thanks!

**Comment by cmeriaux** [comment]
Hello, here is an idea:
Add in your PythonScript that delete some text a prompt that will ask the user the text to delete: 
example:
`str_to_delete = notepad.prompt("enter text to delete:", "prompt", "default_str")`

Now Autohotkey has to call the your python script (that could be associated with a key shortcut) and fill this dialog with the text.

Another idea would be: 
Autohotkey write in the python console the exacte function to replace:

> editor.replaceTarget(text)
> editor.rereplace(r"([A-Z]{3})\1", r"\1")


> Maybe I could write to a file and read that from the PythonScript

sounds like a good idea

> Would the clipboard be an option

Seems there isn't any function to retreive to clipboard content in python script help

In my humble opinion, it seems overkilled. wouldn't it be easier to do everything in a python script ?

**Comment by InfoBube** [comment]
Christophe,

Thank you very much for your input and ideas!

I wanted to avoid the prompt if I could. The console idea seems excellent though, cheers. I've since had the idea of having Autohotkey input the text in the actual file open in Notepad++, then go back and select it, then have the Python script grab and delete the selection, but the console should work even better.

The reason I need this is the string comes from a GUI thing (button bar) that interacts with Autohotkey. Hence handling everything in Python itself is not an option.

**Comment by alankilborn** [comment]
In the future a good place for questions such as this is the Notepad++ Community site:  https://community.notepad-plus-plus.org/

**Comment by InfoBube** [comment]
Sorry if I came to the wrong place. The question is very directly plugin-related so I thought I'd ask here.

**Comment by alankilborn** [comment]
>Sorry if I came to the wrong place. The question is very directly plugin-related so I thought I'd ask here.

Not exactly "wrong", but...
I like to think of github "issues" as a place for reporting problems with the hosted software.
As you weren't reporting a problem, your question is better served in the general Notepad++ support forum (which includes support for plugins -- and especially PythonScript aspects are well-supported there).

**Comment by InfoBube** [comment]
I see and will do so in future. Thanks

**Comment by Ekopalypse** [comment]
@InfoBube - I assume this question is answered and can be closed?

**Comment by InfoBube** [comment]
Thanks for all your help!
