### ISSUE TITLE
Custom autocomplete provider.

### ISSUE THREAD

**Issue by pawelurbanski** [bruderstein/PythonScript#275]
Dear Users and Developers,
I would like to create a custom autocompletion provider from some source. The documentation lists functions for options and some types of notifications.
Unfortunately the documentation for that case understood as shared code on the web is very sporadic.
If anyone of you knows how to get started with coding the following use-case I would be very greatful:
** A user types some characters and the autocompletion is triggered,
** I want to show my list of possible candidate completions.

Getting a current position for a parses is not a problem. But how ot handle hte callbacks such as: AUTOCCOMPLETE, AUTOCSELECTION and so on. Then there is the mysterious listUserMethod parameter, which I am confused about.

All the best and thanks,
Pawel

**Comment by chcg** [comment]
So you already read through https://www.scintilla.org/ScintillaDoc.html#Autocompletion?
Is it really necessary for your usecase to have a dynamically created autocompletion list via pythonscript? Maybe https://npp-user-manual.org/docs/auto-completion/#create-auto-completion-definition-files for a UDL (https://npp-user-manual.org/docs/user-defined-language-system/ , see examples at https://github.com/chcg/userDefinedLanguages) is sufficient for your needs.

**Comment by Ekopalypse** [comment]
@pawelurbanski 

~~~py
from Npp import editor, SCINTILLANOTIFICATION

def on_charadded(args):
    if args['ch'] == ord('.'):
        editor.autoCSetSeparator(ord(';'))
        editor.autoCShow(0, 'abc;test')

editor.callbackSync(on_charadded, [SCINTILLANOTIFICATION.CHARADDED])
~~~

As soon as you add a point, a completion list with 'abc' and `test` should be displayed.

**Comment by Ekopalypse** [comment]
@pawelurbanski, @chcg - can this be closed or are there still open questions?
