### ISSUE TITLE
Run Previous Script

### ISSUE THREAD

**Issue by irendak** [bruderstein/PythonScript#279]
The PythonScript 2.0 Plugin no longer (at least compared with 1.5.4) list the name of the previously ran script on the menu-line "Run Previous Script (missing-here)   Ctrl-Sht R ".
a sore loss IMHO
(I don't know if this was fixed in the 3.x versions)

---------------
F-Up : I can not recreate the problem either!
All I remember was the appearance was "Run Previous script ( )     Ctrl+Shift+R"
Will re-post with details if problem recurs.

**Comment by alankilborn** [comment]
It works for me in PS 2.0.

**Comment by Ekopalypse** [comment]
@irendak, works for me with both PS2 and PS3. Can you give more details when this happens to you?

**Comment by Ekopalypse** [comment]
@irendak @chcg
Can this be closed and reopened if needed?
