### ISSUE TITLE
Release on GitHub older than on SourceForge

### ISSUE THREAD

**Issue by Gitoffthelawn** [bruderstein/PythonScript#28]
The release on GitHub is v1.0.7.0, but the release on SourceForge is v1.0.8.0

See: http://npppythonscript.sourceforge.net/changelog.shtml

Can you sync them so the latest release is available in both locations?

**Comment by chcg** [comment]
Added tag for v1.0.8.0, see https://github.com/bruderstein/PythonScript/releases/tag/v1.0.8

**Comment by Gitoffthelawn** [comment]
Thanks!
