### ISSUE TITLE
Add Begin/End Select in Column Mode to MENUCOMMAND

### ISSUE THREAD

**Issue by alankilborn** [bruderstein/PythonScript#281]
In the release of N++ after 8.4.9 (and thus presumably 8.5) the _Edit_ menu has a new command:  _Begin/End Select in Column Mode_.

This needs to be added to PythonScript's MENUCOMMAND class.

Supporting info:

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12833
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13034
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/07924528c4407f0d99f8ac01862e2d21dcc69899

**Comment by Ekopalypse** [comment]
Can be closed I guess, implemented with [0588292fe2b2ffc431905157da0fea8aacd83447](https://github.com/bruderstein/PythonScript/commit/0588292fe2b2ffc431905157da0fea8aacd83447)

**Comment by chcg** [comment]
Just the enum description of the docu is not up-to-date with the impl.

**Comment by Ekopalypse** [comment]
will take care of it
