### ISSUE TITLE
Single python script does not appear in Shortcut Mapper

### ISSUE THREAD

**Issue by Gitoffthelawn** [bruderstein/PythonScript#29]
If the installation only has a single python User Script added as a menu item, that menu item does not appear in the Shortcut Mapper.

Once a second python User Script is added (or the first one is added twice, thus creating two menu items), then they will appear in the Shortcut Mapper.

**Comment by ClaudiaFrank** [comment]
Seems to be no issue anymore

![grafik](https://user-images.githubusercontent.com/16170444/39210460-11523c84-4809-11e8-9b92-d0a39f04f8fb.png)

**Comment by Gitoffthelawn** [comment]
LOL.  A year and a half later! :)

Has anything changed that would resolve the issue?

**Comment by ClaudiaFrank** [comment]
I've tested with 1.0.8 and current npp 7.5.6 and it didn't show the reported behavior.
So looks like it has been solved with one of the newer npp versions.

![grafik](https://user-images.githubusercontent.com/16170444/39395831-f89fcbc4-4ae3-11e8-8b8c-d47038b73932.png)
