### ISSUE TITLE
in configuration window, not all instructions visible 

### ISSUE THREAD

**Issue by victorel-petrovich** [bruderstein/PythonScript#294]
See at the bottom of the picture how for some instruction text is not visible in the wrapped part (text lines overlap). 
For both installer and portable. My current system details after the pic
![image](https://github.com/bruderstein/PythonScript/assets/11040279/4b35636e-4b9c-4df5-afc5-8db1244e02f9)

Notepad++ v8.5.4   (32-bit)
Build time : Jun 17 2023 - 20:40:14
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\Vic\Desktop\scratch.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (32-bit)
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.4)
    NppExport (0.4)
    PythonScript (2)

**Comment by alankilborn** [comment]
Cannot reproduce:

![image](https://github.com/bruderstein/PythonScript/assets/77065706/b4b1a7f0-4aa9-4542-abde-8546aa1997ad)

on:

Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : C:\NotepadPlusPlus\Portable\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1992
Current ANSI codepage : 1252
Plugins : 
    AnalysePlugin (1.13.49)
    BetterMultiSelection (1.4)
    DSpellCheck (1.4.24)
    EnhanceAnyLexer (1.0.1)
    Explorer (1.9.3)
    GotoLineCol (2.4.2)
    mimeTools (2.9)
    NavigateTo (2.6)
    NppConverter (4.5)
    NppEditorConfig (0.4)
    NppExec (0.8.3)
    NppExport (0.4)
    NppMultiReplace (1)
    PythonScript (2)
    _CustomizeToolbar (5.3)

**Comment by victorel-petrovich** [comment]
I checked it's same problem with portable version, on the same Windows 7 Ultimate (32-bit) and Notepad++ v8.5.4 (32-bit).

**Comment by chcg** [comment]
I also can't reproduce it on my Win10 system. Also not with 32bit version of N++.  As this is a static dialog window the only option seems to be that the styles of the gui elements differs between WIn7 and Win10 and may cause this glitch. Or some HiDPI scaling.

As Win7 is out of support and I don't have such a Win7 system available this issue will likely be not fixed as long as it is not reproducible for Win10.

**Comment by victorel-petrovich** [comment]
It's usable.
