### ISSUE TITLE
Still runs using Python 2.7 - super-outdated

### ISSUE THREAD

**Issue by richlysakowski** [bruderstein/PythonScript#295]
This is nuts.  I get Python 2.7 when I install and run this plugin.  Python 2.7 is out of support for 3.5 years now.  

I get this message when I run the "console" from PythonScript:  

Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]

Then help() gives: 

 help()

Welcome to Python 2.7!  This is the online help utility.

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at http://docs.python.org/2.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, or topics, type "modules",
"keywords", or "topics".  Each module also comes with a one-line summary
of what it does; to list the modules whose summaries contain a given word
such as "spam", type "modules spam".

help> 
You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.

**Comment by alankilborn** [comment]
If you install via Notepad++'s _Plugins Admin_ you get PythonScript 2.0, which uses Python 2.7.

Go [HERE](https://github.com/bruderstein/PythonScript/releases) and look for v3.xx Alpha releases.

There's an unsolved problem with legacy encoding usage preventing full migration to Python 3.  If you don't use legacy encodings, no problem with using a v3.xx Alpha version (but you have to install manually).

**Comment by chcg** [comment]
See https://github.com/bruderstein/PythonScript/issues/36 on python 3 development.
