### ISSUE TITLE
editor.rereplace() not escaping backslash 

### ISSUE THREAD

**Issue by jzajac2** [bruderstein/PythonScript#30]
Trying this:

```
editor.replace("Path=\"Source\\MySecretProject\\obj\\Debug\\MySecretProject.dll", "Path=\"Source\\%ProjectName%\\obj\\%Configuration%\\%TargetFileName%")
editor.replace("Path=\"Source\\MySecretProject\\bin\\Debug\\MySecretProject.dll", "Path=\"Source\\%ProjectName%\\bin\\%Configuration%\\%TargetFileName%")
```

However result in the replacement when I run the macro ends up as:

`Path="Source%ProjectName%obj%Configuration%%TargetFileName%"`

Unfortunately I'm limited to having to replace strings with backslashes in them as there are other strings with word 'Debug' which I DON'T want to replace (these ones are not part of msbuild I am using to replace with env vars). And I don't think editor.replace() comes with a way to replace 'whole word only'. Therefore, I am qualifying with a rather large string with backslashes. Hmm..Still thinking of a way.  

Maybe a way out of this with a regex replace. Let me know if you can think of a good workaround, I'm new to python.

**Comment by ClaudiaFrank** [comment]
In case someone stumbles across this, something like this would solve this issue
`editor.replace(r'Path=\"Source\MySecretProject\obj\Debug\MySecretProject.dll"', r'Path=\\"Source\\%ProjectName%\\obj\\%Configuration%\\%TargetFileName%"')`

**Comment by chcg** [comment]
Considered to be solved with comment above.
