### ISSUE TITLE
Console not persistent visible during relaunch

### ISSUE THREAD

**Issue by vinsworldcom** [bruderstein/PythonScript#312]
As @rdipardo points out in https://github.com/mohzy83/NppMarkdownPanel/issues/90, the `NppTbData.pszModuleName` must be assigned to the DLL file name in order for Notepad++ to remember persistence.  It is not:

https://github.com/bruderstein/PythonScript/blob/92565802ada5be206181e3f77f5c0770b09c612e/PythonScript/src/ConsoleDialog.cpp#L567

Cheers.

**Comment by chcg** [comment]
@vinsworldcom Thanks for forwarding this topic here and thanks @xomx for the PR.

**Comment by vinsworldcom** [comment]
Just tested the artifact - works as expected for me with simple test leaving the window visible and closing - it's there on re-launch.  Closing the window, it is not there on relaunch.

Thank you @xomx for the complete PR and @chcg for merging so quickly!

Cheers.
