### ISSUE TITLE
editor.getTextRange() crashes notepad

### ISSUE THREAD

**Issue by gilmijar** [bruderstein/PythonScript#317]
A line such as this `editor.getTextRange(1, 4)`
Causes Notepadd++ to close without showing an error.

debug info from NPP:

> Notepad++ v8.5.7   (64-bit)
> Build time : Sep  6 2023 - 23:13:49
> Path : C:\Users\iligi\AppData\Local\npp.8.5.7.portable.x64\notepad++.exe
> Command Line : 
> Admin mode : OFF
> Local Conf mode : ON
> Cloud Config : OFF
> OS Name : Windows 10 Enterprise (64-bit)
> OS Version : 22H2
> OS Build : 19045.3570
> Current ANSI codepage : 1252
> Plugins : 
>     ComparePlugin (2.0.2)
>     JsonTools (5.6)
>     mimeTools (2.9)
>     NppConverter (4.5)
>     nppcrypt (1.0.1.6)
>     NppExport (0.4)
>     NPPJSONViewer (2.0.6)
>     PythonScript (3.0.1)

**Comment by alankilborn** [comment]
You're going to have to be more specific about the setup and steps to reproduce this problem.

**Comment by chcg** [comment]
@gilmijar You are using pythonscript 3.0.1. Please update to the current release https://github.com/bruderstein/PythonScript/releases/tag/v3.0.16 . Likely you are facing issue #218 or something similar caused by the interface change with N++ 8.3 and newer.

**Comment by gilmijar** [comment]
I see.
I think my problem is having a manual graft from packages in github.
https://github.com/bruderstein/PythonScript/issues/218#issuecomment-1030664668
so I think this is not a real problem with PythonScript.
I'm loving thus addon, by the way.
