### ISSUE TITLE
"☑ Automatically open console on error" should be default behavior

### ISSUE THREAD

**Issue by pryrt** [bruderstein/PythonScript#329]
The **Configuration... > ☑ Automatically open console on error** option should be checkmarked by default,

For experienced users, it makes sense to be able to turn _off_ that option.  But for people who are new to PythonScript (including all the people who ask for solutions in the Community Forum, and we either point them to a script from a FAQ or to a script already in the forum or to a custom script that we write for them), when they start with their first script and do something wrong, their script runs and "nothing happens", which is a bad user experience, and makes debug more difficult.

I have updated the Community's FAQ to recommend checkmarking that option when they install, but you know how well people follow instructions in a FAQ ;-).  (And that won't help users outside the Community.)

On the other hand, if PythonScript shipped with that option turned on, then as soon as there was an error, the console would pop up. Even if they cannot do the debug on their on, they would at least have error text to paste into their Community post, rather than just saying "I tried it and nothing happened".  

I'd even suggest that this was worth doing a v2.0.1 release in addition to including it in the v3.x_alpha branch, and updating the link in nppPluginList to v2.0.1, so that the version that newbies install from Plugins Admin will have that option on by default.

**Comment by alankilborn** [comment]
It makes good sense.

**Comment by chcg** [comment]
Relevant change is at:
https://github.com/bruderstein/PythonScript/blob/45e0be66b759fc6d1120f11006e838f04640db72/PythonScript/src/ConfigFile.cpp#L47
