### ISSUE TITLE
Wrap text in console

### ISSUE THREAD

**Issue by matthewacarson** [bruderstein/PythonScript#330]
Hi. Is it possible to wrap the output in the console? Sometimes the output is very long and difficult to read. Thanks!

**Comment by Ekopalypse** [comment]
The console is a Scintilla instance, as used by Npp itself.
You can access it via `console.editor` and set the wrapping mode with `console.editor.setWrapMode`.
See [here](https://www.scintilla.org/ScintillaDoc.html#SCI_SETWRAPMODE) for the description of the possible values available via the `WRAP` class.

**Comment by chcg** [comment]
@matthewacarson Is enabling warpping via script command sufficient for your needs?

**Comment by alankilborn** [comment]
> Is enabling wrapping via script command sufficient for your needs?

I should think so; with that everyone can easily customize it have exactly what they want; e.g., put the following in user startup.py:

```py
console.editor.setWrapMode(WRAP.WORD)
console.editor.setWrapIndentMode(WRAPINDENTMODE.SAME)
console.editor.setWrapStartIndent(0)
console.editor.setWrapVisualFlags(WRAPVISUALFLAG.END)
console.editor.setWrapVisualFlagsLocation(WRAPVISUALLOCATION.END_BY_TEXT)
```

Change the parameters to the function as desired.

**Comment by matthewacarson** [comment]
> @matthewacarson Is enabling warpping via script command sufficient for your needs?

Yes!



> > Is enabling wrapping via script command sufficient for your needs?
> 
> I should think so; with that everyone can easily customize it have exactly what they want; e.g., put the following in user startup.py:
> 
> ```python
> console.editor.setWrapMode(WRAP.WORD)
> console.editor.setWrapIndentMode(WRAPINDENTMODE.SAME)
> console.editor.setWrapStartIndent(0)
> console.editor.setWrapVisualFlags(WRAPVISUALFLAG.END)
> console.editor.setWrapVisualFlagsLocation(WRAPVISUALLOCATION.END_BY_TEXT)
> ```
> 
> Change the parameters to the function as desired.

That worked like a charm. Thanks!
