### ISSUE TITLE
Two methods, editor.markerAdd and editor.markerSetBack, have errors. How do I modify our setback?

### ISSUE THREAD

**Issue by jokerlbking** [bruderstein/PythonScript#333]
With editor.markerAdd and editor.markerSetBack some lines failed to convert a background color. I observed that a consistently fixed number of lines failed to convert a row background color.
![1](https://github.com/bruderstein/PythonScript/assets/73996603/e476cb10-3d59-473c-9eb6-71c4caa877bd)
As shown in the figure, the effect I want to achieve is that the background of the number rows is yellow, but there are always fixed rows that cannot change the background color. My PythonScript version is 2.0. How to modify, is there a problem with my script writing? Or is the underlying logic of notepad++ itself problematic?
The full content of my script is as follows:

```
# coding:utf-8 
from Npp import *

#a = editor.getLine(14).isdigit()
#print (a)
#b = editor.getLine(1)
#print b.strip()
#print b.isdigit()
#editor.markerSetBack(1,(245,222,179))

C_list = [21, 22, 23, 24, 32, 53,54,55,56,64,85,86,87,88,96,117,118,118,120,128,149,150,151,152,160,181,182,183,184,192,213,214,215,216]

def CheckC(count):
    
    if count in C_list:
        i = 0
        while i < 4:
            count = count + 1
            if count not in C_list:
                break
                
            i += 1
        return count
        
    else:
    
        return count 


def check_xxx(str) :

    if len(str) == 0 :
        return 1

    elif str.isdigit() :
        return 2

    else :
        return 3


def checkTop(int):
    int=int - 1
    return check_xxx(editor.getLine(int).strip())
    

def mainDef(int):
    i=0
    if checkTop(int) == 2:
        i += 1
        int += 1
        
        if checkTop(int)  == 3:
            i += 1
            int += 1
            
            if checkTop(int)  == 3:
                
                i += 1
                int += 1
                
                if checkTop(int)  == 3:
                
                    i += 1
                    int += 1
                    if checkTop(int)  == 1:
                
                        i += 1
                        int += 1
                        return i
                    else :
                        return i
                else :
                    return i
            else :
                return i
                
        else :
            return i
            
            
    else:
        return 6
        



a = 1
c = 1
editor.markerDeleteAll(-1)
while a<= editor.getLineCount() :
    b = mainDef(a)
    #print a
    if b == 5 :
        a = a + b
        continue
        
    elif b == 6:
        a += 1
    else :
        enf=editor.markerAdd(a - 1, c)
        print enf
        editor.markerSetBack(enf,(245,222,179))
        a = a + b
        c += 1
```

**Comment by alankilborn** [comment]
It's pretty much impossible to consider your script, because it isn't posted correctly.  Do this to fix it:

* Activate the N++ tab holding your script file
* Press Ctrl+a
* Press Tab
* Press Ctrl+c
* Press Ctrl+z (to undo the tabbing)
* Paste into a new comment here on this site

---

Also, paste some of the data you want to affect (looks like video subtitles data?) here, AS TEXT, not only as a screenshot.  If you put it inside lines with three-backtick delimiters before and after like this:

![image](https://github.com/bruderstein/PythonScript/assets/77065706/2f37de45-e0ac-4afa-b7db-52082d9236da)

then it will appear unmangled, and like this:

```
one
two
three
```

---

Finally, be clearer about what effect you are trying to achieve.  We can see some of it in the screenshot, but from the rest of your description, I'm not sure if the `21`, `22`, `23`, `24` lines are also supposed to have the backgrounding effect??

**Comment by jokerlbking** [comment]
Thanks for your help, because I am a beginner and I am Chinese, so I can only understand the functions of Python Script through translation.
The purpose of my script is to help me distinguish those subtitle files that do not conform to the Chinese and English bilingual subtitles. His judgment logic is a small group of four lines. If these four lines conform to the judgment criteria given by me, then no operation will be done. If it doesn't meet my criteria, the script automatically changes the color of the first of the four lines to help me identify the progression that doesn't meet the subtitle criteria and correct it.
markerSetBack() : Set the background colour used for a particular marker number. Set the background colour used for a particular marker number. So I use it to change the background color of the first row in a group.
Now I'm having trouble with the fact that when the script gets to a certain number of lines, it doesn't change the background color of the first line of the team that doesn't meet the requirements, but instead skips or changes to other markup symbols, which makes me confused. I hope I can get your help.
I will upload my subtitle file and my script file, and you can execute it to see if you have the same situation as me.
Subtitle file.txt is a Subtitle file, and 1.txt is a script file.
Finally, thank you again.
[Subtitle file.txt](https://github.com/bruderstein/PythonScript/files/14837315/Subtitle.file.txt)
[1.txt](https://github.com/bruderstein/PythonScript/files/14837335/1.txt)

**Comment by alankilborn** [comment]
One thing I notice is that when you call `editor.markerAdd()`, you are doing it with a different marker number that keeps increasing each time (tracking the `c` variable).  The Scintilla documentation for markers says there are only 32 possible markers, so this is a real problem in your script.  You should choose one marker number (maybe zero?) and use that in every call to markerAdd.

**Comment by jokerlbking** [comment]
Thanks for your help, my problem is solved. The second argument in the original markerAdd() does not need to increase with degree. Thank you again. I wish you good health and a happy life.
