### ISSUE TITLE
permanent setting

### ISSUE THREAD

**Issue by DomOBU** [bruderstein/PythonScript#335]
Hello,

I'm a new PythonScript user. I'm not a geek and I don't know Python.

On the Notepad++ forum I was recommended to install PythonScript to solve a CSS problem with Lexilla.
A command was provided. I tested it in the console; it's operational but temporary.
I haven't found a way to make it permanent when I launch Notepad++. How would this be possible?

Thank you for your reply.

**Comment by Ekopalypse** [comment]
I do not know what "command" you are referring to but to make something permanent you usually create a script and name it `startup.py`. It must be called startup.py and it shouldn't be the one that comes with the plugin itself. Change to configuration from `LAZY` to `ATSTARTUP` and then this script will run every time Npp starts.

**Comment by Ekopalypse** [comment]
No, the startup.py that is supplied with the plugin must remain. The "user" startup.py must also be created.
the setProperty function must be called for both editor instances

```python
editor1.setProperty...
editor2.setProperty...
```

the `editor` refers to the currently active instance and would only be set for this instance.

Do you have changed the Python Script Configuration from `LAZY` to `ATSTARTUP`?

**Comment by Ekopalypse** [comment]
No, this is a Lexer property that you want to set. This must be done differently.
You need to register a callback for bufferactivated and then set the property.
This should still be done in the user startup.py.

**Comment by Ekopalypse** [comment]
@DomOBU - Is there anything still open, or can this topic be closed?
