### ISSUE TITLE
Fix invalid enums

### ISSUE THREAD

**Issue by tooruu** [bruderstein/PythonScript#344]
The following enums are invalid. Please change the attribute names to valid identifiers.
https://github.com/bruderstein/PythonScript/blob/52f7d7b3745ebd629ff4549365b13aac4c813c95/docs/source/enums.rst?plain=1#L1349 https://github.com/bruderstein/PythonScript/blob/52f7d7b3745ebd629ff4549365b13aac4c813c95/docs/source/enums.rst?plain=1#L1351 https://github.com/bruderstein/PythonScript/blob/52f7d7b3745ebd629ff4549365b13aac4c813c95/docs/source/enums.rst?plain=1#L1587

**Comment by Ekopalypse** [comment]
Why do you think they are invalid?
They are created from the [header](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/504e4ca5dfbb524ab09343a9ea24ab3e12846792/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L49), they might be outdated, but ... invalid?

**Comment by tooruu** [comment]
> Why do you think they are invalid? They are created from the [header](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/504e4ca5dfbb524ab09343a9ea24ab3e12846792/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L49), they might be outdated, but ... invalid?

In the header the enums are prefixed with `WV_`, making them valid identifiers. However, names cannot start with a number according to [the docs](https://docs.python.org/3/reference/lexical_analysis.html#identifiers). We can use `str.isidentifier` method to see if a string is a valid identifier.
```py
>>> WINVER.WIN10.name
'WIN10'
>>> WINVER.95.name
  File "<console>", line 1
    WINVER.95.name
          ^^^
SyntaxError: invalid syntax
>>> [name for name in WINVER.names if not name.isidentifier()]
['95', '98']
```

**Comment by Ekopalypse** [comment]
I see, thanks for the clarification.
