### ISSUE TITLE
N++ Save All and Save event support

### ISSUE THREAD

**Issue by bwisely** [bruderstein/PythonScript#350]
Can I know if the Python Script supports the Notepad++ event that identifies Save/Save All?
Because I make a python script to trigger the script to something before saving it to disk.
I want to know how to get the event to measure the correct operation in Save or Save All.

For now:
Python Script has FILEBEFORESAVE, but it doesn’t know if the operation is Save or Save All.
How can Python Script know the operation it is?

Thanks for your kind help.

**Comment by alankilborn** [comment]
>Can I know if the Python Script supports the Notepad++ event that identifies Save/Save All?

PythonScript knows no such distinction, so it can't pass that along to the script programmer.

Saving all is just a series of saving one.

One hacky thing that comes to mind that _might_ work would be subclass the Notepad++ message loop and watch for what happened most recently, i.e., `MENUCOMMAND.FILE_SAVE` vs. `MENUCOMMAND.FILE_SAVEALL`.

**Comment by alankilborn** [comment]
Maybe if you say a bit more about what your script is trying to do...someone will have suggestions on how to accomplish it without needing to know save/all differences.

**Comment by bwisely** [comment]
my script is to update the code content's timestamp.
For example, the last modified date and time need to be updated to the current time when the user does the save or save all.
i.e.:
original code content
=================
# -*- coding: utf-8 -*-
# Last Modified Date, 2024-10-21
# Last Modified Time, 12:16:19
import re
from Npp import notepad, editor, NOTIFICATION
import datetime
import os
=================
When the user clicks notepad++ save, the script automatically updates the data and time strings to the current time.
But for clicks "save" and "save all," the Python script (or notepad++ is not supported) cannot determine which one saves to the disk.
For "save," it's saving one file; it's workable.
But when I implement "save all," the behavior is always incorrect.

**Comment by alankilborn** [comment]
Something like the following script seems to work:

`UpdateUnsavedFilesUponSaveAll.py` : 

```py
# -*- coding: utf-8 -*-
from __future__ import print_function

#########################################
#
#  UpdateUnsavedFilesUponSaveAll (UUFUSA)
#
#########################################

# references:
#  https://github.com/bruderstein/PythonScript/issues/350
#  https://community.notepad-plus-plus.org/topic/26217
#  for newbie info on PythonScripts, see https://community.notepad-plus-plus.org/topic/23039/faq-desk-how-to-install-and-run-a-script-in-pythonscript

#-------------------------------------------------------------------------------

assert __name__ != '__main__'  # ensure this file is not executed directly, i.e. use:  from UpdateUnsavedFilesUponSaveAll import UPDATE_UNSAVED_FILES_UPON_SAVE_ALL from another file, e.g. startup.py

#-------------------------------------------------------------------------------

from Npp import *
import time

#-------------------------------------------------------------------------------

class UUFUSA(object):

    def __init__(self):
        self.special_line1_leading_text = '# Last modified:'
        notepad.callback(self.filebeforesave_callback, [NOTIFICATION.FILEBEFORESAVE])

    def filebeforesave_callback(self, args):
        notepad.activateBufferID(args['bufferID'])
        if editor.getLine(1).startswith(self.special_line1_leading_text):
            editor.replaceLine(1, self.special_line1_leading_text + ' ' + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))

#-------------------------------------------------------------------------------

UPDATE_UNSAVED_FILES_UPON_SAVE_ALL = UUFUSA()
```

As the script comments mention, put

`from UpdateUnsavedFilesUponSaveAll import UPDATE_UNSAVED_FILES_UPON_SAVE_ALL`

in user `startup.py`.

Also, make sure that "Initialisation" for "Python Script Configuration" is set to "ATSTARTUP" and not "LAZY".

**Comment by bwisely** [comment]
Sorry for my brief description.
my issue is that Notepad++ has buttons for [Save] and [Save all], and my script replaces the timestamp that the modified file needs to save to disk.
I'm unsure if PythonScript can support it; maybe I post a request in the Notepad++ community that I post the same one to support [Save] and [Save all] events that let PythonScipt get different triggers.

my script is to check the first 15 lines of want to save file(s); if the check string is met, replace the date or timestamp. Current;y, my script only support [Save] bottom, but [Save all]
row-1 # Last Modified Date, 2024-11-21
row-2 # Last Modified Time, 23:40:59


below is my script
=================
```
# -*- coding: utf-8 -*-
import re
from Npp import notepad, editor, NOTIFICATION
import datetime
import os

def get_comment_syntax(file_ext):
    # == check ext name to confirm which prefix need to process ===
    if file_ext in ['.bat', '.cmd']:
        return ['REM', '::']
    elif file_ext in ['.bas']:
        return "'"
    elif file_ext in ['.ps1', '.py']:
        return "#"
    else:
        return None

def update_last_modified(args=None):

    console.clear()

    # Date and Time format
    current_date = datetime.datetime.now().strftime("%Y-%m-%d")
    current_time = datetime.datetime.now().strftime("%H:%M:%S")

    # get file path and extension
    current_file = notepad.getCurrentFilename()
    file_ext = os.path.splitext(current_file)[1].lower()
    console.write(f"current extenstion is {file_ext}\n")
    console.write(f"Current filename is \n")
    console.write(f"{current_file}\n")
    console.write(f"==============================================\n")
    console.write(f"if updated, the row number as below :\n")


    comment_syntaxes = get_comment_syntax(file_ext)

    # not supported file
    if comment_syntaxes is None:
        console.write(f"not support, not defined :{file_ext}\n")
        return False

    # comment_syntax + String
    date_keywords = [f"{comment_syntax} Last Modified Date," for comment_syntax in comment_syntaxes]
    time_keywords = [f"{comment_syntax} Last Modified Time," for comment_syntax in comment_syntaxes]
    # only for .bat and .cmd rule
    bat_keyword_pattern = r"(.*Created date-)(\d{4}-\d{1,2}-\d{1,2})"


    updated = False
    line_num = 0

     # checkin first 15 rows, Last Modified Date/Time
     # If changed, display. if no change, no display in console
    for line_num in range(min(15, editor.getLineCount())):
        line_content = editor.getLine(line_num).strip()

        # update date
        for date_keyword in date_keywords:
            if line_content.startswith(date_keyword):
                new_date_line = f"{date_keyword} {current_date}"
                if line_content != new_date_line:
                    console.write(f"date string in row {line_num + 1} \n")
                    console.write(f"previously: {line_content}\n")
                    editor.replaceLine(line_num, new_date_line)
                    console.write(f"after replaced: {new_date_line}\n")
                    updated = True

        # update time
        for time_keyword in time_keywords:
            new_time_line = f"{time_keyword} {current_time}"
            if line_content.startswith(time_keyword) and line_content != new_time_line:
                console.write(f"time string in row {line_num + 1} \n")
                console.write(f"previously:  {line_content}\n")
                editor.replaceLine(line_num, new_time_line)
                console.write(f"after replaced:  {new_time_line}\n")
                updated = True

        # for bat cmd title
        match = re.match(bat_keyword_pattern, line_content)
        if match:
            new_bat_line = f"{match.group(1)}{current_date}"
            if line_content != new_bat_line:
                console.write(f"bat script Title date string is row {line_num + 1} \n")
                console.write(f"previously: {line_content}\n")
                editor.replaceLine(line_num, new_bat_line)
                console.write(f"after replaced: {new_bat_line}\n")
                updated = True

    return updated

notepad.clearCallbacks()
notepad.callback(update_last_modified, [NOTIFICATION.FILEBEFORESAVE])
```

**Comment by bwisely** [comment]
In the user startup.py I have the script loaded and the setting changed from LAZY to ATSTARTUP.

```
import sys
import os
from Npp import *
appdata_path = os.getenv('APPDATA')
scripts_path = os.path.join(appdata_path, r'Notepad++\plugins\Config\PythonScript\scripts')
console.write(f"User Startup path:\n")
console.write(f"{scripts_path}\n")
console.write(f"==============================================\n")

# load my script
custom_script = os.path.join(scripts_path, 'LastChangeTimeApply.py')

try:

    if sys.version_info[0] < 3:
        # for Python 2
        execfile(custom_script)
    else:
        # for Python 3, utf8
        with open(custom_script, 'r', encoding='utf-8') as file:
            script_content = file.read()
            exec(script_content)
except Exception as e:
    console.writeError(f"!!!  Error in executing custom script: {e} !!!\n")
```

**Comment by alankilborn** [comment]
@bwisely 

>my issue is that Notepad++ has buttons for [Save] and [Save all], and my script replaces the timestamp that the modified file needs to save to disk.
I'm unsure if PythonScript can support it; maybe I post a request in the Notepad++ community that I post the same one to support [Save] and [Save all] events that let PythonScipt get different triggers.

I really don't understand the problem you seem to have.
I don't see why such a script needs to know the difference between "Save" and "Save All".

---

Oh, maybe I see it now...
In your [SCRIPT](https://github.com/bruderstein/PythonScript/issues/350#issuecomment-2430720829) at the start of your callback function, you don't change the active file, like I do in my sample script from yesterday: 

```py
    def filebeforesave_callback(self, args):
        notepad.activateBufferID(args['bufferID'])  # <--- the IMPORTANT PART!
```

If you _don't_ do this, your `editor.*` function calls for ALL files will simply operate on one file, the active file at the time _Save All_ is invoked.

`args['bufferID']` is the way for the callback notification to tell you _which_ file that `FILEBEFORESAVE` is providing info about.

Other comments on this script:

* your callback function should be declared as `def update_last_modified(args):` and not `def update_last_modified(args=None):`
* you don't need to `return False` or `return True` from your callback function as this doesn't do anything (AFAIK)

**Comment by alankilborn** [comment]
@bwisely 

If in [THIS](https://github.com/bruderstein/PythonScript/issues/350#issuecomment-2430752256) script you are showing what you have in `startup.py`, then, you are doing too much unneeded work in that file.

You should change your `LastChangeTimeApply.py` script to do this at the bottom:

```py
def initialize():
    notepad.clearCallbacks()
    notepad.callback(update_last_modified, [NOTIFICATION.FILEBEFORESAVE])
```

And then all you should have in `startup.py` for this is:

```py
import LastChangeTimeApply
LastChangeTimeApply.initialize()
```

**Comment by bwisely** [comment]
In reality, my script only supports NP++ for the click [Save] function and cannot work for click [Save All].
You can try to test my script on your Windows. You can edit my script and save it, and the timestamp will replaced.
And my script cannot work on [Save All].
When you open many files, some files do some modifications, and some files are not changed.
Then, you try to save the modified files's contents by clicking the [Save All] button to save each file that you have done some modification; it will only change the timestamp of my current file, but the timestamp of the file whose background has been modified cannot be modified.
I have tried the relevant methods on ChatGPT, but no method can achieve the function I need. GPT responded that NP++ does not support it, so Pythonscript cannot achieve the function I want, so I tried here and NP++. Post an article asking for help.

Below is GPT feedback for [Save All]'s original suggestion. Replacing the timestamp is not workable.

`def update_all_modified_files(args=None):
    open_files = notepad.getFiles()
    current_buffer = notepad.getCurrentBufferID()

    for file in open_files:
        buffer_id = file[1]
        notepad.activateBufferID(buffer_id)

        if editor.getModify():
            updated = update_last_modified()
            if updated:
                notepad.save()  
    notepad.activateBufferID(current_buffer)`

**Comment by alankilborn** [comment]
@bwisely 

>In reality, my script only supports NP++ for the click [Save] function and cannot work for click [Save All].

Correct.
The solution is to change your script to be like my sample one provided above.
If you don't listen to this advice, there is nothing I or anyone else can do to help you.

I have edited my original demo script above to include a "FOR DEBUG" block that prints things to the PythonScript console window.  With the script "installed", if you have 3 modified files (`new 1.txt`, `new 2.txt`, `new 3.txt`) and a fourth file called `new 4.txt` which is unmodified, and active when you execute _Save All_, you will see something like this in the console window:

![image](https://github.com/user-attachments/assets/33365fa7-31c5-4f98-a0c2-d664570d2d78)

This shows what happens when the FILEBEFORESAVE callbacks happen in response to the _Save All_.
For example, Notepad++ first sees that `new 1.txt` needs to be saved so it passes FILEBEFORESAVE to plugins like PythonScript.  The callback responds, and indicates that `new 1.txt` is the file to be saved via the `args` argument.  Unfortunately, `new 4.txt` is the active tab, so the tab must be switched to `new 1.txt` before any `editor.` commands can be executed.

I hope you understand this because if you don't I really can't do anything to clarify further.

---

>ChatGPT

The function provided by ChatGPT mostly seems like it would work, but it does extra and unneeded things, like switching the active tab to ALL tabs, modified or not.  My sample script from earlier only activates and saves tabs that it needs to.

**Comment by alankilborn** [comment]
@chcg 

Since I believe I have shown that there is no need for any PythonScript changes relating to this issue, you can go ahead and close it.

**Comment by chcg** [comment]
@alankilborn Thanks for your support in clarification this topic.
