### ISSUE TITLE
Any way to improve BracketHighlighter.py compatibility with EnhanceAnyLexer plugin? 

### ISSUE THREAD

**Issue by Skrell** [bruderstein/PythonScript#354]
When I use the fantastic EnhanceAnyLexer plugin with your also awesome BracketHighlighter, I see the following upon loading a new file : 
![image](https://github.com/user-attachments/assets/540e0504-214d-48ae-b3ed-96bfa6420544)

However, as soon as I click anywhere the blocks of color go away, but some times I click and they come back. 

NOTE that he blocks are only present on lines that also match regex rules in the EnhanceAnyLexer configuration 
https://github.com/Ekopalypse/EnhanceAnyLexer

**Comment by Ekopalypse** [comment]
See comment [here](https://github.com/Ekopalypse/EnhanceAnyLexer/issues/14#issuecomment-2475793144).

@chcg Which raises the question of whether scripts that were available before a certain functionality should have version guard, such as this pseudo-Python code
```python
if plugin.version >= xyz:
    do something
else:
    do something different 
```
or always be updated with the latest PythonScript plugin version.
What do you think?

**Comment by alankilborn** [comment]
> Which raises the question of whether scripts that were available before a certain functionality should have version guard, or always be updated with the latest PythonScript plugin version.

Probably either of those choices is too much burden for the PythonScript developers.
I'd say that if users have questions, they can ask and be helped to a solution (like you just did).
But, preferably the questions come on the [Community](https://community.notepad-plus-plus.org/) and not in the form of an issue.

**Comment by Ekopalypse** [comment]
@Skrell - Is there anything else to do about this, if not, can you please close this issue?

**Comment by Skrell** [comment]
This was very helpful thank you!
