### ISSUE TITLE
How to modify BracketHighlighter for arrow functions?

### ISSUE THREAD

**Issue by Skrell** [bruderstein/PythonScript#355]
Is there an easy way to modify this script to ignore angle brackets **if** they are preceded by an '=' so that '=>' doesn't count towards the stack of bracket pairings?

**Comment by Ekopalypse** [comment]
I assume if you put the if condition in the code, it should do what you want. 

````python
        for j in range(caret_index_into_str, len(str_containing_caret)):
            c = str_containing_caret[j]
            if (j > 0) and ((c == '<' and str_containing_caret[j-1] == '=') or (c == '>' and str_containing_caret[j-1] == '=')):
                continue
````
However, if you want to define multiple exceptions, I would personally define a function to handle them. 
Something along the lines of

````python
        ...
        def in_exception_condition(...): ...
        ...
        for j in range(caret_index_into_str, len(str_containing_caret)):
            c = str_containing_caret[j]
            if in_exception_condition(...): 
                continue
````

**Comment by Ekopalypse** [comment]
@Skrell - Is there anything else to do about this, if not, can you please close this issue?

**Comment by Skrell** [comment]
Works ty
