### ISSUE TITLE
BoostBase directory not set in PythonSettings.props

### ISSUE THREAD

**Issue by Ekopalypse** [bruderstein/PythonScript#360]
@chcg 

Aside from restoring missing NuGet packages and the fact that the gtest and PythonScript.Test projects won't work, the only change I had to make to create the plugin was to change the BoostBase tag in the PythonScript.props file to:

```xml
<BoostBase>$(SolutionDir)packages\boost.1.86.0\lib\native\include</BoostBase>
```

Is there anything wrong with having this by default?

**Comment by chcg** [comment]
@Ekopalypse Which version of VS do you use? VS2022? 
Setting BoostBase explicitly is not necessary in my local build and also not for Appveyor and GHA.
Did you also checkout the gtest submodule via:
`git submodule -q update --init`
?

PythonScript.Test is working for me and GHA, see e.g. https://github.com/bruderstein/PythonScript/actions/runs/12307382293/job/34350941293

> ....
> [----------] 7 tests from findPluginMenuCommand/MenuManagerFindPluginCommandTest
>   [ RUN      ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/0
>   [       OK ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/0 (2 ms)
>   [ RUN      ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/1
>   [       OK ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/1 (2 ms)
>   [ RUN      ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/2
>   [       OK ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/2 (2 ms)
>   [ RUN      ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/3
>   [       OK ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/3 (2 ms)
>   [ RUN      ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/4
>   [       OK ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/4 (2 ms)
>   [ RUN      ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/5
>   [       OK ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/5 (1 ms)
>   [ RUN      ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/6
>   [       OK ] findPluginMenuCommand/MenuManagerFindPluginCommandTest.testFindPluginCommand/6 (1 ms)
>   [----------] 7 tests from findPluginMenuCommand/MenuManagerFindPluginCommandTest (14 ms total)
>   
>   [----------] Global test environment tear-down
>   [==========] 29 tests from 4 test suites ran. (44 ms total)
>   [  PASSED  ] 29 tests.
>

**Comment by Ekopalypse** [comment]
Cloning the submodule did the trick and I can now compile and run tests.
Thank you
