### ISSUE TITLE
[Request] Make "Show Console" toggle the console

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#54]
Hello,

Could you make the "Show Console" command toggle the console visibility (and set the "checked" state accordingly)?

Thank you.

**Comment by Yaron10** [comment]
Another issue: if you close the console by pressing its Close button, `Show Console` remains "checked".

Thank you.

**Comment by ClaudiaFrank** [comment]
@Yaron10 - isn't the focus already handled? 
If you show the console the focus is in the "run area".
Now, only if don't do anything and hide the console there is no defined situation but
if you edit text or have character panel open and selected a char, the focus is set back to this control.
Doesn't this happen to you?

Hide console by using close button is solved.

**Comment by Yaron10** [comment]
> If you show the console the focus is in the "run area".

As expected.

> there is no "defined focus"

That can be discussed; but let's assume the editor should get the focus on closing the console.

> if you edit text or have character panel open and selected a char, the focus is set back to this control.
Doesn't this happen to you?

Unfortunately not.

STR:
Set focus to the editor (caret blinks etc.).
`Show Console`. 
`Show Console` again.

Result:
The editor does not get the focus.
***
>Hide console by using close button is solved.

:+1: 
Thank you.

You haven't committed the fix yet, have you?

**Comment by ClaudiaFrank** [comment]
>Set focus to the editor (caret blinks etc.).
>Show Console.
>Show Console again.

That's what I meant, but if you do
Show Console, edit or do something else with other docked windows and then Show Console 
it should put back the focus to the "last" control.

If you do Show Console - Show Console then, it doesn't.
But I see an issue here - how should one know whether this is a "double Show" or something 
other in between? The window belongs to npp. I'm open for any suggestions.

**Comment by Yaron10** [comment]
Let's refer to three NPP windows.

**Clipboard History**
This window is not "toggleable".
It gets the focus when opened.
On pressing its Close button, the editor always gets the focus (even if you switch to Clipboard History from the incremental-bar).

OK.

**Function List**
"Toggleable".
It does *not* get the focus when opened.
On pressing its Close button, the editor always gets the focus.
On pressing `Function List` again, the editor gets the focus only if you didn't manually set the focus to `Function List`.

That's a bug IMO.

**Folder as Workspace**
"Toggleable".
It gets the focus when opened.
On pressing its Close button, the editor always gets the focus.
On pressing `Folder as Workspace` again, the editor does not get the focus.

That's a bug IMO.

I'd suggest not to make it too complex: always set focus to the editor on hiding the console.
What do you think?

Thank you.

**Comment by ClaudiaFrank** [comment]
I guess I found a way to determine if this is a "double show" :-)
If doing ShowConsole the input is in the "run area" -> save this hwnd and check if
next ShowConsole still reports this hwnd. If yes - send focus to editor, else don't do anything.

**Comment by Yaron10** [comment]
Mid-air collision? :)

I realize this is more complex than I thought at first.
I do believe that always setting the focus to the editor would be fine.

As you understand.

**Comment by ClaudiaFrank** [comment]
Sorry, don't know this term (Mid-air collision) and google and leo.org don't know it too :-(
But I guess I thought way to complicated - that's the "run" hwnd - and this is owned by python script
so we should find a way to make it work with the discussed situation.

**Comment by Yaron10** [comment]
Mid-air collision: posting at the same time.

I don't fully understand your plan. I'm sure it would be clever. :)

**Comment by ClaudiaFrank** [comment]
Ahh - thx
Basically we do have two scenarios, 
1.) opening console, doing something with different windows in npp like editor etc... and then closing console ->we should not redirect the focus to the editor
2.) opening console and either do only actions within console dialog or nothing at all and then closing console -> we should redirect the focus to editor

What do you think?

**Comment by Yaron10** [comment]
Thanks for clarifying.

> 1.) opening console, doing something with different windows in npp like editor etc... and then closing console ->we should not redirect the focus to the editor

Not to the editor nor to any other element, correct?

As a user, I'd consider this behavior a bug.
If you don't switch back to the previously focused element, the editor MUST get the focus.

I'm quite sure the NPP behavior I've described earlier is not intentional but a bug.

**Comment by ClaudiaFrank** [comment]
No - we do not redirect but notepad++ does itself, whereas in the second case
we do redirect to the editor. 
First Case:
we do show console
-> result: focus is in the run window
we do edit text (or any other action in npp but NOT in console dialog)
we do another show console
-> result: focus in the last used control <- we don't need to do anything, Npp does it for us.

Second Case:
we do show console
-> result: focus is in the run window
we do do ONLY action in console dialog OR we don't do any action at all
we do another show console
-> result: focus in still in the run window <- we need to redirect to editor window

Makes this sense to you?

**Comment by Yaron10** [comment]
> First Case:
...
-> result: focus in the last used control <- we don't need to do anything, Npp does it for us.

Does it?
Let's refer to a simple case: the editor and Python console.
If you hide the console, does the caret blink in the editor? Can you scroll the document?

**Comment by ClaudiaFrank** [comment]
Yes

**Comment by Yaron10** [comment]
Do you mean this is the current behavior on your machine?

**Comment by ClaudiaFrank** [comment]
Yes, which makes me think it is not on your machine!?

**Comment by Yaron10** [comment]
Indeed. So this discussion is a serious misunderstanding. :)

**Comment by ClaudiaFrank** [comment]
Just built a x86 and it is working the same, no problem.

**Comment by ClaudiaFrank** [comment]
And I have the current master commits - nothing in addition

**Comment by Yaron10** [comment]
I'll download a fresh portable NPP, keep the original settings and test it.

**Comment by ClaudiaFrank** [comment]
OK - will await the results and if it isn't different then let's follow up on this later this day, already half past 3 ->

**Comment by Yaron10** [comment]
Great.

Thank you and good night.

**Comment by ClaudiaFrank** [comment]
Just for your info - https://imgur.com/a/pqpyEQA

**Comment by Yaron10** [comment]
Hello Claudia,

The following code might be helpful.

I've modified `case IDM_FOCUS_ON_FOUND_RESULTS:` in `NppCommands.cpp` to:
```
case IDM_FOCUS_ON_FOUND_RESULTS:
		{
			// Toggle FindResults window. See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/113 .
			if (_findReplaceDlg.isFinderVisible())
			{
				bool isFinderFocused = (GetFocus() == _findReplaceDlg.getHFindResults());
				_findReplaceDlg.hideFinder();
				if (isFinderFocused)
					switchEditViewTo(currentView());
			}
			else
				_findReplaceDlg.focusOnFinder();
		}
		break;
```
It's based on https://github.com/notepad-plus-plus/notepad-plus-plus/pull/113.

**Comment by ClaudiaFrank** [comment]
Changes should address the discussed points.

**Comment by Yaron10** [comment]
Thank you Claudia.
I'll wait for @chcg to merge your PR.

**Comment by ClaudiaFrank** [comment]
As Python Script is using appveyor ci you could use the artifacts as well.
This is the 32bit dll
https://ci.appveyor.com/project/bruderstein/pythonscript/build/1.1.0.48/job/f48m64q1ioodtdm8/artifacts

**Comment by Yaron10** [comment]
Claudia,

I've downloaded it from your fork.
Great work. Thank you.

If the console output has the focus, the problem is still there.

**Comment by ClaudiaFrank** [comment]
Which steps did you do?

**Comment by Yaron10** [comment]
Show Console.
Click somewhere in the console output.
 Show Console.

**Comment by ClaudiaFrank** [comment]
Ahh - not in the run field but in the scintilla component of the console - I see, confirmed.
Recently, it seems that I always have to do three iterations until something is done.

**Comment by Yaron10** [comment]
I've mentioned it in https://github.com/bruderstein/PythonScript/issues/54#issuecomment-393018248.

> But if the console has the focus (including the output), the editor does not get the focus.
So it's not only "Run"; if Python has the focus, you should make sure the editor grabs it.

After my misunderstanding your explicit STR yesterday, I have absolutely no right to "chirp". :)

> Recently, it seems that I always have to do three iterations until something is done.

It happens to the best. We still appreciate and love you. :)

**Comment by ClaudiaFrank** [comment]
Now, everything which you said yesterday makes more and more sense - I should have carefully read
and not ignoring that there is the OUTPUT area - I always thought we talked about the whole window itself.

>It happens to the best. We still appreciate and love you. :)

Thx :-)

Hopefully appveyor is clever enough to combine the two PRs - let's see.

**Comment by ClaudiaFrank** [comment]
Release builds finished successfully
https://ci.appveyor.com/project/bruderstein/pythonscript/build/1.1.0.49/job/nph7m6ys7fupu50x/artifacts

**Comment by Yaron10** [comment]
:+1:  :+1: 

Great. Thank you very much.

> Now, everything which you said yesterday makes more and more sense...

I thought the same about your comments. I just couldn't understand how I missed your STR.
