### ISSUE TITLE
Set console layout to LTR even if NPP layout is RTL

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#58]
A separate thread for a major issue mentioned in https://github.com/bruderstein/PythonScript/issues/20#issuecomment-383379039.
 
There's no point whatsoever in setting the console layout to RTL; the LTR output text in RTL layout is extremely confusing.

Thank you.

**Comment by ClaudiaFrank** [comment]
Is this still an issue?

**Comment by Yaron10** [comment]
Hello Claudia,

I wasn't able to build this repo at the time. :)
So it's still an issue and the most important one for my personal use (I'd like to clean up startup.py).

Thank you.

**Comment by ClaudiaFrank** [comment]
Reason why I'm asking - seems to do it already.

![grafik](https://user-images.githubusercontent.com/16170444/42038460-4cb9ed2a-7aeb-11e8-9a28-f5149e2d2526.png)

**Comment by Yaron10** [comment]
NPP in the screenshot is **LTR layout**; the editor's *text direction* is RTL.
To reproduce the problem, please select Hebrew as the interface language and restart NPP.

Thank you.

**Comment by ClaudiaFrank** [comment]
I see, better saw, - wip

**Comment by Yaron10** [comment]
Great. Thank you very much.

What's "saw"?

**Comment by ClaudiaFrank** [comment]
see - saw - seen (???)

**Comment by Yaron10** [comment]
I thought it was some abbreviation. :)
Thanks and best of luck.

**Comment by ClaudiaFrank** [comment]
So is it this what you want to have?

![grafik](https://user-images.githubusercontent.com/16170444/42055214-bc282f66-7b16-11e8-9e9b-1a863247300f.png)

and if it is, should we have another setting like `Force console window to LTR` ?

**Comment by Yaron10** [comment]
> So is it this what you want to have?

Indeed. :+1: 

> and if it is, should we have another setting like Force console window to LTR ?

IMO the extra setting would just bloat PS; I can't think of a case anyone would prefer "Python" to be RTL.

Thanks again.
