### ISSUE TITLE
NPP can not be activated while the Help-File is open

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#61]
STR:
Menu -> Configuration.
Click on NPP's tab in Windows Task Bar.

Result:
NPP is not activated.

Thank you.

**Comment by chcg** [comment]
@Yaron10  
Why Menu->Configuration?
Do you mean Plugin->PythonScript -> Context-Help? There are two windows stacked in this case  for win10 and one needs to be chosen.

**Comment by Yaron10** [comment]
> Why Menu->Configuration?

I typed "Configuration" in https://github.com/bruderstein/PythonScript/issues/20 a minute before writing that line and got it mixed up. Sorry.

Thanks for the explanation. I appreciate it.

**Comment by Yaron10** [comment]
Hello @chcg,

Allow me another question:
Running `PythonScript.chm` from `Menu -> Run`, it is possible to switch between NPP and the help file.
Does the *`Context-Help`* make the difference?

Thank you.

**Comment by chcg** [comment]
@Yaron10 
I think in case of calling it from `N++ Menu -> Run` it is like calling the chm from the explorer or command line as a separate windows process which has no knowledge of the calling application. In case it is called from the plugin menu `Context-Help` it is a subprocess of N++.

What exactly do you mean with switch?

**Comment by Yaron10** [comment]
@chcg,

> What exactly do you mean with switch?

When launching `PythonScript.chm` via `Python Script -> Context-Help`, I can not return to NPP unless I close the help file.
Is that the expected behavior?

> I think in case of calling it from N++ Menu -> Run it is like calling the chm from the explorer or command line as a separate windows process which has no knowledge of the calling application. In case it is called from the plugin menu Context-Help it is a subprocess of N++.

I assumed that was the case.
But the current behavior on my machine is so weird that it made me wonder if I my first post here was understood correctly. 

Thanks for replying. I appreciate it.

**Comment by Yaron10** [comment]
@sasumner,

> When launching `PythonScript.chm` via `Python Script -> Context-Help`, I can not return to NPP unless I close the help file.

Is that the behavior on your machine too?

Thank you.

**Comment by sasumner** [comment]
@Yaron10 
I don't see that behavior; using PS 1.2.0.0 I can return to N++ as normal after invoking the help as you describe, and leaving it open as I click back in an N++ editor tab.

**Comment by Yaron10** [comment]
@sasumner,

Thank you for testing it and replying. I do appreciate it.

I've just found out that clicking on the *help-file's tab* (in Windows Task Bar) activates NPP.
(The help-file's tab toggles between help and NPP).

I use [QTTabBar](http://qttabbar.wikidot.com/) which might be the cause to this behavior.
**I don't have this problem with other apps opening their help files; so it might be a good idea to review the relevant code in PS.**

**Comment by Yaron10** [comment]
@sasumner,

> My 2c, I would disable QTTabBar and test it that way.

:+1:
 
I get the same behavior after disabling QTTabBar.
But properly testing it would require uninstalling QTTabBar and manually modifying/restoring some registry entries.
This is quite a task and I might do it later. I'll re-close the issue for the time being.

Thanks again for your help.
