### ISSUE TITLE
[Enhancement] Separate outputs with an empty line

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#68]
![default](https://user-images.githubusercontent.com/10229320/40842885-eff7dbd0-65b7-11e8-8618-de92a737315f.png)

vs.

![default](https://user-images.githubusercontent.com/10229320/40842914-ff991270-65b7-11e8-8f65-6f4d51cd514c.png)

Thank you.

**Comment by sasumner** [comment]
I see the empty lines in the top image, but the bottom image doesn't really relate to the content of the top image so I am confused about what is really wanted here?

**Comment by Yaron10** [comment]
Simply add an empty line after each output segment.

At the top image it's instantly clear there are three different segments.
Looking at the bottom image you see "one block".

Setting the command's foreground color to blue would make the output even clearer IMO.
That is:
>>> Command [in blue]
Result [in black]

**Comment by sasumner** [comment]
The top image seems to be initialization?  Once initialization is over, then things that happen in the console look like the bottom image, so there's no extra spacing needed?  If code writes to the console it could/should put its own spacing in when it is done.  Otherwise, is this feature supposed to "watch" code and if it writes anything at all to the console, this feature should add an empty line when the code has finished (and if the code hasn't written anything then no empty line should be added?).

**Comment by Yaron10** [comment]
Currently a single `\n` is inserted after each output.
My suggestion is to insert `\n\n` for a better clarity.

**Comment by ClaudiaFrank** [comment]
To be honest, I think this is something for userdefined startup.py files
Something like

```
class ModifiedConsoleOut:
    def __init__(self):
        global console
        self._console = console;

    def write(self, text):
        self._console.write(text+'\n');

sys.stdout = ModifiedConsoleOut()
```

**Comment by Yaron10** [comment]
@ClaudiaFrank,

I'd like to make sure we understand each other correctly.

If you run `editor.getCurLine()` 5 times, this is the output:
```
>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'
>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'
>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'
>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'
>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'
```
Wouldn't it be much clearer like this?
```
>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'

>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'

>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'

>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'

>>> editor.getCurLine()
'// Note that the GPL places important restrictions on "derived works", yet\r\n'
```
***
```
class ModifiedConsoleOut:
    def __init__(self):
        global console
        self._console = console;

    def write(self, text):
        self._console.write(text+'\n');

sys.stdout = ModifiedConsoleOut()
```
Does not achieve that.

```
console.editor.setExtraAscent(2)
console.editor.setExtraDescent(2)
```
Increases the spacing between *all lines* but does not separate the different segments.

Thank you.

**Comment by ClaudiaFrank** [comment]
So you are looking for solution just for the output generated by commands execute via the "run area", correct?

**Comment by Yaron10** [comment]
Indeed.

**Comment by Yaron10** [comment]
Allow me a correction.

I was initially thinking about outputs generated after using the console input.
But actually any console output not initiated directly by the user - PS should make sure to insert an empty line and separate its messages.

That is:
If `console.write()` is used in a script, the user can add as many `\n` as they want.
However, error messages generated by PS (e.g. wrong syntax in a script) should be separated by an empty line.

It's not that important for my personal use.
If you don't think it's a worthy enhancement, please let me know and I'll close the issue.

Thank you.

**Comment by ClaudiaFrank** [comment]
Actually I like your approach, unfortunately it looks like it isn't that easy to implement it reasonably well.
Currently I only found the way to add

`textToWrite.append((textToWrite != "\n") ? "\n" : "");`

to `void PythonConsole::writeText(boost::python::object text)` before GILRelease and only for normal output.
Error output is sent in multiple text so that nearly each line does get an additional extra EOL.

**Comment by Yaron10** [comment]
Thank you Claudia.

Should I close the issue or you'd like to keep trying?

**Comment by sasumner** [comment]
I suppose the one thing I don't care for about this is I would have to devote more screen real estate to my PS console window to see the same amount of information.  I like keeping my editor tab area as large as possible for obvious reasons, so while I like having other things (consoles, find results, clipboard history panel, etc) viewable, they are secondary and I like them to be as compact as possible.  My 2c.

**Comment by Yaron10** [comment]
@sasumner,

I see your point.
I suppose a user-preference can set this behavior.
***
What do you think about the following suggestion?

Setting the command's foreground color to blue would make the output even clearer IMO.
That is:
>>> Command [in blue]
Result [in black]

**Comment by sasumner** [comment]
@Yaron10 I have no objection to that.  I don't know that I hear about that and think "wow" that would really be great, but sometimes I have to actually experience things before I realize how much I missed them before.  :)

**Comment by Yaron10** [comment]
@sasumner,

It was supposed to be a good minor enhancement. :)

**Comment by Yaron10** [comment]
> Setting the command's foreground color to blue would make the output even clearer IMO.
That is:
>>> Command [in blue]
Result [in black]

If ever implemented, the following should be better.
>>> Command [in black] (current behavior)
Result - no error [in green]
Error [in red] (current behavior)

**Comment by chcg** [comment]
Available current styles see:
https://github.com/bruderstein/PythonScript/blob/77a365bd1ffa4b31f0d174b67077c8c35b1074b2/PythonScript/src/ConsoleDialog.cpp#L468-L506. 
Needs probably something like ConsoleDialog::writeError() with a newly defined style for the python result output and the appropriate calls in the right places.

**Comment by ClaudiaFrank** [comment]
What I do have atm is, introducing a new style 8 which is configurable via, for example,
SETTING/COLORIZEOUTPUT/1234567
where 1234567 is the color and non-existance of the string or value less than 0 is disabling this feature.

![grafik](https://user-images.githubusercontent.com/16170444/41346736-ca85a0d6-6f07-11e8-9348-60ca63e64df4.png)

Additional line breaks as well as the "open console on error" does not yet work as expected.

**Comment by Yaron10** [comment]
Claudia,

It looks great. I appreciate your work.

Does it mean that *any* `console.write()` should use the preset color?
Would it be complex to differentiate between general output (e.g. `Initialisation took... Ready.` ) and a result (correct: green; error: red)? 
***
> Additional line breaks as well as the "open console on error" does not yet work as expected.

Thank you and best of luck.

**Comment by ClaudiaFrank** [comment]
Ok this is the current state and before making the pr I wanted to ask if this is what can be accepted
@Yaron10 , I guess this answers your question as well, doesn't it.

![grafik](https://user-images.githubusercontent.com/16170444/41384679-833d703a-6f77-11e8-81ce-ad430ef35310.png)

Only the statements execute from within console dialog can get an additional eol or can be colored.
Console dialog can be configured to open upon python error
The way to achieve the same for external programs should be done via console.run and user defined pipes.

Sorry for having two feature request bundled in one, but my first assumption that stdout and stderr
can be used to solve both request was wrong as those objects are only useable with external programs.

**Comment by Yaron10** [comment]
Hello Claudia,

I couldn't reply earlier. Sorry.

> Only the statements execute from within console dialog can get an additional eol

Do you mean "currently" or is it your final conclusion?
Anyway, the additional EOL is configurable (for our friend @sasumner), correct? 

> Only the statements execute from within console dialog can be colored.

That's perfectly fine.

> Console dialog can be configured to open upon python error 

:+1: 
Could you flash the Python window if it's already open (like NPP flashes the Find Dialog if the search-term is not found)?

Thank you for your great work. I appreciate it.

**Comment by sasumner** [comment]
>Could you flash the Python window if it's already open?

Flash **ONLY** the Pythonscript console window?  Not sure I've seen that effect in any program; not sure how hard that would be; but if anyone can do it CF can!

What is the definition of "open"; perhaps you mean "open and visible" (I have PS console and the *Find result* panel as tabs in a shared subwindow docked at bottom of N++).  PS console is always "open" but not always "visible" (well, its tab is always visible).

**Comment by Yaron10** [comment]
> Flash ONLY the Pythonscript console window? Not sure I've seen that effect in any program;

 NPP flashes the *Find Dialog* if the search-term is not found.

>  perhaps you mean "open and visible" (I have PS console and the Find result panel as tabs in a shared subwindow docked at bottom of N++). PS console is always "open" but not always "visible" (well, its tab is always visible).

I remembered that case well and intentionally used the term "open".
Switching from "Find Results" to "Python", the window should be flashed as well.

**Comment by sasumner** [comment]
I didn't make it clear when I said "not sure I've seen that effect in any programs"...maybe what I should have said is I haven't seen the effect of flashing a subwindow of a docked window.  Certainly I understand if we are discussing a free-floating PS console window (much like the Find window is independent).  Maybe it is the same either way.  I guess I won't know until I see it working...or I mock up something with ctypes...  :)

Regardless, I think I see what you mean now; it seems consistent and good.  :)

**Comment by Yaron10** [comment]
In terms of design I don't see a substantial difference between the Find Dialog and a docked window.
I haven't tried to implement it though. We're discussing it freely and leaving the hard work to Claudia. :)   

> Regardless, I think I see what you mean now; it seems consistent and good.

I'm glad you agree.

**Comment by ClaudiaFrank** [comment]
Yes, new functions/settings would be configurable via cnf file and probably via configuration menu
and yes, I haven't found a reliable way to add an extra eol if the output is generated via script and
using print or console.write/writeError function but to be honest. If one uses print or console.write/writeError then it could be easily achieved by adding an eol in front of the string.

For me it is not clear under which condition it should be flashed and just a question,
isn't adding additional text not some kind of "flashing" already? 
I mean, if the window is docked you won't see the taskbar flashing as it doesn't belong to python script window and if you detach it we don't see a second taskbar icon as well so you only would get notified
with a "flash" if the window is actual visible and in such a case, I ASSUME, that adding text to console window is also some kind of "flash"
Or do I miss something?

**Comment by Yaron10** [comment]
> Yes, new functions/settings would be configurable via cnf file and probably via configuration menu

:+1: 
Great. Thank you.

> but to be honest. If one uses print or console.write/writeError then it could be easily achieved by adding an eol in front of the string.

I was not referring to those outputs but rather to Python Script's generated messages.
That is: insert an empty line between two consecutive syntax-errors (for example).

> isn't adding additional text not some kind of "flashing" already?

If "Python" is visible, it is to some degree; not enough as an alert IMO. 
If "Python" is not visible (Scott's case: "Python" and "Find Results" are both open and "Find Results" is visible), we don't have even that.

> I mean, if the window is docked you won't see the taskbar flashing...

I was suggesting to flash Python's title bar.

Thanks again. I appreciate it.
