### ISSUE TITLE
[Enhancement] Add "Input History" navigation buttons to Console

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#69]
Currently the only way to navigate through "Input History" is via the Up/Down arrows.

1. New users may not be aware of this functionality.
2. "Mouse-Oriented" users would prefer navigating with the mouse.

How about adding `<<` and `>>` buttons to the console?
A ComboBox/Drop-down List would be even better.

Thank you.

**Comment by Yaron10** [comment]
What's wrong with being the first?

**Comment by sasumner** [comment]
Nothing wrong with being a trailblazer.  However I think that other consoles don't have this functionality because it isn't necessary; anyone that has used any console understands up and down arrows for command recall after a short period of using their first console.  That being said I wouldn't vehemently oppose (hah! not like my opinion means anything!) GUI elements for this as long as the window real-estate was minimal.  In other words, for me, if it makes my PS console window have increased vertical size, I don't like it at all.  :)

**Comment by Yaron10** [comment]
Would a `History` drop-down button be too much?
And if it was placed under the `Run` button (slightly decreasing its height)?

If you don't like it, I'll retract my request and close this issue.

**Comment by sasumner** [comment]
@Yaron10 , thanks for your politeness but I am just offering up what I think.  If someone considers implementing this I would think they read all of this and consider all opinions (I think that is the point of being able to comment).  So in no way do I think you should retract your request.  :)

**Comment by Yaron10** [comment]
@sasumner,

Your politeness is appreciated too.

Here is another option taking the "real estate" into consideration: make "Run" a split-button displaying history on pressing its arrow.
And `>>>` can be replaced with `>`. So you might end up with more "real estate". :)

**Comment by Yaron10** [comment]
A simpler and easier to implement solution would be processing WM_MOUSEWHEEL: wheel up/down should cycle through history just like arrows up/down.

Replacing the EditBox with a ComboBox would be better but slightly more complex to implement.

NPP has a generic `addText2Combo()` in `FindReplaceDlg.cpp`.
```
void addText2Combo(const TCHAR * txt2add, HWND hCombo)
{
	if (!hCombo) return;
	if (!lstrcmp(txt2add, TEXT(""))) return;

	auto i = ::SendMessage(hCombo, CB_FINDSTRINGEXACT, static_cast<WPARAM>(-1), reinterpret_cast<LPARAM>(txt2add));
	if (i != CB_ERR) // found
	{
		::SendMessage(hCombo, CB_DELETESTRING, i, 0);
	}

	i = ::SendMessage(hCombo, CB_INSERTSTRING, 0, reinterpret_cast<LPARAM>(txt2add));
	::SendMessage(hCombo, CB_SETCURSEL, i, 0);
};
```
Claudia, Scott,
What do you think?
***
Why should the input field be cleared after "Run"? - I often want to run the same string again.
If you want to allow the user type a new string, keep the previous one and select it.

**Comment by sasumner** [comment]
@Yaron10 you certainly provided some real-estate-free options (mouse-wheel, drop-down combobox).  Neither would bother me, but remember, I think the current up/down arrow key thing like on every other console in existence is the ultimate for this type of thing.

I can't agree with the input field retaining its value but selected...just too annoying visually...and really unnecessary (when an up-arrow press recalls it).  But....I certainly wouldn't complain if others like the idea.

**Comment by Yaron10** [comment]
Hello Scott,

Thanks for replying. I appreciate it.

I thought you might oppose a ComboBox. I'm glad you don't. :)

> I think the current up/down arrow key thing like on every other console in existence is the ultimate for this type of thing.

You could still use the arrows with a ComboBox. Why force "mouse-oriented-users" use the keyboard?

> I can't agree with the input field retaining its value but selected...just too annoying visually...and really unnecessary (when an up-arrow press recalls it). But....I certainly wouldn't complain if others like the idea.

OK. Let's wait for @ClaudiaFrank's opinion.

**Comment by sasumner** [comment]
>Why force "mouse-oriented-users" use the keyboard?
Ah ha!  It's finally been said explicitly!  :)  The base nature of the `>>>` prompt is that you use the keyboard at it.  Given that, going to the mouse for anything related to this is unnatural, when the up/down arrow keys are so accessible (you're already at the keyboard).  Note that I'm not a keyboard purist at all (I like the mouse...for useful mousey things,,,).  But again, I'm not going to complain, unless someone wants to take away my up/down arrow capability here (and I'm not worried at all that they do).

**Comment by Yaron10** [comment]
I agree that most of the time you should use the keyboard. But often - for short tests - I find it much more convenient to use the mouse.

Sure, no change without your explicit approval. :)

**Comment by ClaudiaFrank** [comment]
@Yaron10 
I'm a keyboard junkie - so I don't really care about mouse functionality and Scott knows this :-)
Which way of drop down functionality you are looking for.
Something like in the find dialog or just two buttons (up/down) like you normally have when you
want to increase/decrase numerical values?

**Comment by ClaudiaFrank** [comment]
Yaron, once we know how it should look like an addition if statement to check if it should be retained or not
is easy to implement. 
Q: The edit control is at the bottom so opening a combo box should always open upwards and the most recent entry should be next to the edit control, so going from bottom to top in
combo box list means getting older and older entries, right?

>What are the Download/Upload icons?

see https://github.com/bruderstein/PythonScript/issues/15
Just a test to see if it works.

**Comment by Yaron10** [comment]
> once we know how it should look like an additional if statement to check if it should be retained
or not is easy to implement.

Great. :+1: 

> The edit control is at the bottom so opening a combo box should always open upwards

If the combo contains two/three items it might open downwards.
If NPP is not maximized, the combo may contain many more items and still open downwards.
So IMO the expected behavior is always having the recent item at the top.

Many thanks.
***
> see #15
Just a test to see if it works.

Thanks and best of luck.

**Comment by sasumner** [comment]
I agree that a dropdown (or dropup?) is best here.  The most recent entry should be closest to the `>>>` box, so if it drops down that would mean that the top/first entry in the box would be most recent...but if it drops up then the bottom/last entry in the box would be the most recent.  Hmmm...maybe this makes sense, maybe not.  And maybe Windows handles it automagically based upon screen positioning? Maybe that is too much to hope for.

Drop-down is going to be always preferrable, if it can be done (if there is real-estate to drop it downward), because that way it won't cover the rest of the PS console (maybe what is on the console is needed to be seen...impacts what you'd choose next from the dropdown).  I suppose this presumes that everyone likes the PS console at the bottom of their N++ window (I do, seem to recall CF doesn't...).

Is the box going to be droppable with a keystroke (note: can't use down-arrow for this like the Find-what box in the Find window!)

...and BTW I kinda liked the original idea for this feature to use the mouse wheel...but probably combobox IS better...

**Comment by ClaudiaFrank** [comment]
I need to play with comboxes just to see what can or can't be done.
Scott, as far as I understand standard comboboxes at the moment, 
the mouse can be used as long as you don't open the list part - like in find dialog
but may I ask what you mean by droppable with keystroke and that you can't use arrow key?

Do you have the arrow key reassigned or is it just not working for you (for me it is)?
If you have it reassigned, which key do you use atm to jump through the history?

Ja, I don't like it at the bottom and to be honest, I would prefer a different solution without an attached
run dialog - just to have the console  window being an output window and if there is a need to execute
a console command then it should pop up in the middle of my document. Something like this

![grafik](https://user-images.githubusercontent.com/16170444/42943364-d4c235b0-8b62-11e8-8dfd-5e76044e06d6.png)

**Comment by sasumner** [comment]
>but may I ask what you mean by droppable with keystroke and that you can't use arrow key?

In the find-what box of the Find window, a down-arrow press drops down the box...in the PS console window, a down press needs to do normal console behavior...recalling command history as normal...not dropping a box.  Remember that the dropdown shouldn't even feel like it is there for those that choose not to use it.  So what I meant is for non-mouse junkies to have a keyboard way to drop down this proposed box.  Since "down" is not an option, perhaps "ctrl+down" would open the combobox in order to see its entries? I'm good with anything that makes sense here (e.g., some combo of modifiers along with "down" arrow, in all likelihood).

>Do you have the arrow key reassigned or is it just not working for you (for me it is)?

Don't understand the question...not reassigned...works fine right now (but we were debating how it might work AFTER this proposed change...)

>should pop up in the middle of my document.

I think that's fine.

**Comment by ClaudiaFrank** [comment]
> In the find-what box of the Find window, a down-arrow press drops down the box.

Ok, this seems to be the confusing part as this doesn't happen to me, instead a down-arrow key press 
selects the next item but does not open the box.

**Comment by sasumner** [comment]
>instead a down-arrow key press selects the next item but does not open the box.

Oh, gosh, you are so totally right....sorry, sorry, sorry, how could I have been so wrong?

But this begs the question, what keycombo DOES or SHOULD open the box?  Probably a standard windows thing but I don't know it.

This discussion is about the find-what box but presume a PS console dropdown should work same...

**Comment by ClaudiaFrank** [comment]
Afaik, alt+down arrow

**Comment by Yaron10** [comment]
> And maybe Windows handles it automagically based upon screen positioning?

Indeed.

> so if it drops down that would mean that the top/first entry in the box would be most recent...but if it drops up then the bottom/last entry in the box would be the most recent.

https://stackoverflow.com/questions/9192096/how-to-check-if-combobox-drop-down-list-is-revealed-up-or-down

Scott, don't you think it would be *highly confusing* if the order changed on adding one more item?
(Assuming it drops down with 4 items and up with 5 items).
***
I was about to refer Scott to [this](https://docs.microsoft.com/en-us/windows/desktop/controls/cb-getextendedui) article.

> But this begs the question, what keycombo DOES or SHOULD open the box? Probably a standard windows thing but I don't know it.

F4 or Alt+Up/Down arrows.

**Comment by ClaudiaFrank** [comment]
Yaron, the number of items should be the same but I was suggesting something like this

```
       ...
       3rd entry
       2nd entry
       1st entry
>>>
       1st entry
       2nd entry
       3rd entry
       ...
```

**Comment by Yaron10** [comment]
Scott,

I understand that.
But if you have 3 items and it drops down, you'll get:
```
      Scott
      Claudia
      Yaron
```
Now if you add another item and it pops up, you'll get: 
```
       PS
       Yaron
       Claudia
       Scott
```
The user may have to "recalculate" quite often which is the last entry.

Also, the implementation is seemingly complex.
But I guess that would be a nice challenge for Claudia. :)

**Comment by ClaudiaFrank** [comment]
Ähheemmm - maybe I should wait for Scott to answer in my name then :-)

**Comment by Yaron10** [comment]
The "Confused" was a mere confusion. :)

**Comment by ClaudiaFrank** [comment]
Of course every new item added should always result in the exprected behavior,
like you said, having an list of Scott, Claudia, Yaron, being Yaron the first
and Scott the last recent one  command used, and adding a new command PS should result
in 

```
       Yaron
       Claudia
       Scott
       PS
>>>
       PS
       Scott
       Claudia
       Yaron
```

But just to be clear - I don't mind as I probably won't use this function at all.
So it is up to you both or whoever might jump in and decide how it should be done.

**Comment by Yaron10** [comment]
Claudia,

If you enter A, B, C and it drops down, it looks as follows:
![default](https://user-images.githubusercontent.com/10229320/42958813-514d1510-8b8f-11e8-8c23-61c5ded0eb4f.png)

If you then add D, E and it pops up, it looks as follows:
![default](https://user-images.githubusercontent.com/10229320/42958859-758ff69a-8b8f-11e8-9d83-d367ada9a352.png)

This is the standard Windows behavior and IMO it shouldn't be changed.

*The order in my previous post was an illustration to Scott's suggestion.*

Scott,
Claudia has kindly delegated the decision to us. :)
What do you think?

Claudia,
Thank you very much.

**Comment by sasumner** [comment]
Thanks for cluing me in on alt+down!

My thinking was that the drop-up case should be different but I don't wanna go violating any windows standards!  :-)

If we are looking for standards to follow, maybe lean towards what happens when you press F7 at a good old CMD.EXE prompt...the most classic of consoles (on windows), which brings us back to CF's suggestion of a bit ago:

![image](https://user-images.githubusercontent.com/30118311/42962884-af4d52a8-8b60-11e8-9858-981d8f057122.png)

:-D

**Comment by Yaron10** [comment]
> My thinking was that the drop-up case should be different (like CF's 321-123 example) but I don't wanna go violating any windows standards! :-)

I don't really care about Windows standards, but in this case I believe it should be better. 

> Ja, I don't like it at the bottom and to be honest, I would prefer a different solution without an attached
run dialog - just to have the console window being an output window and if there is a need to execute
a console command then it should pop up in the middle of my document. Something like this
...
If we are looking for standards to follow, maybe lean towards what happens when you press F7 at a good old CMD.EXE prompt...the most classic of consoles (on windows), which brings us back to CF's suggestion of a bit ago:

How about making that optional? - Keep the current design (+ combo) and have an option to open a "floating input".
If that's too much, implement what you prefer; I'm not a console heavy-user as you both are.

**Comment by sasumner** [comment]
My 2c is that too much configurability is annoying.  Probably should just select a winning design and roll with it.  :)

**Comment by Yaron10** [comment]
So you'd go for the "floating input"?

**Comment by sasumner** [comment]
I'd go for any design...let's go with yours since you care the most...if CF (or whomever) is willing to implement.  I've enjoyed the engaging discussion...sorry for my earlier factual errors....bad day. :)

**Comment by Yaron10** [comment]
> since you care the most...

Thank you.
But as I wrote - you both use it much more than I do.
Trying to be objective though, other users may not like the "floating input" either.

> sorry for my earlier factual errors.

Do you mean the arrows functionality?
Come on! It happens to all of us every day. :)

**Comment by sasumner** [comment]
I think you were in favor of the combobox approach and I think that is fine.  I just brought up what CMD.EXE does in case someone jumped in with YES, THAT'S HOW IT SHOULD BE.

I think the feature itself will be helpful to newbies and I'm sure I will also use it occasionally.

**Comment by sasumner** [comment]
>I hope you mean the combo

EITHER way.  :-)

Combo, working the way you suggested, has the advantage of commonality with the "find".  I vote for it, if this is a democracy.  :)

**Comment by Yaron10** [comment]
Thanks. :)

**Comment by sasumner** [comment]
If it is going to work like the Find-what's combo/edit box, I have a question about THAT functionality.  

I've noticed that when I am in that box and I press the down arrow, what is retrieved and put in the edit box is actually one item BELOW what I think should be recalled there.  A simple up arrow press then gets me what I want, but I'm fairly certain that the first press of down arrow should have done it.

Dropping down the box shows the entry I got as the second one from the top, with the first entry from the top being the one I wanted and expected.

Anyone else ever see this?  I ask here because while duplicating the overall functionality for the PS console window would be great, let's not bring along any "weirdness"...

Here's a specific sequence of events I observed:  After just starting N++, I call up the Find window.  Find what field is empty, I press down arrow.  I get "CHARADDED" there but I expected "print".  Dropping down the box shows:

![image](https://user-images.githubusercontent.com/30118311/43005257-54c39482-8c00-11e8-94f4-ffb6614a7f5a.png)

**Comment by ClaudiaFrank** [comment]
No - I don't see that behaviour.
I can only replicate it if I search for **CHARADDED** then I search for **print** - close find dialog.
Put cursor to word **CHARADDED** or select word **CHARADDED** and open find dialog.
But that is expected behavior, isn't it?

**Comment by Yaron10** [comment]
Scott,

NPP calls `addText2Combo()` only after a button (Find, Count etc.) has been pressed.
So, as Claudia has mentioned, the following must have been your steps.

1) CHARADDED in the box.
2) Button pressed (-> CHARADDED added to the list).
3) print in the box.
4) Button pressed (-> print added to the list *before CHARADDED*).
5) CHARADDED in the box (*no button pressed* -> CHARADDED is the EditBox value but in the *list* it appears second).

**Comment by sasumner** [comment]
Okay it appears to be something I was doing wrong.  I had some (old) automation code clearing out the find what box (I suppose at one time it annoyed me if my last search term popped up there, even if I invoked the find while my caret was in whitespace--but actually a recent Community posting by CF has finished convincing me that this is OK--since the text is selected and is wiped out by just typing something new).

So since N++ thought that the last term was already in the box (even though the automation had erased it), of course a down arrow press at that point retrieves the NEXT lower remembered search term.  Anyway, not an issue and not going to be one for PS console.  Sorry to have bothered y'all.

**Comment by Yaron10** [comment]
Scott,

I'm glad you've figured that out.

Apropos: using the up/down arrows in a combo, the text in the EditBox is selected; would you like to change that?

Claudia,
Would placing the input on top (i.e. switching the output/input positions) be more convenient to you?

**Comment by sasumner** [comment]
It seems okay to me that edit/combo text is selected when one arrows up/down...

Is this what your question to Claudia implies?
![image](https://user-images.githubusercontent.com/30118311/43018955-56f96ff0-8c29-11e8-9e30-0fa8fa39f658.png)

**Comment by Yaron10** [comment]
> It seems okay to me that edit/combo text is selected when one arrows up/down...

Great.
Do you still want the input field to be cleared after "Run"? Or having the Find Dlg behavior would be fine?

> Is this what your question to Claudia implies?

Yes. What do you think?
I don't know if it would be better for Claudia.

**Comment by ClaudiaFrank** [comment]
I really have no preferences.

**Comment by Yaron10** [comment]
Claudia, 
No "floating input"? why? :)

**Comment by sasumner** [comment]
Find dlg behavior is good with me.

I don't think it would be fair just to move the prompt to the top of the console.  I'd think it would have to be a preference.

**Comment by Yaron10** [comment]
Scott,

Thanks.

> I don't think it would be fair just to move the prompt to the top of the console. I'd think it would have to be a preference.

I understand it's not important to Claudia. So no move to the top.

**Comment by ClaudiaFrank** [comment]
> No "floating input"? why? :)
Too much hassle - then either this is not working or that ... and I'm not a big fan of having multiple
solution for a task doing one simple thing.

**Comment by Yaron10** [comment]
Claudia,

Thanks.
You're the boss. :)

**Comment by ClaudiaFrank** [comment]
Noooo - I'm the typing slave :-)
So, do we have an outcome?

**Comment by Yaron10** [comment]
Should we start a "Free Claudia!" campaign?

If no "floating input", a combo; no extra setting if I understated Scott correctly. 

Thank you so much.

**Comment by ClaudiaFrank** [comment]
So implementation will be similar to find dialog - ok.
Once I have the #15 and #96 done - this is the next on the list.

**Comment by Yaron10** [comment]
Great.
Best of luck with all the issues. :)

**Comment by ClaudiaFrank** [comment]
@Yaron10 - wuld you mind testing with one of the artifacts from [this build](https://ci.appveyor.com/project/bruderstein/pythonscript/build/1.2.0.81) ?

Thx
Claudia

**Comment by Yaron10** [comment]
Hello Claudia,

:+1: 
Great work. I do appreciate it.

With your permission, some comments:
1) The EditBox (element in the combo) is cleared after a statement has been run. Is that intentional? (Scott has agreed to keep the string :) ).
2) If you open the list and press Enter, the selected statement is run immediately. 
It's actually not bad at all, but I'm not sure it's the standard expected behavior.
(- If you select a string with the mouse, the list is closed and then you need to Enter/Run).
Allow me to ask again: Is that intentional? - If not, I don't understand why this happens.
(`CB_GETDROPPEDSTATE` indicates whether the list is open or not).

And some cosmetic comments:
1) Could you pleas change `IDC_COMBO1,25,156,125,25` to `IDC_COMBO1,25,156,125,50` (25 -> 50)?
It should only change the *empty list* initial height. 
2) The position (top) of the combo is better than that of the previous EditBox.
But `>>>`'s top should be lowered and `Run`'s top and height should be changed; could you please try `"Run",IDC_RUN,152,156,40,13`? - It's base on other combos I've tried.

![default](https://user-images.githubusercontent.com/10229320/43742290-0e4397d6-99da-11e8-96e2-9311ea93a56f.png)

![default](https://user-images.githubusercontent.com/10229320/43742316-2ccb3952-99da-11e8-8149-15ba0a8ac03a.png)

3) @chcg's improvements to the Configuration Dlg (rc file) should be re-committed. :)

Thank you.

**Comment by ClaudiaFrank** [comment]
Hi Yaron, I have no idea why this rc file is always in the wront state,
I even rebased to the current upstream before working on that.
Next commit SHOULD have the improvments again.
Concerning >>> position, I gave up placing the controls - it always looks crappy to me.
Maybe I should by a new pair of glasses.

1. + 2. are intentional but as I don't have any preferences I will change to whatever you want as long
as I'm able to do it.

**Comment by Yaron10** [comment]
> Next commit SHOULD have the improvments again.

:+1:  :)

> Concerning >>> position, I gave up placing the controls - it always looks crappy to me.

This can certainly be annoying. 

`IDC_COMBO1,25,156,125,50`.
`"Run",IDC_RUN,152,156,40,13` (156 to have same the top as the combo; 13 to have the same height).
`">>>",IDC_PROMPT,7,160,17,11` (or 159?).

Could you please upload a screenshot of the `>>>` on your machine?
I don't have the repo and I haven't tested it.

> 1 and 2 are intentional but as I don't have any preferences I will change to whatever you want as long
as I'm able to do it.

Great.
I've just had a look at https://github.com/ClaudiaFrank/PythonScript/commit/38d7c74365b26e4bf9c10f6297cbf5441e10cb16.
Removing `SetWindowText(m_hInput, _T(""));` should fix `1`, correct?
Is `2` related to sub-classing the EditBox? 
You can use `CB_GETDROPPEDSTATE` to handle Enter if the list is open.

Thank you very much.

**Comment by ClaudiaFrank** [comment]
> ">>>",IDC_PROMPT,7,160,17,11 (or 159?).

I change the value even to 150 and it didn't do anything

![grafik](https://user-images.githubusercontent.com/16170444/43745496-5162b63c-99df-11e8-9233-a2f5a57959c2.png)


1 - yes but it leaves the last command selected (can't be seen in screenshot)
2 - yes, to use the enter/return key it is needed to subclass the edit control.

**Comment by ClaudiaFrank** [comment]
left one is within the resource designer and right picture what it looks like when running in real

![grafik](https://user-images.githubusercontent.com/16170444/43745562-bc27d83a-99df-11e8-9dfc-f67fb582124b.png)

**Comment by Yaron10** [comment]
> Oh Lord, totally forgot about this

:+1: :+1: 

> 1 - yes but it leaves the last command selected (can't be seen in screenshot)

That's good, isn't it?

> 2 - yes, to use the enter/return key it is needed to subclass the edit control.

Personally I don't care about `2`. What do you think?

Thank you.

**Comment by Yaron10** [comment]
> to use the enter/return key it is needed to subclass the edit control.

Can't it be achieved with `case IDOK:`?

**Comment by ClaudiaFrank** [comment]
Don't understand your question, IDOK is an command identifier of dialog box,
like IDCANCEL, IDABORT etc... - how is this related to the VK_RETURN key?

**Comment by Yaron10** [comment]
Could you please have a look at the following block in FindReplaceDlg.cpp?

```
case IDC_INCFINDPREVOK:
case IDC_INCFINDNXTOK:
case IDOK:
```

**Comment by ClaudiaFrank** [comment]
Do you mean, instead of subclassing the edit control we should check if the combox gets an WM_COMMAND and WPARAM being an IDOK message?

**Comment by Yaron10** [comment]
Indeed.

**Comment by ClaudiaFrank** [comment]
Need to test - means your current open points do stay open a little bit longer :-)

**Comment by Yaron10** [comment]
Great. :)
Thank you and best of luck.

LOWORD(wParam).

**Comment by ClaudiaFrank** [comment]
Does not look good

```
>>> print 1
Traceback (most recent call last):
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\code.py", line 265, in push
    more = self.runsource(source, self.filename)
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\code.py", line 76, in runsource
    code = self.compile(source, filename, symbol)
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\codeop.py", line 168, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\codeop.py", line 82, in _maybe_compile
    code = compiler(source, filename, symbol)
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\codeop.py", line 135, in __call__
    if codeob.co_flags & feature.compiler_flag:
KeyboardInterrupt
>>> print 1
1
>>> print 2
Traceback (most recent call last):
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\code.py", line 265, in push
    more = self.runsource(source, self.filename)
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\code.py", line 76, in runsource
    code = self.compile(source, filename, symbol)
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\codeop.py", line 168, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\codeop.py", line 82, in _maybe_compile
    code = compiler(source, filename, symbol)
  File "D:\Repositories\_cf\Builds\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\plugins\PythonScript\lib\codeop.py", line 135, in __call__
    if codeob.co_flags & feature.compiler_flag:
KeyboardInterrupt
>>> print 2
2

```

As I do not want to dig deeper at the moment, I commit the outstanding changes and stay with the 
edit control subclassing solution.

**Comment by Yaron10** [comment]
> As I do not want to dig deeper at the moment, I commit the outstanding changes and stay with the
edit control subclassing solution.

Thank you Claudia.

I've tried it with a Resource Editor.

![default](https://user-images.githubusercontent.com/10229320/43775275-c8a03d30-9a54-11e8-9ddf-922807d07c47.png)

The combo's and Run's top and height are equal. The >>>'s top should be reverted to 158.

The Run's *top and height* in `MoveWindow()` should be adapted.

![default](https://user-images.githubusercontent.com/10229320/43775479-83a42704-9a55-11e8-8827-1450d550cc04.png)

The combo's height should also be changed in `MoveWindow()` (it only affects the empty list initial height).
***
After opening the list, the text in the EditBox is cleared on every Run.

Thanks again. I apologize for the extra work.

**Comment by ClaudiaFrank** [comment]
Hi Yaron,

>Concerning >>> position, I gave up placing the controls - it always looks crappy to me.

I won't spend any more time figuring out what might look best - if you know the positions,
let me know and I will modifiy the needed files and commit it. Sorry but this drives me nuts.

>After opening the list, the text in the EditBox is cleared on every Run.

Could you define exactly how it should be?

Thank you :-)

**Comment by Yaron10** [comment]
> Concerning >>> position, I gave up placing the controls - it always looks crappy to me.

No problem. I thought it would be easier once you knew the correct initial positions.

Should `Run` be moved on `WM_SIZE`?

> Could you define exactly how it should be?

Just like the Find Dlg: the string should be kept in the box.
Currently (after your recent changes) it's kept as long as you don't open the list.

Thank you.

**Comment by ClaudiaFrank** [comment]
>Should Run be moved on WM_SIZE?

Don't get it, what do you mean? The control, obviously, must be repositioned once the window moves
so you must have something else in mind what I don't get.

>Just like the Find Dlg: the string should be kept in the box.

After return key or Run button pressed, correct?

**Comment by ClaudiaFrank** [comment]
As of now, you probably already know what the glitch was :-)

**Comment by ClaudiaFrank** [comment]
Hi Yaron,
if you don't want to use VS what about using a python script?

```
import ctypes
from ctypes.wintypes import BOOL, HWND, LPARAM, RECT

EnumWindowsProc = ctypes.WINFUNCTYPE(BOOL, HWND, LPARAM)

def foreach_window(hwnd, lParam):
    if ctypes.windll.user32.IsWindowVisible(hwnd):
        curr_class = ctypes.create_unicode_buffer(256)
        ctypes.windll.user32.GetClassNameW(hwnd, curr_class, 256)


        length = ctypes.windll.user32.GetWindowTextLengthW(hwnd) + 1
        if length > 1:
            buffer = ctypes.create_unicode_buffer(length)
            res = ctypes.windll.user32.GetWindowTextW(hwnd, buffer, length)
            if res == 0:
                _last_error = ctypes.windll.kernel32.GetLastError()
                if _last_error != 0:
                    print 'GetLastError:{}'.format(_last_error)

            if (curr_class.value == u'#32770') and (buffer.value == u'Python Script'):
                print '{}:{}'.format(curr_class.value, hwnd)
                rect = RECT()
                ctypes.windll.user32.GetClientRect(hwnd, ctypes.byref(rect))
                for field, value in rect._fields_:
                    print '{}:{}'.format(field, eval('rect.{}'.format(field)))

            elif (curr_class.value == u'Button') and (buffer.value == u'Run'):
                print '\n{}:{}'.format(curr_class.value, hwnd)
                rect = RECT()
                ctypes.windll.user32.GetWindowRect(hwnd, ctypes.byref(rect))
                for field, value in rect._fields_:
                    print '{}:{}'.format(field, eval('rect.{}'.format(field)))
                return False
    return True

npp_hwnd = ctypes.windll.user32.FindWindowW(u'Notepad++', None)
res = ctypes.windll.user32.EnumChildWindows(npp_hwnd, EnumWindowsProc(foreach_window), 0)
```

this should result in something like

#32770:199726
left:0
top:0
right:733
bottom:709

Button:134242
left:1633
top:829
right:1683
bottom:854

Now use the MoveWindow Api to let the button move like

```
ctypes.windll.user32.MoveWindow(134242, 733-50-1, 709-23-3, 50, 23, True)

```

**Comment by Yaron10** [comment]
Hello Claudia,

Thank you for the script.

With
`MoveWindow(::GetDlgItem(_hSelf, IDC_RUN), LOWORD(lParam)-50, HIWORD(lParam)-25, 50, 21, TRUE);`

the button is perfectly aligned with the combo.

![default](https://user-images.githubusercontent.com/10229320/43931861-8043a404-9c49-11e8-8790-3af33ea9db8a.png)
***
`MoveWindow(m_hCombo, 30, HIWORD(lParam)-25, LOWORD(lParam)-85, 50, TRUE);`

I haven't tested this but it should just change the initial empty list height.

Could you replace the two lines?
Thanks.

**Comment by Yaron10** [comment]
Thank you Claudia.

You did a great job positioning the combo and `>>>`. :+1: 

![default](https://user-images.githubusercontent.com/10229320/43962046-4da29bc4-9cbf-11e8-929b-279f9ee4de9c.png)

Thanks also for your other recent improvements. Much appreciated.
***
Scott,
Thank you for your help.
