### ISSUE TITLE
Can't have dir with no .py files in menuing "path" to .py file

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#72]
Not a great issue title.  :)
But here's the thing:

Make a folder under ...\\plugins\\Config\\PythonScript\\scripts\\ and call it test1\\.
(Manually) create a file called test3.py in the test1\\ folder.
Restart Notepad++ and see that you can see test3 (the .py file) in the menus:

![image](https://user-images.githubusercontent.com/30118311/40999887-4b4120ee-68da-11e8-918f-b35da2a1efd7.png)

That is all well and good and is expected behavior; it is just creating a "testbed" for the following:

Now use Windows Explorer to make a folder under ...\\plugins\\Config\\PythonScript\\scripts\\test1\\ and call it test2\\.
Move test3.py from test1\\ to test2\\.
Note test1\\ now has no other files or dirs besides the dir called test2\\
Restart Notepad++ and see that you cannot access test3 via the menus:

![image](https://user-images.githubusercontent.com/30118311/41000163-1c99cdee-68db-11e8-9005-b8ff56aaee1d.png)

Suspect that this is because test1\\ has no .py files in it.  In fact, picking up from the previous step, creating test4.py in the test1\\ folder results in correct behavior (after N++ restart):

![image](https://user-images.githubusercontent.com/30118311/41000330-adfe6cae-68db-11e8-8620-c6cbb1f0490b.png)

**Comment by sasumner** [comment]
...and I do concede it is a very MINOR issue.  :)

**Comment by alankilborn** [comment]
I just encountered this bug, when using PS2.0.  Had me scratching my head for a bit.  :-(

**Comment by chcg** [comment]
Happens at:
https://github.com/bruderstein/PythonScript/blob/50fd4982307041efa963788d6d352c398039f406/PythonScript/src/MenuManager.cpp#L441-L455

because on iteration through submenu an empty one is eliminated also if scripts are part of a deeper nested folder.

**Comment by alankilborn** [comment]
Thanks for the fix!
