### ISSUE TITLE
[Question] Is "To Input" command useful?

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#80]
Is the console output's context-menu command `To Input` useful?

Using the mouse, you can simply click in the Input field.
Using the keyboard, you can press `Tab` and the focus moves to Input.

Thank you.

**Comment by sasumner** [comment]
Haha.  The joke's on me.  I always thought that "To Input" would copy a highlighted selection to the `>>>` line for execution as a command!  Honestly, I never tried it because I never needed that.  Now, I've tried it and I see its real function (as described above by Yaron).  Thus my answer to the Question is NO.  But are you proposing its elimination?  It wouldn't bother me if it were removed but I'm sure there is someone somewhere that desperately needs it.  It does no harm, let it remain...

**Comment by Yaron10** [comment]
>  I always thought that "To Input" would copy a highlighted selection to the >>> line for execution as a command!

I also thought about that possibility and tested it before posting. :)

> I'm sure there is someone somewhere that desperately needs it.

No doubt about that!

> It does no harm, let it remain...

Why clutter the menu?

**Comment by sasumner** [comment]
@Yaron10, our backwards-compatibility hawk, @ClaudiaFrank will shoot down the idea of removal.  :)
It really does make you wonder why someone thought "To Input" was useful at the time it was added, doesn't it?

**Comment by Yaron10** [comment]
> It really does make you wonder why someone thought "To Input" was useful at the time it was added, doesn't it?

That "someone" is clever; so it's indeed a question. :)

**Comment by ClaudiaFrank** [comment]
hmmm .. source code

```

case 4: // To input (TODO: TEST only!)
						giveInputFocus();
						break;
```

**Comment by Yaron10** [comment]
:+1: 

Better late than never. :)

**Comment by chcg** [comment]
Indeed this seems to be superfluous. Added with commit:

> Revision: 61576ff7e35164d132a9de213fb3dde6409bbb4c
> Author: Dave Brotherstone <davegb@pobox.com>
> Date: 07.10.2012 13:34:30
> Message:
> Console Support for Tabbing between input and output windows
> 
> Tab to/from the Scintilla control in the console was previously not supported.  Requested for better support for blind users.
> 
> Many thanks to Ralf V. for the suggestion, and I hope it helps!
> ----
> Modified: .gitignore
> Modified: PythonScript/project/PythonScript2010.vcxproj
> Modified: PythonScript/project/PythonSettings.props
> Modified: PythonScript/src/ConsoleDialog.cpp
> Modified: PythonScript/src/ConsoleDialog.h
> Modified: PythonScript/src/PythonConsole.cpp
> 
> 

So I will remove the test part.

**Comment by Yaron10** [comment]
:+1: 

Thank you.
