### ISSUE TITLE
notepad.prompt() input control won't accept input

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#81]
The notepad.prompt() input area control has a bug.  It appears to be capable of five lines of input.  So try the following by entering it at the PS console's `>>>` prompt:

`notepad.prompt('','','a\r\nb\r\nc\r\nd\r\ne\r\n')`

The dialog box appears and a/b/c/d/e lines appear (pre-selected) within it.  Now use the up-arrow key to move the caret up to the top line (before the 'a').  Now type some alphanumeric characters, which should be inserted before the 'a'...but they are not; nothing appears.

**Comment by ClaudiaFrank** [comment]
Ready for close?

**Comment by sasumner** [comment]
That appeared to be an easy fix.  Next time I'll ask for the entire window to be made bigger, since it is my "preferred user interface"...over Tk (ugh) at least.  :)

**Comment by ClaudiaFrank** [comment]
I wonder why you didn't ask for monospace font to make you "Guis" even more easy to format? :-)

**Comment by chcg** [comment]
@sasumner @ClaudiaFrank 
So this is fixed with V1.2? Is this correct?

**Comment by ClaudiaFrank** [comment]
Yes

**Comment by sasumner** [comment]
@chcg I agree that it is fixed
