### ISSUE TITLE
Wrong line in Syntax Error message

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#86]
Run the following script.

```
editor.home(
editor.lineEndExtend()
editor.copy()
```

Result:

![default](https://user-images.githubusercontent.com/10229320/41978546-c1ef254a-7a2a-11e8-8021-6656bb11baff.png)

The error is in line 1.

Thank you.

**Comment by ClaudiaFrank** [comment]
>The error is in line 1.

But not from pythons point of view - python assumes editor.lineEndExtend() to be the first parameter
to editor.home and starting by editor.copy it knows that something is wrong.

**Comment by Yaron10** [comment]
Clever! :+1: 

Changing `editor.home(` to `editor.home)`, line 1 appears in the error message.

Thank you.
