### ISSUE TITLE
>>> in Console changes to - - -

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#88]
STR:
Run (several times) `notepad.getCurrentView(` from the console.

Result:

![default](https://user-images.githubusercontent.com/10229320/42064411-cdcf8d0e-7b3e-11e8-8eff-147eac24ce09.png)

**

STR:
Run `notepad.getCurrentView(`.
Run (several times) `notepad.getCurrentView()` *[correct syntax]*.

Result:

![default](https://user-images.githubusercontent.com/10229320/42064727-1240e9d2-7b40-11e8-9553-62d6ea5f98fa.png)

Thank you.

**Comment by ClaudiaFrank** [comment]
This is the same kind of error we discussed at #86 - if you want to confuse the python interpreter
you can certainly do it but not sure what you expect in such cases.

**Comment by sasumner** [comment]
@ClaudiaFrank said:

> if you want to confuse the python interpreter you can certainly do it but not sure what you expect in such cases.

Not sure if this is what @Yaron10 is getting at, but I *think* he is hoping that the Pythonscript console never gets "confused"...i.e, handles even bad interpreter confusion perfectly.  :-D

**Comment by ClaudiaFrank** [comment]
That would be nice, wouldn't it :-D
But I should have rephrased me answer - `not sure what you expect in such **test** cases`.
The prompt issue was a race condition I introduced, that's for sure but I don't get how testing
python is ...  now that I'm typing this I see the benefit - without testing it, it would have, maybe, taken some time before this race condition would have been found. So good job, Yaron.

**Comment by Yaron10** [comment]
@sasumner,

> Not sure if this is what @Yaron10 is getting at, but I think he is hoping that the Pythonscript console never gets "confused"...i.e, handles even bad interpreter confusion perfectly. :-D

:+1: 
I couldn't have phrased it better. :) Thank you.
***
I didn't know `...` was a legit output prefix. Could you please enlighten me as to the cases it should appear?
Is `- - -` instead of `>>>` also legit? In what cases?

`notepad.getCurrentView(` can be a common (innocent :) ) mistake.
So the following case should be considered a bug IMO.

Run `notepad.getCurrentView(`.
Run `notepad.getCurrentView()` (you've realized the mistake and corrected it).

Result:
`... notepad.getCurrentView()`

Run `notepad.getCurrentView()` again.

Result:
Syntax error.

Thank you.

**Comment by ClaudiaFrank** [comment]
... is the visual representation to inform the user that a code block is going on.
so something like

```
>>> if i==1:
...     print 1
... else:
...     print 'not 1'
```

is what should happen. I agree that after an exception, the prompt should be set to >>> again, that's
what the fix is, hopefully, addressing.

I don't know the reason why --- is rendered in your case. Maybe some font issue but the code hasn't had any minus sign in it (afaik).

Concerning the bug - are you referring to the syntax error? If so, no, because python treats the whole
input as a code block and only after seeing the second correct notepad.getCurrentView() it knows that this code block doesn't make sense.

If you mean something different, then may I ask for clarification?

**Comment by sasumner** [comment]
@Yaron10 No, I can't reproduce it and don't recall ever seeing it that way...maybe you are unique? :-)

**Comment by Yaron10** [comment]
Hello Scott,

Thank you for testing it. Appreciated.

> maybe you are unique?

Good intuition, my friend. :)
