### ISSUE TITLE
editor.getTextRange() with bad argument

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#90]
consider this one-liner:
`for j in xrange(10): print editor.getTextRange(-1, 1)`

for me, this will put the following in my PS (1.2.0.0) console:
![image](https://user-images.githubusercontent.com/30118311/42098457-fad29f72-7b88-11e8-8689-c08a93869bf7.png)

Okay, so if I intentionally use `-1` as the first arg to .getTextRange() then it is on me.  But frequently this is a *calculated* value and programmers often get the calculation *wrong*.  I guess I would, as a Python programmer, expect some sort of exception to be raised in this event...to let me know loudly...because it *can* be detected.  But...in general it seems as if exceptions aren't raised for the `editor` and `notepad` objects in PS.  :-(

I'm okay with the exception philosophy in PS (if that's what it truly is), but then I would think that .getTextRange() should internally change a bad first (and/or second!) argument into a good value before getting the text from Scintilla; and it shouldn't give a different result each time.  So I'd suggest some internal code like:  `if first_arg < 0: first_arg = 0` before an attempt is made to retrieve the text.

Thoughts?

**Comment by sasumner** [comment]
>not strictly true

Do note that I said "in general"...it's just my experience...maybe I've missed some areas where exceptions ARE thrown on errors...

Anyway, is there agreement that `.getTextRange()` needs some "exception love"?

**Comment by ClaudiaFrank** [comment]
>Do note that I said "in general"...

Noted - now :-D

>Anyway, is there agreement that .getTextRange() needs some "exception love"?

To be honest, I'm not a big fan. I see the benefit but I don't think it is in the responsibility of PS to
take care that either the underlying object returns proper data or the script calling the method is providing valid values. PS should take care that data exchange between script-python-script is working
flawlessly. Having said this, I know that PS is checking some methods to make sure npp
isn't crashing but I guess this is a little bit different. _But this is only my opinion_.

**Comment by sasumner** [comment]
I suppose I see that point of view if PS is just a data-exchanger.  I guess I was hoping it could be something more than that...maybe be what one expects from API code written in Python.

But I guess some wrapper functions I have like the following can live on and be carried around (on my Mac now so just typing the following in untested pseudo-python, i.e., totally from memory):

def editor_getTextRange(start, end):
 if start < 0:
  raise IndexError
 elif end > editor.getTextLength():
  raise IndexError
 else:
  return editor.getTextRange(start, end)

**Comment by alankilborn** [comment]
I got bit by this today.
I didn't realize that I collected some sel-start and sel-end positions, then created a new document, and tried to getTextRange() using the previous document's position data.
I got garbage strings.
It took me a while to figure it out.
I suppose I will use the "solution" proposed by @sasumner just above, but..
@chcg What do you think of raising an exception in the actual PS code for this?

**Comment by chcg** [comment]
There is already some check:

https://github.com/bruderstein/PythonScript/blob/7bbc09d595b0d7faa76645fd44da1934e02c4d1a/PythonScript/src/ScintillaWrapperGenerated.cpp#L2281-L2295

Maybe it need to be extended for some additional cases.

**Comment by alankilborn** [comment]
So `-1` for `end` is supposed to be a special signal value to get the text from `start` to the end of the document.
Special signals are not a great idea, mainly (for this following example) because I could do a calculation to determine `end` and if I maybe mess up that calculation instead of getting an error, it could go unnoticed and the function just returns unintended text.  I'd prefer to be perhaps loudly informed that I have an error.

Wouldn't it be better served to have a default argument for `end` for this purpose?
e.g., in Python-speak:  `def getTextRange(start, end=None)` or similar?

>There is already some check

That's fine, but it isn't much of a check.
Very easy to get garbage text if `start` and `end` are not within valid document positions.

**Comment by alankilborn** [comment]
@chcg Can I suggest reopening?
