### ISSUE TITLE
"Add an additional EOL..." does not work in 1.2.0.68

### ISSUE THREAD

**Issue by Yaron10** [bruderstein/PythonScript#93]
It seems that https://github.com/bruderstein/PythonScript/pull/89 breaks the `Add an additional EOL...` setting.

Could you please have a look?

Thank you.

**Comment by ClaudiaFrank** [comment]
wip

**Comment by Yaron10** [comment]
Thank you Claudia. I appreciate your work.

**Comment by Yaron10** [comment]
Hello Claudia,

:+1: 
Thank you for the fix.

A minor point: no additional EOL after "...Ready".

![default](https://user-images.githubusercontent.com/10229320/42760244-7f40f2cc-8912-11e8-99da-f14e3de176bd.png)

**Comment by ClaudiaFrank** [comment]
Yes as this isn't a statement what has been executed via console dialog run field.
I'm having in mind that we agreed on that, haven't we? Did I misunderstand something?

**Comment by Yaron10** [comment]
I don't remember all the various scenarios. :)
But with 1.2.0.67, there *is* an extra EOL in that case.

**Comment by ClaudiaFrank** [comment]
Actually this should work -  as the eol is put in front of the prompt.
I guess I know where to look - phew.

**Comment by Yaron10** [comment]
Fixed in 1.2.0.73.
:+1: 

Thank you Claudia. I appreciate your patience.

**Comment by ClaudiaFrank** [comment]
My patience? It's your patience which needs to be appreciated :-)

**Comment by Yaron10** [comment]
Thank you Claudia. I appreciate your kindness.

> My kindness? It's your kindness which needs to be appreciated :-)

:)

**Comment by sasumner** [comment]
OMG, guys....please stop!  
I am feeling way to0 much <3 <3 <3 here...  
:)
