### ISSUE TITLE
Coloring in console output window does not work reliably

### ISSUE THREAD

**Issue by ClaudiaFrank** [bruderstein/PythonScript#95]
If the output to be written is large, like in help(editor) it happens that not everything is colored.

![grafik](https://user-images.githubusercontent.com/16170444/42734220-8630aa1e-8840-11e8-835d-198c6bf23711.png)

I assume this goes in hand with the scintilla error messages one gets if running python script in debug mode.
Investigation ongoing.

**Comment by Yaron10** [comment]
Hello Claudia,

This is also caused by https://github.com/bruderstein/PythonScript/pull/89 (as https://github.com/bruderstein/PythonScript/issues/93).

While back at it, how about coloring links (to files in script errors) in blue?

**Comment by Yaron10** [comment]
> This is also caused by #89 (as #93).

Correction.
I tested it with 1.2.0.67 and couldn't reproduce it (and hence the wrong conclusion).
I can not reproduce it with 1.2.0.71 either.

**Comment by ClaudiaFrank** [comment]
>how about coloring links (to files in script errors) in blue?

Once I understand what is going on it shouldn't be too hard to make this work

**Comment by Yaron10** [comment]
:+1: 
Thank you and best of luck.

**Comment by ClaudiaFrank** [comment]
This is weird - if I add a breakpoint or a outputdebugstring statement the error is gone,
as soon as I remove those the error reapears. 
Solution: using indicator instead of different style to color output - did 100 runs and no issue was reported,

@Yaron10 - to change the color of the use something like

`console.editor.styleSetFore(2,(0,0,255))`

in either machine or user startup file.

**Comment by Yaron10** [comment]
> to change the color of the use something like
console.editor.styleSetFore(2,(0,0,255))

Thank you Claudia. I appreciate it.
