### ISSUE TITLE
"See Scintilla documentation for ..." broken in the documentation

### ISSUE THREAD

**Issue by sasumner** [bruderstein/PythonScript#96]
In PS 1.0.8.0, clicking on a link in the help file, e.g., 
![image](https://user-images.githubusercontent.com/30118311/42965553-5e347f74-8b68-11e8-9ffe-e8743f399657.png)

would take me here (note, still within the CHM file!):
![image](https://user-images.githubusercontent.com/30118311/42965563-67315fc0-8b68-11e8-9bdb-2f3305292938.png)

Now, in PS 1.2.0.0, , clicking on the same link in the help file takes me to my default browser (chrome) and leaves me looking at this:
![image](https://user-images.githubusercontent.com/30118311/42965678-9ef5133e-8b68-11e8-8573-910cba8f38a1.png)

**Comment by Yaron10** [comment]
Seems to be a good catch.
:+1:

**Comment by sasumner** [comment]
I guess I wouldn't have "issue'd" this if I had been jumped to the right place in chrome, i.e., right to the SCI_DELETERANGE entry.  Meaning, the change from staying-within-the-help to going to a browser wouldn't have phased me.

**Comment by Yaron10** [comment]
Another good point.

Claudia will soon write: "Guys, please stop it!". :)

**Comment by ClaudiaFrank** [comment]
Guys ... :-D
From rst source it looks ok. If I use sphinx-view I do get directly to the scintilla page (for example SCI_DELETERANGE) so I assume it has something to do how the chm file has been created 
but to be honest I've never done it before. Batch says something about html help workshop.
Hmmm ???

**Comment by ClaudiaFrank** [comment]
Ha, MS says I need to install IE in order to use html help workshop -> this will never happen.
@chcg - any idea what could have caused it? AppVeyor setup?

**Comment by chcg** [comment]
@ClaudiaFrank Maybe or the update of sphinx (1.7.5 vs. 1.2.2) or the html help version. Just tested that 1.0.8 chm really uses a direct internet access as the current scintilla website is shown, so no buildin one.

Link to subitem is available in the rst file, but is lost in opening from external browser, e.g.:

`   See Scintilla documentation for `SCI_CLEARDOCUMENTSTYLE <http://www.scintilla.org/ScintillaDoc.html#SCI_CLEARDOCUMENTSTYLE>`_`

**Comment by ClaudiaFrank** [comment]
I have searched the web for alternatives but it looks like all of them use their own frontend but in the end
html help workshop is used to compile it.
I will setup another VM with IE and hhw - and will try digging into it. 
@chcg do you have knowledge if some special setup is needed or plain install is sufficient?

**Comment by chcg** [comment]
@ClaudiaFrank Don't have a deeper knowledge, but I don't remember there are setup options on installation of hh.

**Comment by ClaudiaFrank** [comment]
Yes, looks like the new sphinx version is the culprit. It introduced a new feature target=_blank which
is automatically set when links are discoverd. If I remove this new attribute then the newly created
chm opens the link within its window correctly. https://github.com/sphinx-doc/sphinx/issues/2550
Need to dig a little bit deeper as the idea of the attribute was to open the link in the browser which
unfortunate does not work correctly.

**Comment by chcg** [comment]
Thanks for investigation on this.

**Comment by ClaudiaFrank** [comment]
no problem :-)
